### ISSUE TITLE
🐛[BUG] 国产发行版deepin下 开启 github 加速一直提示443端口占用

### ISSUE THREAD

**Issue by tensor-tech** [BeyondDimension/SteamTools#1157]
### 🐛 描述(Description)

点击 一键加速， 提示端口443 占用,但是并没有程序占用443端口

### 📷 复现步骤(Steps to Reproduce)

1. 勾选github 加速，选用Hosts 代理模式 
2. 点击 一键加速， 提示端口443 占用
3. 杀死全部 占用443 端口的程序 也是 提示端口占用

### 📄 [异常/日志]信息([Exception/Log] Information)
2022-03-19 15:15:26.6424|Error|GetDownloadingAppList|GetDownloadApp Error | System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Application.Services.Implementation.SteamServiceImpl.GetDownloadingAppList()
2022-03-19 15:16:17.5239|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Error occured in whilst handling the client
 ---> System.Exception: Could not establish connection to content-autofill.googleapis.com :
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
2022-03-19 15:19:17.7820|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'github.com' with certificate 'github.com'.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
2022-03-19 15:19:17.7820|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'github.com' with certificate 'github.com'.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
2022-03-19 15:19:17.7820|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'github.com' with certificate 'github.com'.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
2022-03-19 15:19:29.7050|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'github.com' with certificate 'github.com'.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
2022-03-19 15:19:29.7114|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'github.com' with certificate 'github.com'.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
2022-03-19 15:19:32.4614|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Error occured in whilst handling the client
 ---> System.Exception: Could not establish connection to accounts.google.com :
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
2022-03-19 15:19:36.5760|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Error occured in whilst handling the client
 ---> System.Exception: Could not establish connection to content-autofill.googleapis.com :
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---
2022-03-19 15:19:37.8203|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.Exception: Could not establish connection to www.gstatic.com 163.163.0.29:41694
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.RetryPolicy`1.ExecuteAsync(Func`2 action, Func`1 generator, TcpServerConnection initialConnection)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(SessionEventArgs args, TcpServerConnection serverConnection, SslApplicationProtocol sslApplicationProtocol, CancellationToken cancellationToken, CancellationTokenSource cancellationTokenSource)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
2022-03-19 15:19:52.4822|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Error occured in whilst handling the client
 ---> System.Exception: Could not establish connection to accounts.google.com :
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
   --- End of inner exception stack trace ---

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):  2.6.9
- 系统版本号(OS Version):  deepin社区版 20.4
- 是否为应用商店版本(Whether it is a Store version): NO

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/30520357/159211852-6c3ed83b-d9fa-40f9-add2-acf4910b2fa9.png)
![image](https://user-images.githubusercontent.com/30520357/159212086-4cdd9d8f-6ac7-4f7f-a14f-b930a1151da3.png)

**Comment by Mossimos** [comment]
这个是因为 系统默认不允许非 root 占用 1024 以下的端口 建议先使用 系统代理模式使用
下个版本可用
sudo setcap cap_net_bind_service=+eip [程序的文件位置 例如 ： \home\xxx\desktop\steam++\steam++]
现有的发行版本 有判断无法使用该方法

**Comment by AkarinLiu** [comment]
请尝试更换系统代理模式，同时请发送图片

**Comment by buiawpkgew1** [comment]
@zhang335809116 https://www.dogfight360.com/blog/knowledge-base/%e8%a7%a3%e5%86%b3%e5%b8%b8%e8%a7%81%e7%9a%8480-443%e7%ab%af%e5%8f%a3%e8%a2%ab%e5%8d%a0%e7%94%a8%e9%97%ae%e9%a2%98/

**Comment by latiaoGG** [comment]
程序版本（程序版本）： 2.8.6
系统版本号（OS Version）： deepin社区版 V23
点击 一键加速， 提示端口443 占用,但是并没有程序占用443端口，产生空白log，
![截图_Steam++_20230907003211](https://github.com/BeyondDimension/SteamTools/assets/144264916/1df576d6-f0b3-40df-b625-5fa1d7524828)

**Comment by latiaoGG** [comment]
使用系统代理，无法打开steam社区，创意工坊

**Comment by latiaoGG** [comment]
使用 sudo su   ，这些指令都用了，没有效果
Linux Host文件权限
程序无法监听 443 端口，请执行下方命令允许程序监听 1024 以下端口( 以上 2.6.9 可用)
sudo setcap cap_net_bind_service=+eip /usr/share/Steam++/Steam++

（避免每次启动关闭加速需要输入密码）请打开终端执行以下命令
sudo chmod a+w /etc/hosts
（如输入上面命令还提示无法hosts错误请尝试执行下面命令）
sudo chmod a+r /etc/hosts

![截图_deepin-terminal_20230907012741](https://github.com/BeyondDimension/SteamTools/assets/144264916/493eccb8-c5a7-44d3-9ac0-d40c1dcaec34)

**Comment by Mossimos** [comment]
输入完命令后需要退出程序再启动 @latiaoGG

**Comment by latiaoGG** [comment]
![截图_dde-desktop_20230907014438](https://github.com/BeyondDimension/SteamTools/assets/144264916/28679026-79ef-43dd-8310-7241667dbf07)
![截图_选择区域_20230907014417](https://github.com/BeyondDimension/SteamTools/assets/144264916/e29a385b-7ce1-4ea2-8b87-4029bd18eb56)
![截图_steamwebhelper_20230907014402](https://github.com/BeyondDimension/SteamTools/assets/144264916/1a4a0e4a-1559-4e51-859e-6acdd118f6b8)
![截图_steamwebhelper_20230907013754](https://github.com/BeyondDimension/SteamTools/assets/144264916/05d36fdc-aeb6-4528-8722-7769b3e05eae)

**Comment by latiaoGG** [comment]
成功加速了，但是steam商店打不开了

**Comment by latiaoGG** [comment]
steam社区也打不开了

**Comment by Mossimos** [comment]
这个是 不信任证书 可以下载 个Chrome 去信任或者 安装
certutil  -A -d sql:$HOME/.pki/nssdb -n "SteamTools" -t C,, -i "证书路径"
或者等 3.0 马上就要发了
