### ISSUE TITLE
🐛[BUG] macOS 2.6.9b 无法删除证书

### ISSUE THREAD

**Issue by simon300000** [BeyondDimension/SteamTools#1165]
### 🐛 描述(Description)

点击移除证书，证书并不会被移除

类似下方的异常日志在「安装证书」也会出现，但是安装证书会弹出一个输入密码的框，移除证书不会

### 📷 复现步骤(Steps to Reproduce)

1. 打开应用
2. （如果没有安装证书）安装证书
3. 移除证书

### 📄 [异常/日志]信息([Exception/Log] Information)

```
2022-03-24 10:53:21.5419|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to remove root certificate trust  for CurrentUser store location. You may need admin rights.
 ---> System.Security.Cryptography.CryptographicException: Removing the requested certificate would modify admin trust settings, and has been denied.
   at Interop.AppleCrypto.X509StoreRemoveCertificate(SafeKeychainItemHandle certHandle, SafeKeychainHandle keychain, Boolean isReadOnlyMode)
   at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Remove(ICertificatePal cert)
   at System.Security.Cryptography.X509Certificates.X509Store.Remove(X509Certificate2 certificate)
   at Titanium.Web.Proxy.Network.CertificateManager.uninstallCertificate(StoreName storeName, StoreLocation storeLocation, X509Certificate2 certificate)
   --- End of inner exception stack trace ---
2022-03-24 10:53:21.5419|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to remove root certificate trust  for CurrentUser store location. You may need admin rights.
 ---> System.Security.Cryptography.CryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Titanium.Web.Proxy.Network.CertificateManager.uninstallCertificate(StoreName storeName, StoreLocation storeLocation, X509Certificate2 certificate)
   --- End of inner exception stack trace ---
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.9b
- 系统版本号(OS Version): macOS 12.3 (21E230
- 是否为应用商店版本(Whether it is a Store version): no

### 🖼 截图(Screenshots)

点击的按钮：
<img width="549" alt="image" src="https://user-images.githubusercontent.com/12656264/159832860-bfdba556-32cc-4ae2-8c5e-923ec0e2528f.png">

**Comment by rmbadmin** [comment]
看日志是mac上没有权限移除证书

**Comment by simon300000** [comment]
> 看日志是mac上没有权限移除证书

仅仅是看日志应该是…对的

这是添加证书，也有类似的日志
```
2022-03-24 11:11:16.8888|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights.
 ---> System.Security.Cryptography.CryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---
2022-03-24 11:11:16.9014|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights.
 ---> System.Security.Cryptography.CryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---
```

但是同时会弹出来一个这样的框，输入密码之后就可以正确添加证书
<img width="442" alt="image" src="https://user-images.githubusercontent.com/12656264/159834754-0d840ef5-6d25-44a0-a5e6-2f34c0f370ab.png">
我估计移除证书应该也会弹出来一个类似的框，但是不知道为什么没弹出来

**Comment by rmbadmin** [comment]
@Mossimos 增加一下mac移除证书时的密码框和指令，
以及考虑做一个停止加速时自动移除证书的设置项

**Comment by Mossimos** [comment]
可用手动去钥匙串管理里面 删除 SteamTools 的证书
如果有多个证书 的话会导致 终端指令删除很麻烦 
查询指令返回的数据如下
![image](https://user-images.githubusercontent.com/26396340/159847345-5a23203f-bdb5-4d63-8244-74ddda9b6994.png)
而且只能通过 SHA-1 指纹删除 旧证书丢失只能通过指令查询 但是指令中未包含 SHA-1

**Comment by rmbadmin** [comment]
> 可用手动去钥匙串管理里面 删除 SteamTools 的证书 如果有多个证书 的话会导致 终端指令删除很麻烦 查询指令返回的数据如下 ![image](https://user-images.githubusercontent.com/26396340/159847345-5a23203f-bdb5-4d63-8244-74ddda9b6994.png) 而且只能通过 SHA-1 指纹删除 旧证书丢失只能通过指令查询 但是指令中未包含 SHA-1

优先考虑删除当前存在的已安装证书的情况，遗失残留的旧证书暂不考虑

**Comment by simon300000** [comment]
现在这个软件的行为其实也有一点奇怪，不知道是只在我的电脑上这样还是普遍性

参考这里的代码：
https://github.com/BeyondDimension/SteamTools/blob/2af95b44910f2ee436d12819263e6f58d0e60199/src/ST.Client/Services/Implementation/HttpProxyServiceImpl.cs#L447

也就是类似这样的指令 `sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "/Users/username/Library/Steam++/SteamTools.Certificate.cer"`

手工在控制台输入会在系统钥匙链增加一个证书，如图：
<img width="725" alt="image" src="https://user-images.githubusercontent.com/12656264/159869968-1bfa01db-8228-4107-9484-28d7cb4dc371.png">

这里一切正常


但是软件的行为是什么呢
首先点击安装证书
此时会输出log

<details>
  <summary>log</summary>
  ```
2022-03-24 16:05:05.9940|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights.
 ---> System.Security.Cryptography.CryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---
2022-03-24 16:05:06.0067|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights.
 ---> System.Security.Cryptography.CryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---
```
</details>
弹出密码窗口
<img width="448" alt="image" src="https://user-images.githubusercontent.com/12656264/159870473-4349bc44-ca5a-4009-bb2d-b1ebf1466ba2.png">
Login钥匙串出现一个不被信任的证书
<img width="719" alt="image" src="https://user-images.githubusercontent.com/12656264/159870663-b0c4e76f-2cd7-4888-a1b5-8c5447aeda4b.png">
输入密码后系统钥匙串出现一个不被信任的证书
<img width="695" alt="image" src="https://user-images.githubusercontent.com/12656264/159871652-91dfe8f9-f51a-4b2f-9f8f-2367e3614b73.png">

此时进行一个密码/Touch ID验证，两个证书都被信任了
<img width="669" alt="image" src="https://user-images.githubusercontent.com/12656264/159871725-8407c706-9cba-4668-98e6-a636c2e46162.png">



也就是Login和System都会装一个证书，不知道为什么


如果要装Login就是把`/Library/Keychains/System.keychain`换成`~/Library/Keychains/login.keychain-db`
这样也不需要sudo了，理论上可能连那个密码弹窗也不需要了？
不过我也不知道这样装两个证书是不是因为什么原因有意做的，只是发现装了俩感觉有点怪

（老的macOS系统似乎文件结尾没有`-db`）

**Comment by Mossimos** [comment]
关于这个 其实是 钥匙串 访问 不是实时刷新的 你完全退出再开就剩下一个证书了  同理 终端删除证书也会是这样
关于安装到了 My 和 root 是因为 程序通过 My 的证书 来验证是否安装 之后会优化一下
今天一天 尝试了各种方法 发现 Net6 这个设置证书信任的压根没绑定 之后试试 swift 单独一个文件能不能操作 当前用户直接信任证书 （也会要输入密码）
!missing-pinvoke! SecTrustSetOptions is not bound.

一旦信任过也只能通过
sudo SHA-1 指纹删除

密码弹窗 主要是 我们程序是非 root 运行  无法执行 sudo 指令  
输入的密码 是写入文件 
echo '' | sudo -S xxxxxx 
这样执行（ps：这命令不用文件执行直接报错说非 root 程序无法运行 sudo 指令）
当然手动直接去钥匙串添加信任是最好。

**Comment by Mossimos** [comment]
已经修改了下个版本 不会安装到系统  的目录下了 导入的时候可以少输入一次密码
