### ISSUE TITLE
🐛[BUG] NRE in Avalonia.Controls.FluentWindow`1.FluentWindow_Opened

### ISSUE THREAD

**Issue by 123485k** [BeyondDimension/SteamTools#1234]
### 🐛 描述(Description)

Steam++无法启动
### 📷 复现步骤(Steps to Reproduce)

1.  将窗口最大化
2. 退出steam++
3. 重新进入

### 📄 [异常/日志]信息([Exception/Log] Information)
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.FluentWindow`1.FluentWindow_Opened(Object sender, EventArgs e)
   at Avalonia.Controls.TopLevel.OnOpened(EventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 466
   at Avalonia.Controls.Window.ShowCore(Window parent) in /_/src/Avalonia.Controls/Window.cs:line 707
   at Avalonia.Controls.Window.Show() in /_/src/Avalonia.Controls/Window.cs:line 631
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 129
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 118
   at System.Application.UI.Program.CommandLineTools.<>c__DisplayClass0_0.<Run>g__MainHandler_|1(Action onInitStartuped)
   at System.Application.UI.Program.CommandLineTools.<>c__DisplayClass0_0.<Run>g__MainHandler|0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):v2.6.9
- 系统版本号(OS Version): Ubuntu 20.04.4 LTS  
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by AigioL** [comment]
看起来 NRE 发生在这段代码中，可能是 ```Screens.Primary``` 中出现的 ```null```


https://github.com/BeyondDimension/SteamTools/blob/ef1971a907101ca2b369ebcaf8fd4631ae5fe4f6/src/ST.Client.Desktop.Avalonia/Application/UI/Views/Windows/WindowBase/FluentWindow.cs#L142-L182

等这个 Action 跑完可以下载编译后的 linux 包再尝试能否复现
https://github.com/BeyondDimension/SteamTools/actions/runs/2144224963

此 API 可能返回 null 值
```public Screen? Primary => All.FirstOrDefault(x => x.Primary);```
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Screens.cs#L17

**Comment by 123485k** [comment]
Action 没有生成linux包

**Comment by AigioL** [comment]
> Action 没有生成linux包

[[Release]Steam++_linux_x64_2433ea1](https://github.com/BeyondDimension/SteamTools/suites/6067363131/artifacts/209676189)

https://github.com/BeyondDimension/SteamTools/actions/runs/2145643200

**Comment by 123485k** [comment]
问题已修复，可以正常变化窗口大小
