### ISSUE TITLE
🐛[BUG] 导入令牌后确认交易看不见需要确认的交易

### ISSUE THREAD

**Issue by SZCDSB** [BeyondDimension/SteamTools#1263]
### 🐛 描述(Description)

 导入令牌后确认交易看不见需要确认的交易

 不知道是不是土区账号的问题.之前用国区账号能看到需要确认的交易
### 📷 复现步骤(Steps to Reproduce)

1. 挂梯子
2. 令牌-确认交易-登录
3. 刷新及注销后也无法看到需要确认的交易

### 🚑 基本信息(Basic Information)

- 程序版本(Program [Version):2.6.9
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/88022624/163192611-c957a924-8b1f-4ee4-80e8-c8887c316120.png)
![image](https://user-images.githubusercontent.com/88022624/163192685-dd8dbb69-cf97-40ec-906e-3ade53138cf1.png)

**Comment by rmbadmin** [comment]
确保导入的uuid和identity secret是正确的数据，这两个数据不正确会导致无法获取确认交易。

**Comment by xiansky** [comment]
之前反馈过确认交易的时候只能看到对方的头像，无法得知自己被交易的库存和对方的注册日期等

**Comment by Heporis** [comment]
> 确保导入的uuid和identity secret是正确的数据，这两个数据不正确会导致无法获取确认交易。

GitHub最新release2.7.2，同样无法获得待确认交易的信息，但是我把steam++里保存的令牌数据复制到[winauth](https://github.com/winauth/winauth)里，立马就能看到待确认的交易。

**Comment by Heporis** [comment]
> 确保导入的uuid和identity secret是正确的数据，这两个数据不正确会导致无法获取确认交易。

昨天的全部日志，我忘了具体什么时间确认的交易
`2022-07-14 13:41:35.4633|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.IO.IOException: Invalid http status code.
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
2022-07-14 13:41:36.6816|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.IO.IOException: Invalid http status code.
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
2022-07-14 16:01:45.2374|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.IO.IOException: Invalid http status code.
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
2022-07-14 16:50:49.0481|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.RetryPolicy`1.ExecuteAsync(Func`2 action, Func`1 generator, TcpServerConnection initialConnection)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(SessionEventArgs args, TcpServerConnection serverConnection, SslApplicationProtocol sslApplicationProtocol, CancellationToken cancellationToken, CancellationTokenSource cancellationTokenSource)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
`

**Comment by AigioL** [comment]
> > 确保导入的uuid和identity secret是正确的数据，这两个数据不正确会导致无法获取确认交易。
> 
> 昨天的全部日志，我忘了具体什么时间确认的交易 `2022-07-14 13:41:35.4633|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request ---> System.IO.IOException: Invalid http status code. at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) --- End of inner exception stack trace --- at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken) 2022-07-14 13:41:36.6816|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request ---> System.IO.IOException: Invalid http status code. at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) --- End of inner exception stack trace --- at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken) 2022-07-14 16:01:45.2374|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request ---> System.IO.IOException: Invalid http status code. at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) --- End of inner exception stack trace --- at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken) 2022-07-14 16:50:49.0481|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'. ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。 --- End of inner exception stack trace --- at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken) at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken) at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken) at Titanium.Web.Proxy.Network.RetryPolicy`1.ExecuteAsync(Func`2 action, Func`1 generator, TcpServerConnection initialConnection) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(SessionEventArgs args, TcpServerConnection serverConnection, SslApplicationProtocol sslApplicationProtocol, CancellationToken cancellationToken, CancellationTokenSource cancellationTokenSource) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) --- End of inner exception stack trace --- at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps) at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken) `

日志看上去都是加速相关的，没有令牌交易的错误内容
