### ISSUE TITLE
联通网使用discord加速经常卡转圈🧐[Question] 

### ISSUE THREAD

**Issue by bysghjx** [BeyondDimension/SteamTools#1270]
### 🧐 问题描述(Description)
联通网使用discord加速经常卡转圈消息加载失败

### 🚑 其他信息(Other Information)
` ---> System.Exception: Could not establish connection to discord.com 162.159.138.232:443
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.RetryPolicy`1.ExecuteAsync(Func`2 action, Func`1 generator, TcpServerConnection initialConnection)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(SessionEventArgs args, TcpServerConnection serverConnection, SslApplicationProtocol sslApplicationProtocol, CancellationToken cancellationToken, CancellationTokenSource cancellationTokenSource)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
`

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version): Windows11 22000.613
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
应该已经热更新修复
