### ISSUE TITLE
🧐[Question] steam++ 無法正常加速

### ISSUE THREAD

**Issue by deniszhu1991** [BeyondDimension/SteamTools#1343]
### 🧐 问题描述(Description)
當點擊一鍵加速時候會提出錯誤，讓我去log file 觀看日誌。
日誌如下

2022-05-06 15:20:51.2412|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 拒绝访问。
   at Internal.Cryptography.Pal.StorePal.Add(ICertificatePal certificate)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---
2022-05-06 15:20:51.3372|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 拒绝访问。
   at Internal.Cryptography.Pal.StorePal.Add(ICertificatePal certificate)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---

### 🚑 其他信息(Other Information)

- 程序版本(Program Version): windows 版本 v2.7.2
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by rmbadmin** [comment]
证书无法正常添加信任，请尝试手动添加证书文件到系统根证书信任区域
