### ISSUE TITLE
🧐[Question] Steam++无法正常加速社区页面和挂卡

### ISSUE THREAD

**Issue by royalparadise616** [BeyondDimension/SteamTools#1413]
### 🧐 问题描述(Description)

网络加速HOSTS模式和系统代理模式都没用
多次重新安装证书和重置Hosts文件steam商店一样报错误代码-324
原官网Windows版卸载换微软商店版加速也无效

Logs File的日志
2022-05-18 17:11:07.3787|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Exception thrown in user event
 ---> DnsClient.DnsResponseException: Query 58944 => steamcommunity.rmbgame.net IN A on 223.5.5.5:53 timed out or is a transient error.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.Tasks.TaskExtensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   at DnsClient.LookupClient.QueryInternalAsync(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.DnsAnalysisServiceImpl.AnalysisDomainIpByCustomDns(String url, IPAddress[] dnsServers, Boolean isIPv6)
   at System.Application.Services.Implementation.HttpProxyServiceImpl.GetReverseProxyIp(String url, IPAddress proxyDns, Boolean isDomain)
   at System.Application.Services.Implementation.HttpProxyServiceImpl.OnRequest(Object sender, SessionEventArgs e)
   at Titanium.Web.Proxy.Extensions.FuncExtensions.internalInvokeAsync[T](AsyncEventHandler`1 callback, Object sender, T args, ExceptionHandler exceptionFunc)
   --- End of inner exception stack trace ---
2022-05-18 17:11:07.4591|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.Exception: A client is making HTTP request to one of the listening ports of this proxy steamcommunity.com:443
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.RetryPolicy`1.ExecuteAsync(Func`2 action, Func`1 generator, TcpServerConnection initialConnection)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(SessionEventArgs args, TcpServerConnection serverConnection, SslApplicationProtocol sslApplicationProtocol, CancellationToken cancellationToken, CancellationTokenSource cancellationTokenSource)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)

挂卡问题
2022-05-18 17:15:19|Steam++-12768|INFO|GK|IsAnythingToFarm() 正在检查 Steam 徽章页面的第一页……
2022-05-18 17:15:34|Steam++-12768|WARN|GK|Init() System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SteamKit2.WebAPI.AsyncInterface.CallAsyncInternal(HttpMethod method, String func, Int32 version, Dictionary`2 args, String expectedFormat)
   at SteamKit2.WebAPI.AsyncInterface.CallAsync(HttpMethod method, String func, Int32 version, Dictionary`2 args)
   at ArchiSteamFarm.Steam.Integration.ArchiWebHandler.<>c__DisplayClass68_0.<<Init>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ArchiSteamFarm.Steam.Integration.ArchiWebHandler.WebLimitRequest[T](Uri service, Func`1 function)
   at ArchiSteamFarm.Steam.Integration.ArchiWebHandler.Init(UInt64 steamID, EUniverse universe, String webAPIUserNonce, String parentalCode)

### 🚑 其他信息(Other Information)

![1652865444](https://user-images.githubusercontent.com/56012319/169005938-a2c1571b-29cd-4d89-9bb9-7fb9dc3e7b70.png)
![1652865770(1)](https://user-images.githubusercontent.com/56012319/169005968-37f65ef6-8b3d-4a7b-8b5b-b3b6d08802c9.png)

- 程序版本(Program Version): Windows 版本v2.7.3
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 是(Yes)

**Comment by AigioL** [comment]
```
DnsClient.DnsResponseException: Query 58944 => steamcommunity.rmbgame.net IN A on 223.5.5.5:53 timed out or is a transient error.
```

看起来是阿里 DNS 解析域名超时导致的，换一个 DNS 试一试，在网络加速 - 代理设置 - 自定义代理 DNS 中选其他的值

**Comment by royalparadise616** [comment]
成功了！多谢！

**Comment by royalparadise616** [comment]
成功了！多谢！ @AigioL
