### ISSUE TITLE
🧐[Question] 无法确认 Steam 令牌交易

### ISSUE THREAD

**Issue by thaoeu** [BeyondDimension/SteamTools#1418]
### 🧐 问题描述(Description)

Steam++ 可以加载到需要确认的交易，但无法确认或取消；
### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/34019378/169643467-ca410051-e4ac-410a-9ca8-c6c886cf4659.png)

- 程序版本(Program Version):2.7.2
- 系统版本号(OS Version): Windows 10.19044.1706
- 是否为应用商店版本(Whether it is a Store version): 否(No)

**Comment by thaoeu** [comment]
相关日志：
```
2022-05-21 16:35:40.9068|Error|FileToAppInfo|c:\program files (x86)\steam\steamapps\appmanifest_714010.acf | Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Application.Services.Implementation.SteamServiceImpl.GetInt64(Object value)
   at CallSite.Target(Closure , CallSite , SteamServiceImpl , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Application.Services.Implementation.SteamServiceImpl.FileToAppInfo(String filename)
2022-05-21 16:35:41.0854|Error|FileToAppInfo|c:\program files (x86)\steam\steamapps\appmanifest_714010.acf | Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Application.Services.Implementation.SteamServiceImpl.GetInt64(Object value)
   at CallSite.Target(Closure , CallSite , SteamServiceImpl , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Application.Services.Implementation.SteamServiceImpl.FileToAppInfo(String filename)
2022-05-21 16:37:07.8682|Error|Image2|DecodeImage | System.ArgumentNullException: Value cannot be null. (Parameter 'data')
   at SkiaSharp.SKImage.FromEncodedData(SKData data)
   at Avalonia.Skia.SkiaSharpHelpers.FromEncodedData(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.Avalonia.Platform.IPlatformRenderInterface.LoadBitmap(Stream stream)
   at Avalonia.Media.Imaging.Bitmap..ctor(Stream stream) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 72
   at AvaloniaGif.Image2.DecodeImage(Stream stream)
2022-05-21 16:37:07.9413|Error|Image2|DecodeImage | System.ArgumentNullException: Value cannot be null. (Parameter 'data')
   at SkiaSharp.SKImage.FromEncodedData(SKData data)
   at Avalonia.Skia.SkiaSharpHelpers.FromEncodedData(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.Avalonia.Platform.IPlatformRenderInterface.LoadBitmap(Stream stream)
   at Avalonia.Media.Imaging.Bitmap..ctor(Stream stream) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 72
   at AvaloniaGif.Image2.DecodeImage(Stream stream)
2022-05-21 16:37:07.9524|Error|Image2|DecodeImage | System.ArgumentNullException: Value cannot be null. (Parameter 'data')
   at SkiaSharp.SKImage.FromEncodedData(SKData data)
   at Avalonia.Skia.SkiaSharpHelpers.FromEncodedData(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.Avalonia.Platform.IPlatformRenderInterface.LoadBitmap(Stream stream)
   at Avalonia.Media.Imaging.Bitmap..ctor(Stream stream) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 72
   at AvaloniaGif.Image2.DecodeImage(Stream stream)
2022-05-21 16:37:07.9617|Error|Image2|DecodeImage | System.ArgumentNullException: Value cannot be null. (Parameter 'data')
   at SkiaSharp.SKImage.FromEncodedData(SKData data)
   at Avalonia.Skia.SkiaSharpHelpers.FromEncodedData(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.Avalonia.Platform.IPlatformRenderInterface.LoadBitmap(Stream stream)
   at Avalonia.Media.Imaging.Bitmap..ctor(Stream stream) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 72
   at AvaloniaGif.Image2.DecodeImage(Stream stream)
2022-05-21 16:37:08.1486|Error|Image2|DecodeImage | System.ArgumentNullException: Value cannot be null. (Parameter 'data')
   at SkiaSharp.SKImage.FromEncodedData(SKData data)
   at Avalonia.Skia.SkiaSharpHelpers.FromEncodedData(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.Avalonia.Platform.IPlatformRenderInterface.LoadBitmap(Stream stream)
   at Avalonia.Media.Imaging.Bitmap..ctor(Stream stream) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 72
   at AvaloniaGif.Image2.DecodeImage(Stream stream)
2022-05-21 16:37:08.1794|Error|Image2|DecodeImage | System.ArgumentNullException: Value cannot be null. (Parameter 'data')
   at SkiaSharp.SKImage.FromEncodedData(SKData data)
   at Avalonia.Skia.SkiaSharpHelpers.FromEncodedData(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.Avalonia.Platform.IPlatformRenderInterface.LoadBitmap(Stream stream)
   at Avalonia.Media.Imaging.Bitmap..ctor(Stream stream) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 72
   at AvaloniaGif.Image2.DecodeImage(Stream stream)
2022-05-21 16:37:08.2327|Error|Image2|DecodeImage | System.ArgumentNullException: Value cannot be null. (Parameter 'data')
   at SkiaSharp.SKImage.FromEncodedData(SKData data)
   at Avalonia.Skia.SkiaSharpHelpers.FromEncodedData(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.Avalonia.Platform.IPlatformRenderInterface.LoadBitmap(Stream stream)
   at Avalonia.Media.Imaging.Bitmap..ctor(Stream stream) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 72
   at AvaloniaGif.Image2.DecodeImage(Stream stream)
```

**Comment by rmbadmin** [comment]
日志里看起来是没有记录到相关错误，但出现这个问题应该是请求steam接口是返回了错误的结果或者失败，尝试重新登录或者重新上架物品确认

**Comment by thaoeu** [comment]
好的，非常感谢，我尝试一下。
