### ISSUE TITLE
🧐[Question] Failed to make system trust root certificate for Root\CurrentUser store location. You may need admin rights.

### ISSUE THREAD

**Issue by liudi1996** [BeyondDimension/SteamTools#1430]
### 🧐 问题描述(Description)
启动加速服务失败，遇到未知错误

2022-05-24 22:53:58.6010|Error|HttpProxyS|ProxyServer ExceptionFunc | System.Exception: Failed to make system trust root certificate  for Root\CurrentUser store location. You may need admin rights.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 拒绝访问。
   at Internal.Cryptography.Pal.StorePal.Add(ICertificatePal certificate)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   --- End of inner exception stack trace ---
### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/69335815/170066316-4966491e-d119-4e32-849d-744bd4f3dbe8.png)

- 程序版本(Program Version):2.7.2
- 系统版本号(OS Version): Windows 11.22000.675
- 是否为应用商店版本(Whether it is a Store version): NO

**Comment by rmbadmin** [comment]
日志里已经给明原因，Failed to make system trust root certificate for Root\CurrentUser store location. You may need admin rights.
尝试手动安装证书吧，步骤参考https://steampp.net/faq#NoCer
