### ISSUE TITLE
🐛[BUG] Linux 下最新源代码构建的程序彻底爆炸

### ISSUE THREAD

**Issue by arenekosreal** [BeyondDimension/SteamTools#1449]
### 🐛 描述(Description)

Arch Linux 下执行自行从源代码构建的程序后无法运行
### 📷 复现步骤(Steps to Reproduce)

1. AUR 安装 `watt-toolkit-git` 这个从源代码构建的版本
2. 正常启动程序，从终端执行 watt-toolkit 启动的话可以看到详细错误
3. 完全无法启动程序

### 📄 [异常/日志]信息([Exception/Log] Information)

```
& zhanghua @ archlinux in ~/linux (master ✔) 0 [20:03:27]
~ watt-toolkit                                                                                                      0 [20:03:27]
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Avalonia.Win32.WindowImpl' from assembly 'Avalonia.Win32, Version=255.255.255.255, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'.
   at FluentAvalonia.UI.Controls.CoreWindow..ctor()
   at Avalonia.Controls.ReactiveCoreWindow`1..ctor()
   at Avalonia.Controls.FluentWindow`1..ctor(Boolean isSaveStatus)
   at Avalonia.Controls.FluentWindow`1..ctor()
   at System.Application.UI.Views.MainWindow..ctor()
   at System.Application.UI.App.<Initialize>b__23_0(IViewModelManager vmService)
   at System.Application.UI.Program.OnCreateAppExecuted(IProgramHost host, Action`1 handlerViewModelManager, Boolean isTrace)
   at System.Application.UI.Program.ProgramHost.System.Application.UI.IApplication.IDesktopProgramHost.OnCreateAppExecuted(Action`1 handlerViewModelManager, Boolean isTrace)
   at System.Application.UI.App.Initialize()
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at System.Application.UI.Program.CommandLineTools.<>c__DisplayClass0_0.<Run>g__MainHandler_|1(Action onInitStartuped)
   at System.Application.UI.Program.CommandLineTools.<>c__DisplayClass0_0.<Run>g__MainHandler|0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): GitHub 源代码自行构建，构建时的标签为 2.7.2.100-g15ad1a5c
- 系统版本号(OS Version): Arch Linux
- 是否为应用商店版本(Whether it is a Store version):  否

### 🖼 截图(Screenshots)
见异常信息

附：构建过程完全仿照 GitHub Action 的配置，从异常信息看似乎是 Windows 的一些组件被引入到 Linux 这边来了？另外，现在仓库的 GitHub Action 的配置文件里面已删除 ubuntu-latest 的构建配置，不知是否也与此有关

**Comment by AigioL** [comment]
这个问题之前修复过，当前的代码中是注释了这段的
在 https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Client.Desktop.Avalonia/Application/UI/Views/Windows/WindowBase/FluentWindow.cs#L36

**Comment by AigioL** [comment]
最近更新了 FluentAvalonia 库，在这个 CoreWindow 类构造函数上引用了 Avalonia.Win32.WindowImpl 这个类型
https://github.com/BeyondDimension/FluentAvalonia/blob/fe9f173444c26744e03b88128e57b9bebf004526/FluentAvalonia/UI/Controls/CoreWindow/CoreWindow.cs#L27
在非 Windows 平台现在是了个版本号最大值的空程序集强行替换实现的裁剪。

当前最新的提交中已修复

**Comment by arenekosreal** [comment]
经测试的确已修复这个问题。另外指出一个发现的 GitHub Action 配置的一个问题，Linux 下是无法安装 maui 工作负载的，因为目前的配置中没有 ubuntu-latest 所以构建没有问题。
