### ISSUE TITLE
🐛[BUG] Win7 Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 不支持请求的操作

### ISSUE THREAD

**Issue by SNWCreations** [BeyondDimension/SteamTools#1717]
### 🐛 描述(Description)

听闻出了 v2.8.1 ，我很快就下载了，毕竟用了一段时间这个软件了，很满意。
废话少说，说正事。
刚刚装上新版本，用这个加速 Github ，结果网页加载立刻失败。（现在用的是裸连，不稳定）
四种方法均已尝试，全部失败。
错误码: ERR_CONNECTION_CLOSED

目前等待此 Issue 修复，在此之前我会继续使用 v2.7 。

### 📷 复现步骤(Steps to Reproduce)

1. 安装 Watt Toolkit v2.8.1 （我保留了 v2.7 的备份）
2. 选择需要的加速项
3. 启动加速，用 DNS 驱动拦截模式（之后我用了其他方式，但还是失败）
4. 因为我之前用了 v2.7 ，程序提示我卸载证书，确定
5. 安装新证书，确定
6. 加速启动完成
7. 尝试访问 Github
8. 立刻失败

### 📄 [异常/日志]信息([Exception/Log] Information)

```
2022-07-24 09:47:44.5889|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HMJD2Q0BDA25. |ConnectionId=0HMJD2Q0BDA25 Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 不支持请求的操作。
   at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
   at System.Security.Cryptography.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
   at Org.BouncyCastle.Security.DotNetUtilities.GetRsaKeyPair(RSA rsa) in /_/crypto/src/security/DotNetUtilities.cs:line 100
   at System.Application.Services.Implementation.HttpServer.Certificates.CertGenerator.GenerateByCaPfx(IEnumerable`1 domains, Int32 keySizeBits, DateTime validFrom, DateTime validTo, String caPfxPath, String password)
   at System.Application.Services.Implementation.HttpServer.Certificates.CertService.<>c__DisplayClass12_0.<GetOrCreateServerCert>g__GetOrCreateCert|0(ICacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at System.Application.Services.Implementation.HttpServer.Certificates.CertService.GetOrCreateServerCert(String domain)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass1_0.<UseTls>b__1(ConnectionContext ctx, String domain)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.<>c__DisplayClass19_0.<DoOptionsBasedHandshakeAsync>b__0(Object sender, String name)
   at System.Net.Security.SslStream.ServerCertSelectionCallbackWrapper(String targetHost)
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at System.Application.Services.Implementation.HttpServer.Middleware.TlsInvadeMiddleware.InvokeAsync(ConnectionDelegate next, ConnectionContext context)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.8.1
- 系统版本号(OS Version): Windows 7 SP1
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

无有效截图。

**Comment by AigioL** [comment]
参考这个试一下 https://github.com/BeyondDimension/SteamTools/issues/1677#issuecomment-1189257953

**Comment by SNWCreations** [comment]
> 参考这个试一下 [#1677 (comment)](https://github.com/BeyondDimension/SteamTools/issues/1677#issuecomment-1189257953)

很抱歉，无效，我的操作系统没有这个文件夹。（或我无法找到）
补：我可以正常生成证书，v2.7 时每次使用前我都会重新生成证书（因为用一小会就会出问题）

我不能根据该 comment 提供的路径找到，但我在 C:\Users\Administrator\AppData\Roaming 找到了 Microsoft\Crypto\RSA 文件夹
但其中**没有** MachineKeys 文件夹，只有一个存放了大量“系统文件”的文件夹。
![QQ截图20220724101601](https://user-images.githubusercontent.com/59989459/180629372-88a3d7ac-be6a-403a-a601-4a3656099703.png)

**Comment by AigioL** [comment]
> > 参考这个试一下 [#1677 (comment)](https://github.com/BeyondDimension/SteamTools/issues/1677#issuecomment-1189257953)
> 
> 很抱歉，无效，我的操作系统没有这个文件夹。（或我无法找到）

在 Win7 上这个目录应该为 ```C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys```

**Comment by AigioL** [comment]
2.8.1 应该不会生成新的证书，如果有 2.7.x 的证书文件或者更早版本生成的话，你可以用 2.7.x 生成的证书复制过去试一试

**Comment by SNWCreations** [comment]
> 2.8.1 应该不会生成新的证书，如果有 2.7.x 的证书文件或者更早版本生成的话，你可以用 2.7.x 生成的证书复制过去试一试

事实是确实生成了新证书，并且我已安装，旧证书已经丢失。

**Comment by AigioL** [comment]
> > 2.8.1 应该不会生成新的证书，如果有 2.7.x 的证书文件或者更早版本生成的话，你可以用 2.7.x 生成的证书复制过去试一试
> 
> 事实是确实生成了新证书，并且我已安装，旧证书已经丢失。

你可以用 2.7 的备份开启加速生成一个证书后复制过去

**Comment by SNWCreations** [comment]
> > > 参考这个试一下 [#1677 (comment)](https://github.com/BeyondDimension/SteamTools/issues/1677#issuecomment-1189257953)
> > 
> > 
> > 很抱歉，无效，我的操作系统没有这个文件夹。（或我无法找到）
> 
> 在 Win7 上这个目录应该为 `C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys`

我找到了，并且向 Everyone 赋予了完整控制权。
但是仍然无效，还是报相同错误。

**Comment by AigioL** [comment]
你有安装 ESU 吗？

**Comment by SNWCreations** [comment]
> 你有安装 ESU 吗？

那是什么？

**Comment by SNWCreations** [comment]
> > > 2.8.1 应该不会生成新的证书，如果有 2.7.x 的证书文件或者更早版本生成的话，你可以用 2.7.x 生成的证书复制过去试一试
> > 
> > 
> > 事实是确实生成了新证书，并且我已安装，旧证书已经丢失。
> 
> 你可以用 2.7 的备份开启加速生成一个证书后复制过去

方法无效。

**Comment by AigioL** [comment]
> > 你有安装 ESU 吗？
> 
> 那是什么？

https://docs.microsoft.com/zh-cn/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq

**Comment by SNWCreations** [comment]
> > > 你有安装 ESU 吗？
> > 
> > 
> > 那是什么？
> 
> https://docs.microsoft.com/zh-cn/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq

无，我的电脑是 Ultimate （旗舰版），可能无法安装这个。

**Comment by AigioL** [comment]
你可以试着安装第三方的 ESU 补丁，例如 UpdatePack7R2，最新版本好像是 22.07.14 这个版本号看上去是年月日命名的
我们测试环境中是安装了这个补丁的，也是 Win7 旗舰版，我记得之前不安装这个程序是打不开的
不确定这个问题是不是因为这个引起的，但是你可以试一下看能不能解决

**Comment by SNWCreations** [comment]
> 你可以试着安装第三方的 ESU 补丁，例如 UpdatePack7R2，最新版本好像是 22.07.14 这个版本号看上去是年月日命名的 我们测试环境中是安装了这个补丁的，也是 Win7 旗舰版，我记得之前不安装这个程序是打不开的 不确定这个问题是不是因为这个引起的，但是你可以试一下看能不能解决

感谢，我会在饭后进行测试。

**Comment by SNWCreations** [comment]
> 你可以试着安装第三方的 ESU 补丁，例如 UpdatePack7R2，最新版本好像是 22.07.14 这个版本号看上去是年月日命名的 我们测试环境中是安装了这个补丁的，也是 Win7 旗舰版，我记得之前不安装这个程序是打不开的 不确定这个问题是不是因为这个引起的，但是你可以试一下看能不能解决

您好，我无法连接原作者的网站下载那个程序，您有没有可用的副本？

**Comment by AigioL** [comment]
> > 你可以试着安装第三方的 ESU 补丁，例如 UpdatePack7R2，最新版本好像是 22.07.14 这个版本号看上去是年月日命名的 我们测试环境中是安装了这个补丁的，也是 Win7 旗舰版，我记得之前不安装这个程序是打不开的 不确定这个问题是不是因为这个引起的，但是你可以试一下看能不能解决
> 
> 您好，我无法连接原作者的网站下载那个程序，您有没有可用的副本？

https://update7.simplix.info/UpdatePack7R2.exe 这个连接打不开么
magnet:?xt=urn:btih:DC71EE6739BD22F164F3053F700D649256A6090C 这个磁力连接下载呢？

**Comment by SNWCreations** [comment]
> 

前者我下载了，是个下载器，速度非常慢（几乎没有动静）
后者我试了，是个torrent文件，但我手头没有torrent下载器（我平常不用），我会稍后测试。

**Comment by SNWCreations** [comment]
我无法下载 :(
总是失败。

**Comment by AigioL** [comment]
> UpdatePack7R2

https://www.123pan.com/s/A6cA-nsHJh

https://pan.baidu.com/s/1RWxXDFyprERrRGZNIpYy2A

**Comment by SNWCreations** [comment]
感谢！下载已经开始。
![image](https://user-images.githubusercontent.com/59989459/180632183-39d58c6a-3695-446a-82c4-08b833ca4cdf.png)

**Comment by SNWCreations** [comment]
如今看来，这个问题难以解决。
我无法正常安装 UpdatePack7R2 ，总是安装中断（错误码 0x800f081f）
并且程序下载并运行了 WinRepair （同样来自 simplix），但是已经运行了2个小时了，现在在 Repair system storage 阶段，我不知道这个程序何时能结束。

我暂时会使用 v2.7 ，期待这个能得到修复。

**Comment by AigioL** [comment]
试下这个包
https://github.com/BeyondDimension/SteamTools/suites/7494569938/artifacts/307864760

**Comment by SNWCreations** [comment]
> 试下这个包 https://github.com/BeyondDimension/SteamTools/suites/7494569938/artifacts/307864760

抱歉，刚刚在修改我工程的错误，现在才处理。

失败，出现了新的问题（我用的 Discord 网站进行测试）。
> 此网站无法提供安全连接
> www.pixiv.net 使用了不受支持的协议。
> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

我无法从日志找到问题，因为没有ERROR级别的。

**Comment by SNWCreations** [comment]
> 试下这个包 https://github.com/BeyondDimension/SteamTools/suites/7494569938/artifacts/307864760

抱歉，刚刚在修改我工程的错误，现在才处理。

失败，出现了新的问题（我用的 Discord 网站进行测试）。
> 此网站无法提供安全连接
> www.discord.com 使用了不受支持的协议。
> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

我无法从日志找到问题，因为没有ERROR级别的。

**Comment by AigioL** [comment]
这个包应该修复从根证书创建用于网站域名的证书
ERR_SSL_VERSION_OR_CIPHER_MISMATCH 这个问题似乎现在是在 Win7 上受影响，还在解决中

**Comment by SNWCreations** [comment]
> 这个包应该修复从根证书创建用于网站域名的证书 ERR_SSL_VERSION_OR_CIPHER_MISMATCH 这个问题似乎现在是在 Win7 上受影响，还在解决中

期待你们解决，在此之前我还是会使用 v2.7 。

**Comment by SNWCreations** [comment]
我注意到了 v2.8.2 更新，并且我下载了，v2.8.2 修复了此问题。
此问题可以关闭了。
