### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by buiawpkgew1** [BeyondDimension/SteamTools#1719]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):no

**Comment by AigioL** [comment]
在设置-通用设置-存储空间上打开Logs文件夹，将完整的log内容贴上来

**Comment by buiawpkgew1** [comment]
[nlog-all-2022-07-24.log](https://github.com/BeyondDimension/SteamTools/files/9175013/nlog-all-2022-07-24.log)

**Comment by AigioL** [comment]
> [nlog-all-2022-07-24.log](https://github.com/BeyondDimension/SteamTools/files/9175013/nlog-all-2022-07-24.log)

```
2022-07-24 10:36:38.7019|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/Accelerate/All/4 | System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Application.Services.CloudService.ApiConnection.SendCoreAsync[TRequestModel,TResponseModel](Boolean isAnonymous, Boolean isApi, CancellationToken cancellationToken, HttpMethod method, String requestUri, TRequestModel requestModel, Boolean responseContentMaybeNull, Boolean isSecurity, Boolean isShowResponseErrorMessage, String errorAppendText)
```

看上去还是与 https://github.com/BeyondDimension/SteamTools/issues/709 https://github.com/BeyondDimension/SteamTools/issues/1468  https://gitee.com/rmbgame/SteamTools/issues/I4N5YF

相同 问题视乎是出在了客户端的 Http2 请求上，也许降级到 1.1 就能正常了，之前版本没有这个问题吗？例如 2.7.x/2.6.x？

**Comment by buiawpkgew1** [comment]
> > [nlog-all-2022-07-24.log](https://github.com/BeyondDimension/SteamTools/files/9175013/nlog-all-2022-07-24.log)
> 
> ```
> 2022-07-24 10:36:38.7019|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/Accelerate/All/4 | System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
>  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
>  ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
>    --- End of inner exception stack trace ---
>    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at System.Application.Services.CloudService.ApiConnection.SendCoreAsync[TRequestModel,TResponseModel](Boolean isAnonymous, Boolean isApi, CancellationToken cancellationToken, HttpMethod method, String requestUri, TRequestModel requestModel, Boolean responseContentMaybeNull, Boolean isSecurity, Boolean isShowResponseErrorMessage, String errorAppendText)
> ```
> 
> 看上去还是与 #709 #1468 [gitee.com/rmbgame/SteamTools/issues/I4N5YF](https://gitee.com/rmbgame/SteamTools/issues/I4N5YF)
> 
> 相同 问题视乎是出在了客户端的 Http2 请求上，也许降级到 1.1 就能正常了，之前版本没有这个问题吗？例如 2.7.x/2.6.x？

2.7.x/2.6.x 都有

**Comment by AigioL** [comment]
[ConsoleApp1.zip](https://github.com/BeyondDimension/SteamTools/files/9175080/ConsoleApp1.zip)

运行这个程序看看控制台输出

**Comment by buiawpkgew1** [comment]
> 

Http2 Error:
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage , CancellationToken )
   at Program.<Main>$(String[] args)
Http11 Error:
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage , CancellationToken )
   at Program.<Main>$(String[] args)

**Comment by AigioL** [comment]
> > 
> 
> Http2 Error: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持 --- End of inner exception stack trace --- at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean ) at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken ) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken ) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage ) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken ) at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken ) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage , CancellationToken ) at Program.<Main>$(String[] args) Http11 Error: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持 --- End of inner exception stack trace --- at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean ) at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken ) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken ) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage ) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken ) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken ) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken ) at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage , CancellationToken ) at Program.
> 
> $(String[] args)
> ![image](https://user-images.githubusercontent.com/71136405/180631448-32e8f0db-481d-42b5-ab9d-8b8d54ad0e5f.png)

看来是 SSL 的问题，https://api.steampp.net 这个地址你能在浏览器中打开吗？

**Comment by buiawpkgew1** [comment]
> 看来是 SSL 的问题，[api.steampp.net](https://api.steampp.net) 这个地址你能在浏览器中打开吗？

![image](https://user-images.githubusercontent.com/71136405/180631482-d9f280b4-5b13-4bcb-a8fc-666d5c409b24.png)

**Comment by AigioL** [comment]
[ConsoleApp2.zip](https://github.com/BeyondDimension/SteamTools/files/9175134/ConsoleApp2.zip)
这个程序呢

**Comment by buiawpkgew1** [comment]
> [ConsoleApp2.zip](https://github.com/BeyondDimension/SteamTools/files/9175134/ConsoleApp2.zip) 这个程序呢 `<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>`
> 
> ```
> using System;
> using System.Collections.Generic;
> using System.Linq;
> using System.Net;
> using System.Net.Http;
> using System.Text;
> using System.Threading.Tasks;
> 
> namespace ConsoleApp2
> {
>     internal class Program
>     {
>         static async Task Main(string[] args)
>         {
>             ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
> 
>             const string url = "https://api.steampp.net/[](https://api.steampp.net/)";
> 
>             try
>             {
>                 using (var client = new HttpClient())
>                 {
>                     var htmlStr = await client.GetStringAsync(url);
>                     Console.WriteLine("Http OK");
>                     Console.WriteLine($"len: {htmlStr.Length}");
>                 }
>             }
>             catch (Exception e)
>             {
>                 Console.WriteLine("Http Error: ");
>                 Console.WriteLine(e);
>             }
> 
>             Console.ReadLine();
>         }
>     }
> }
> ```

Http OK
len: 48672

**Comment by AigioL** [comment]
[ConsoleApp1(2).zip](https://github.com/BeyondDimension/SteamTools/files/9175145/ConsoleApp1.2.zip)

试试这个，WinHttpHandler 或许兼容性好一些

```
using System.Net;

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Tls13;
Console.WriteLine($"SecurityProtocol: {ServicePointManager.SecurityProtocol}");

var urls = new[] { "https://cn.bing.com/", "https://api.steampp.net/" };

foreach (var url in urls)
{
    try
    {
        using var client = new HttpClient(new WinHttpHandler());
        client.DefaultRequestVersion = HttpVersion.Version20;
        client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
        var htmlStr = await client.GetStringAsync(url);
        Console.WriteLine("Http2 OK");
        Console.WriteLine($"len: {htmlStr.Length}");
    }
    catch (Exception e)
    {
        Console.WriteLine("Http2 Error: ");
        Console.WriteLine(e);
    }

    try
    {
        using var client = new HttpClient(new WinHttpHandler());
        client.DefaultRequestVersion = HttpVersion.Version11;
        client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
        var htmlStr = await client.GetStringAsync(url);
        Console.WriteLine("Http11 OK");
        Console.WriteLine($"len: {htmlStr.Length}");
    }
    catch (Exception e)
    {
        Console.WriteLine("Http11 Error: ");
        Console.WriteLine(e);
    }
}

Console.ReadLine();
```

**Comment by buiawpkgew1** [comment]
> 

SecurityProtocol: Tls11, Tls12, Tls13
Http2 OK
len: 79590
Http11 OK
len: 79441
Http2 OK
len: 48672
Http11 OK
len: 48672

**Comment by AigioL** [comment]
下个版本会在设置中加一个 使用 WinHttpHandler 的开关，默认会是关闭，之后你更新开启这个开关重启程序应该就能解决了

**Comment by buiawpkgew1** [comment]
> 下个版本会在设置中加一个 使用 [WinHttpHandler](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.http.winhttphandler?view=dotnet-plat-ext-6.0) 的开关，默认会是关闭，之后你更新开启这个开关重启程序应该就能解决了

OK

**Comment by AigioL** [comment]
https://github.com/BeyondDimension/SteamTools/suites/7493675424/artifacts/307801195
用这个版本试一下

**Comment by buiawpkgew1** [comment]
> [BeyondDimension/SteamTools/suites/7493675424/artifacts/307801195](https://github.com/BeyondDimension/SteamTools/suites/7493675424/artifacts/307801195) 用这个版本试一下

![image](https://user-images.githubusercontent.com/71136405/180637835-4cb9d069-16a4-47b1-8c62-0148bb4d61f5.png)

**Comment by buiawpkgew1** [comment]
![X7O`` V1PE`5GNX%PST6 %5](https://user-images.githubusercontent.com/71136405/180637927-27aac9e9-b781-43e6-98ba-e728bb1dc97c.png)
>{"error":"Request","message":"Because https://github.com/BeyondDimension/SteamTools/issues/1719 actually points to WattToolkit itself, WattToolkit has interrupted this forwarding"}

**Comment by rmbadmin** [comment]
这个提示是表示该地址被重复代理了两次，尝试更换其它加速模式测试
