### ISSUE TITLE
 🐛[BUG]  v2.8.1 加速网站出现 XXX 使用了不支援的通訊協定。

### ISSUE THREAD

**Issue by guihongwong** [BeyondDimension/SteamTools#1720]
### 🐛 描述(Description)

在浏览器打开 加速网站时 无法打开 网站 显示 xxx 使用了不支援的通訊協定。

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
有日志吗？

**Comment by guihongwong** [comment]
> 有日志吗？
[nlog-all-2022-07-24.log](https://github.com/BeyondDimension/SteamTools/files/9175052/nlog-all-2022-07-24.log)

[Uploading nlog-all-2022-07-23.log…]()

**Comment by AigioL** [comment]
日志中错误不少，还包含上一个版本的错误

这个错误的出现次数较多，启用了 SAM 的 挂时长吗？
```
2022-07-24 08:30:41.0487|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```

末尾处的错误应该是导致此问题的原因 @rmbadmin 
```
2022-07-24 09:23:46.1575|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://api.steampowered.com/ISteamDirectory/GetCMListForConnect/v0001/ responded 502 in 30118.9773 ms
System.Net.Http.HttpRequestException: Query 24063 => steamstore.rmbgame.net IN AAAA on 223.5.5.5:53 timed out or is a transient error. (api.steampowered.com:443)
 ---> DnsClient.DnsResponseException: Query 24063 => steamstore.rmbgame.net IN AAAA on 223.5.5.5:53 timed out or is a transient error.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.Tasks.TaskExtensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   at DnsClient.LookupClient.QueryInternalAsync(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.DnsAnalysisServiceImpl.AnalysisDomainIpAsync(String hostNameOrAddress, IPAddress[] dnsServers, Boolean isIPv6, CancellationToken cancellationToken)+MoveNext()
   at System.Application.Services.Implementation.DnsAnalysisServiceImpl.AnalysisDomainIpAsync(String hostNameOrAddress, IPAddress[] dnsServers, Boolean isIPv6, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+MoveNext()
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+MoveNext()
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 
2022-07-24 10:40:25.9706|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://google2.cdn.steampipe.steamcontent.com/depot/227301/chunk/5f4d3f4ad555279134160c436e832c2e6dd5f647 responded 502 in 6080.9325 ms
System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, CancellationToken cancellation) | 
```

**Comment by rmbadmin** [comment]
可以尝试修改下代理dns设置如果无效的话得等下个版本发布，暂时先回滚使用吧

**Comment by AigioL** [comment]
看上去你的网络连不上阿里云公共DNS，超时导致的错误
https://alidns.com/

**Comment by guihongwong** [comment]
> 

修改成系统默认 正常了
建议不用阿里dns   家里设备基本都用 dns时不时抽风

**Comment by guihongwong** [comment]
asf 双账户卡死

**Comment by guihongwong** [comment]
> 有日志吗？

asf 双账户卡死
[log.txt](https://github.com/BeyondDimension/SteamTools/files/9175088/log.txt)

**Comment by AigioL** [comment]
> asf 双账户卡死

是这个问题么 https://github.com/BeyondDimension/SteamTools/issues/1407

@rmbadmin 大概率就是这个输入框因为多个账户并发了？

**Comment by rmbadmin** [comment]
> > asf 双账户卡死
> 
> 是这个问题么 #1407
> 
> @rmbadmin 大概率就是这个输入框因为多个账户并发了？

我一直都是俩个账号并没有这样的问题，这里是按顺序依次登录账号的，又不是并行

**Comment by guihongwong** [comment]
> > asf 双账户卡死
> 
> 是这个问题么 #1407
> 
> @rmbadmin 大概率就是这个输入框因为多个账户并发了？

只有 gh   有双重手机验证 ks没有

**Comment by guihongwong** [comment]
> 看上去你的网络连不上阿里云公共DNS，超时导致的错误 https://alidns.com/

感觉是启用脚本的问题导致的   关闭了就没有弹通讯协定处理

**Comment by GuihongWang** [comment]
> 可以尝试修改下代理dns设置如果无效的话得等下个版本发布，暂时先回滚使用吧

大号       不知道下个版本能不能使用doh 的dns 来代替普通dns      &启用脚本之后出现这个bug的概率大大增加

**Comment by rmbadmin** [comment]
> > 可以尝试修改下代理dns设置如果无效的话得等下个版本发布，暂时先回滚使用吧
> 
> 大号 不知道下个版本能不能使用doh 的dns 来代替普通dns &启用脚本之后出现这个bug的概率大大增加

主要是目前使用的dnsclient未支持doh，自己去实现一个嫌麻烦，之后有空整一个

**Comment by GuihongWang** [comment]
> > > 可以尝试修改下代理dns设置如果无效的话得等下个版本发布，暂时先回滚使用吧
> > 
> > 大号 不知道下个版本能不能使用doh 的dns 来代替普通dns &启用脚本之后出现这个bug的概率大大增加
> 
> 主要是目前使用的dnsclient未支持doh，自己去实现一个嫌麻烦，之后有空整一个

希望可以早一点弄好
wondows 7 任然是一个好的Base On NT的工作站系统

**Comment by guihongwong** [comment]
新问题 
![image](https://user-images.githubusercontent.com/109639571/181492543-f2db3ebc-f94a-457a-a41d-6e2e581fd0c5.png)
被dxtory识别成其他软件 左上角出现帧率

**Comment by guihongwong** [comment]
新版本 2.8.2 
這個網頁無法正常運作
github.com 目前無法處理這項要求。
HTTP ERROR 502
[nlog-all-2022-07-28.log](https://github.com/BeyondDimension/SteamTools/files/9208861/nlog-all-2022-07-28.log)
