### ISSUE TITLE
🐛[BUG] 新版本加速完全失效

### ISSUE THREAD

**Issue by MisakMikot** [BeyondDimension/SteamTools#1732]
### 🐛 描述(Description)

不论是DNS模式，HOSTS模式，系统代理模式还是PAC模式都无法进入社区。刚开机也没有其他代理运行。流量统计也始终为0
### 📷 复现步骤(Steps to Reproduce)

1. 打开steam
2. 打开steam++
3. 开启加速

### 📄 [异常/日志]信息([Exception/Log] Information)
2022-07-25 08:47:19.2069|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): Windows 10(11).22000.795
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/87216484/180674063-c68454e3-d14f-4bb3-8296-51e71e5afab4.png)
![image](https://user-images.githubusercontent.com/87216484/180674091-f14d1c6e-484b-427c-a81c-cd2558b864d6.png)

**Comment by Asnirelia** [comment]
我也有这个问题，回退到2.72使用正常，更新到2.81就加速失败

**Comment by rmbadmin** [comment]
提供的日志并不是加速相关的，没法确定问题原因

**Comment by 1325927765** [comment]
> 提供的日志并不是加速相关的，没法确定问题原因
2022-07-25 11:46:23.6144|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://www.pixiv.net/ responded 502 in 15062.5747 ms
System.Net.Http.HttpRequestException: Query 13380 => pixiv.rmbgame.net IN A on 192.168.0.1:53 timed out or is a transient error. (www.pixiv.net:443)
 ---> DnsClient.DnsResponseException: Query 13380 => pixiv.rmbgame.net IN A on 192.168.0.1:53 timed out or is a transient error.
类似问题

**Comment by rmbadmin** [comment]
> > 提供的日志并不是加速相关的，没法确定问题原因
> > 2022-07-25 11:46:23.6144|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://www.pixiv.net/ responded 502 in 15062.5747 ms
> > System.Net.Http.HttpRequestException: Query 13380 => pixiv.rmbgame.net IN A on 192.168.0.1:53 timed out or is a transient error. ([www.pixiv.net:443](http://www.pixiv.net:443))
> > ---> DnsClient.DnsResponseException: Query 13380 => pixiv.rmbgame.net IN A on 192.168.0.1:53 timed out or is a transient error.
> > 类似问题

下载最新的构建版本，或者自己修改下电脑dns可暂时解决，之后更新会修复

**Comment by MisakMikot** [comment]
> > > 提供的日志并不是加速相关的，没法确定问题原因
> > > 2022-07-25 11:46:23.6144|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://www.pixiv.net/ responded 502 in 15062.5747 ms
> > > System.Net.Http.HttpRequestException: Query 13380 => pixiv.rmbgame.net IN A on 192.168.0.1:53 timed out or is a transient error. ([www.pixiv.net:443](http://www.pixiv.net:443))
> > > ---> DnsClient.DnsResponseException: Query 13380 => pixiv.rmbgame.net IN A on 192.168.0.1:53 timed out or is a transient error.
> > > 类似问题
> 
> 下载最新的构建版本，或者自己修改下电脑dns可暂时解决，之后更新会修复


下了2.82版本还是不行啊大佬，用的hosts模式，下面是日志：
2022-07-28 22:37:10.5838|Error|HttpService|SendAsync Fail, requestUri: https://steam-chat.com/miniprofile/1101817760/json | System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Application.Services.Implementation.HttpServiceImpl.SendAsync[T](Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, CancellationToken cancellationToken, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, String clientName)
2022-07-28 22:37:11.7057|Error|HttpService|SendAsync Fail, requestUri: https://steam-chat.com/miniprofile/1101817760/json | System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Application.Services.Implementation.HttpServiceImpl.SendAsync[T](Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, CancellationToken cancellationToken, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, String clientName)
2022-07-28 22:37:11.9096|Error|HttpService|SendAsync Fail, requestUri: https://steam-chat.com/miniprofile/1101817760/json | System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Application.Services.Implementation.HttpServiceImpl.SendAsync[T](Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, CancellationToken cancellationToken, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, String clientName)
2022-07-28 22:37:15.6385|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:18.6578|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:21.7083|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:24.7394|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:27.7629|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:30.7891|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:33.8224|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:36.8448|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-28 22:37:42.0380|Error|HttpService|SendAsync Fail, requestUri: https://steam-chat.com/miniprofile/1101817760/json | System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Application.Services.Implementation.HttpServiceImpl.SendAsync[T](Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, CancellationToken cancellationToken, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, String clientName)

**Comment by rmbadmin** [comment]
建议直接提交日志文件，你提交的日志中并没有看到加速相关的内容

**Comment by MisakMikot** [comment]
> 建议直接提交日志文件，你提交的日志中并没有看到加速相关的内容

这个就是全部日志了，不过现在又突然好了，流量也正常显示了，社区也能进
