### ISSUE TITLE
🐛[BUG] DNS驱动模式不可用

### ISSUE THREAD

**Issue by Ra2-IFV** [BeyondDimension/SteamTools#1737]
### 🐛 描述(Description)
如果选择加速模式为DNS驱动，则加速功能不可用，Steam好友网络无法使用，商店页面打不开，Github无加速效果，且流量统计中无流量
若选择为Hosts模式，则可正常加速，流量统计中一切正常

### 📷 复现步骤(Steps to Reproduce)
退出Steam，退出Steam++，确定hosts文件只有127.0.0.1，然后打开Steam++，选择模式为DNS并开始加速，然后打开Steam

### 📄 日志信息(Log Information)
[nlog-all-2022-07-25.log](https://github.com/BeyondDimension/SteamTools/files/9178263/nlog-all-2022-07-25.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.1 非FDE
- 系统版本号(OS Version): Windows10 2004 (内部19041.1415)
- 是否为应用商店版本(Whether it is a Store version): False
### 🖼 截图(Screenshots)
![图片](https://user-images.githubusercontent.com/96299096/180705254-8f3391bc-ffac-4e3a-8477-a696f57a1130.png)

**Comment by Mossimos** [comment]
DNS驱动 加速模式可能有 电脑浏览器已经有DNS缓存 导致未走程序DNS解析 加速无效建议重启电脑清理DNS缓存后再试试

**Comment by rmbadmin** [comment]
日志文件404无法下载，

其实能用什么模式就用什么模式就行，做这么多模式就是给大家根据自身情况选择使用的

**Comment by Ra2-IFV** [comment]
[nlog-all-2022-07-25.log](https://github.com/BeyondDimension/SteamTools/files/9178306/nlog-all-2022-07-25.log)
log文件是在开启DNS模式时上传的...忘了（捂脸）
> DNS驱动 加速模式可能有 电脑浏览器已经有DNS缓存 导致未走程序DNS解析 加速无效建议重启电脑清理DNS缓存后再试试

那是不是应该使用ipconfig /flushdns ?

**Comment by AigioL** [comment]
```
2022-07-25 02:14:30.9821|Error|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HMJDE0AF0COG", Request id "0HMJDE0AF0COG:00000023": An unhandled exception was thrown by the application. |ConnectionId=0HMJDE0AF0COG, TraceIdentifier=0HMJDE0AF0COG:00000023, EventId=13, EventName=ApplicationError System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_ContentType(StringValues value)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_ContentType(String value)
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync[TValue](HttpResponse response, TValue value, JsonSerializerOptions options, String contentType, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.HandleErrorAsync(HttpContext context, ForwarderError error)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyPacMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

```
2022-07-25 13:03:18.2995|Error|System.Application.Services.Implementation.PacketIntercept.DnsInterceptHostedService|InterceptAsync catch. | System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。
   at System.Application.Services.Implementation.PacketIntercept.DnsInterceptor.InterceptAsync(CancellationToken cancellationToken)
   at System.Application.Services.Implementation.PacketIntercept.InterceptHostedService.ExecuteAsync(CancellationToken stoppingToken)
```

```
2022-07-25 13:24:27.6944|Error|Shutdown|compositeDisposable.Dispose() | System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Application.Services.Implementation.YarpReverseProxyServiceImpl.StopProxy()
   at System.Application.Services.ProxyService.Exit()
   at System.TaskExtensions.RunSync(Func`1 func)
   at System.Reactive.Disposables.CompositeDisposable.Dispose() in D:\a\SteamTools\SteamTools\references\reactive\Rx.NET\Source\src\System.Reactive\Disposables\CompositeDisposable.cs:line 244
   at System.Application.UI.App.ApplicationLifetime_Exit(Object sender, ControlledApplicationLifetimeExitEventArgs e)
```

**Comment by AigioL** [comment]
WinDivert.dll / WinDivert64.sys 是不是被杀毒软件删了？

**Comment by Ra2-IFV** [comment]
> WinDivert.dll / WinDivert64.sys 是不是被杀毒软件删了？

拿Everything搜了一下
![图片](https://user-images.githubusercontent.com/96299096/180707016-76b475e7-65b5-412d-8088-1fb4d61d26f6.png)
WinDivert64.sys没找到

**Comment by Ra2-IFV** [comment]
而且我下的是64位版本的，嗯......（托腮）
那可能就是问题所在了...

**Comment by AigioL** [comment]
这个文件应该位于程序目录上的，你的杀毒软件的管理日志里或许有这个纪录
这应该是引发 ```System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。``` 的原因

**Comment by Ra2-IFV** [comment]
我去下了一份压缩包，拷贝了WinDivert64.sys到程序目录，已经可以使用了
> 这个文件应该位于程序目录上的，你的杀毒软件的管理日志里或许有这个纪录 这应该是引发 `System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。` 的原因

我去火绒的记录里看了，没有关于这个文件的日志，所以可能是安装时就缺失了
btw我是用的是exe安装，等下重新安装看看

**Comment by Ra2-IFV** [comment]
重新安装了一下，WinDivert64.sys也出现了，所以可能是安装时出了些问题
感谢各位大佬的鼎力相助！这就速速去捐助一下~
