### ISSUE TITLE
🐛[BUG] DNS模式无法使用

### ISSUE THREAD

**Issue by JJN114514** [BeyondDimension/SteamTools#1758]
### 🐛 描述(Description)
DNS模式加速好像用了旧的协议（？不清楚用的什么），导致无法加载网站

### 📷 复现步骤(Steps to Reproduce)

1. 使用DNS模式加速
2. 打开加速的网站
3. 

### 📄 日志信息(Log Information)
2022-07-26 11:20:08.6636|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://github.com/BeyondDimension/SteamTools/tree/develop/.github responded 502 in 7142.4805 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (Authentication failed, see inner exception.) (Authentication failed, see inner exception.) (Authentication failed, see inner exception.) (HTTP connection to 20.205.243.166 timed out.) (由于目标计算机积极拒绝，无法连接。) (由于目标计算机积极拒绝，无法连接。) (github.com:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (Authentication failed, see inner exception.) (Authentication failed, see inner exception.) (Authentication failed, see inner exception.) (HTTP connection to 20.205.243.166 timed out.) (由于目标计算机积极拒绝，无法连接。) (由于目标计算机积极拒绝，无法连接。)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

 ---> (Inner Exception #2) System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

 ---> (Inner Exception #3) System.TimeoutException: HTTP connection to 20.205.243.166 timed out.<---

 ---> (Inner Exception #4) System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

 ---> (Inner Exception #5) System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): win7
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/93071165/180920567-2776c83f-c8f0-4f89-addc-12b349afca63.png)

![image](https://user-images.githubusercontent.com/93071165/180921008-9189817c-353f-4790-b11e-179638761476.png)
![image](https://user-images.githubusercontent.com/93071165/180921032-23db2661-bbe8-4cdb-aa4f-372ae3eadc33.png)

**Comment by rmbadmin** [comment]
https://github.com/BeyondDimension/SteamTools/suites/7519729500/artifacts/309596647
测试下这个版本看看问题是否依旧复现

**Comment by JJN114514** [comment]
> [https://github.com/BeyondDimension/SteamTools/suites/7519](https://github.com/BeyondDimension/SteamTools/suites/7519729500/artifacts/309596647) 看看729500/artifacts/309596647测试下这个版本问题是否依然复现


用chrome打开其他网站好像没问题了，就是pixiv不行（好像只是pixiv连不上），但是换edge打开所有加速的网站都不加载
![T$3 $45S NZLWFX@EAGFE1Q](https://user-images.githubusercontent.com/93071165/181023261-c5db241d-5e7e-4e89-b08d-0e2f56544b64.png)

**Comment by JJN114514** [comment]
补充一下，pixiv全部模式下均无法打开

**Comment by rmbadmin** [comment]
已经定位问题并修复，等待下个版本更新
