### ISSUE TITLE
🐛[BUG] 一个小bug，steam主页头像消失

### ISSUE THREAD

**Issue by SeYingSi** [BeyondDimension/SteamTools#1759]
### 🐛 描述(Description)
当开启网路加速启动steam时，steam主页头像消失，使用dns模式和hosts模式皆会发生，好友列表及个人资料页头像正常。关闭加速重启steam头像便会正常显示。

### 📷 复现步骤(Steps to Reproduce)

1. 开启网络加速
2. 启动steam

### 📄 日志信息(Log Information)
```
2022-07-26 09:41:14.9323|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-26 09:41:18.0052|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-26 10:25:07.9800|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-26 10:40:58.4016|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-26 10:41:41.5450|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-26 10:43:29.9692|Error|JumpListS|AddJumpItemsAsync catch. | System.Runtime.InteropServices.COMException (0x80070497): 无法删除要被替换的文件。 (0x80070497)
   at System.Application.Services.Implementation.Windows10JumpListServiceImpl.AddJumpItemsAsync(IEnumerable`1 items)
2022-07-26 11:50:10.8060|Error|JumpListS|AddJumpItemsAsync catch. | System.Runtime.InteropServices.COMException (0x80070497): 无法删除要被替换的文件。 (0x80070497)
   at System.Application.Services.Implementation.Windows10JumpListServiceImpl.AddJumpItemsAsync(IEnumerable`1 items)

```

-->

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):x64 2.8.1 Windows
- 系统版本号(OS Version): Windows 11.22000.708
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/110009167/180923408-be359105-d7bc-43b4-8713-473b072eebfa.png)
![image](https://user-images.githubusercontent.com/110009167/180923946-e93df321-1e10-486f-baa4-fc9ef34e05d5.png)

**Comment by H1b1sCuS** [comment]
我是右上角头像会消失

**Comment by SeYingSi** [comment]
> 我是右上角头像会消失

一样，我这个是steam皮肤罢了，就是主页上的头像，把加速里的steam图片去掉就能加载出来了

**Comment by Nepchico** [comment]
这个问题我之前也反馈过了，不过我的日志无法帮助复现。。。☹️

**Comment by Nepchico** [comment]
> 这个问题我之前也反馈过了，不过我的日志无法帮助复现。。。☹️

不过我的主网是移动的，关闭了也是无法加载的
