### ISSUE TITLE
微软商店最新版watt toolkit无法正常启动🐛[BUG] 

### ISSUE THREAD

**Issue by TBFOTA** [BeyondDimension/SteamTools#1773]
### 🐛 描述(Description)

运行后程序不运行
后台进程显示“已挂起”，并于几秒后自动结束

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 📄 日志信息(Log Information)

```
2022-07-28 08:12:43.5319|Error|ViaFactory|Stopped program because of exception, name: AppDomain, isTerminating: True | System.Exception: DI.Get* fail, serviceType: Microsoft.Extensions.Logging.ILoggerFactory
   at System.DI.Get[T]()
   at System.Log.Error(String tag, String msg, Object[] args)
   at System.Application.Settings.SettingsHost.Load()
   at System.Application.UI.Program.OnCreateAppExecuting(Boolean isTrace)
   at System.Application.UI.Program.Main(String[] args)
2022-07-28 08:12:43.5881|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService
   at System.DI.Get_Nullable[T]()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
2022-07-28 08:12:43.6008|Error|ViaFactory|(App)Close exception when exception occurs | System.ArgumentNullException: Value cannot be null. (Parameter 'app')
   at System.Application.UI.App.get_Instance()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): Windows 10.19044.1826
- 是否为应用商店版本(Whether it is a Store version): Yes

### 🖼 截图(Screenshots)

[Uploading nlog-all-2022-07-28.log…]()

**Comment by yolomc** [comment]
+1
昨天刚更新完是可以启动的，今天开机后无法启动

**Comment by zbdaqwe** [comment]
更新2.8.2之后就直接不能启动了

**Comment by rmbadmin** [comment]
参考 https://github.com/BeyondDimension/SteamTools/issues/1805#issuecomment-1200660137 解决方案
