### ISSUE TITLE
访问网址时地址栏出错🐛[BUG] 

### ISSUE THREAD

**Issue by GodGun968** [BeyondDimension/SteamTools#1775]
### 🐛 描述(Description)

当访问google.com时,地址栏会复制此网址
![image](https://user-images.githubusercontent.com/67826085/181413721-bff661d2-c2e1-4f6c-b81d-38863c6585d6.png)
```
http://google.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/httpsgoogle.com/
```
### 📷 复现步骤(Steps to Reproduce)

1. 启用加速,我是用的是DNS拦截
2.  似乎 是启用加速但是,依然无法访问的网站会这样
3. 

### 📄 日志信息(Log Information)

```
2022-07-28 11:14:26.5330|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HMJG8S6JMN4T. |ConnectionId=0HMJG8S6JMN4T Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.DuplexPipeStreamExtensions.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Application.Services.Implementation.FlowAnalyze.FlowAnalyzeStream.ReadAsync(Memory`1 destination, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|36_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyMiddleware.InvokeAsync(ConnectionDelegate next, ConnectionContext context)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
2022-07-28 11:25:10.7018|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://storage.live.com/users/0x466a9d1c5d31eb71/myprofile/expressionprofile/profilephoto:UserTileStatic/p responded 502 in 1.3214 ms
System.ApplicationException: Because https://storage.live.com/users/0x466a9d1c5d31eb71/myprofile/expressionprofile/profilephoto:UserTileStatic/p?ck=1&ex=720&sid=36F0AE11668A681D22E4BFFE6758694B&fofoff=1 actually points to WattToolkit itself, WattToolkit has interrupted this forwarding
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 
2022-07-28 11:26:37.2372|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://storage.live.com/users/0x466a9d1c5d31eb71/myprofile/expressionprofile/profilephoto:UserTileStatic/p responded 502 in 0.6814 ms
System.ApplicationException: Because https://storage.live.com/users/0x466a9d1c5d31eb71/myprofile/expressionprofile/profilephoto:UserTileStatic/p?ck=1&ex=720&sid=36F0AE11668A681D22E4BFFE6758694B&fofoff=1 actually points to WattToolkit itself, WattToolkit has interrupted this forwarding
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 

```
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): win11
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by GodGun968** [comment]
已搜索到相关问题

**Comment by GodGun968** [comment]
#1772

**Comment by GodGun968** [comment]
问题类似,但似乎不完全一样,等下个版本发布时看问题是否解决

**Comment by rmbadmin** [comment]
是一样的问题，已经解决了的
