### ISSUE TITLE
🐛[BUG] 更新2.82后加速仍旧失败

### ISSUE THREAD

**Issue by Asnirelia** [BeyondDimension/SteamTools#1777]
### 🐛 描述(Description)

同之前2.81版本遇到的问题一样，无法加载社区相关信息，甚至加速后steam商店都白屏

### 📷 复现步骤(Steps to Reproduce)

1. 打开steam++
2. 网页打开steam
3. 该网页无法正常运作

### 📄 日志信息(Log Information)
2022-07-28 21:44:28.6383|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://store.steampowered.com/ responded 502 in 10008.3774 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (HTTP connection to 23.42.182.65 timed out.) (store.steampowered.com:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (HTTP connection to 23.42.182.65 timed out.)
 ---> System.TimeoutException: HTTP connection to 23.42.182.65 timed out.
   --- End of inner exception stack trace ---
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):V2.82
- 系统版本号(OS Version): WIN10
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/74890253/181520892-c7c5a1c8-98ea-4890-a7b0-62ec099b1177.png)
![image](https://user-images.githubusercontent.com/74890253/181521599-95441e05-7ade-4d8c-83b0-52c41e52b3c8.png)

**Comment by MisakMikot** [comment]
我也是，而且我的直接连上下行流量都没有

**Comment by Asnirelia** [comment]
回退到2.72正常使用。能进社区
![image](https://user-images.githubusercontent.com/74890253/181581425-eb837d26-bca0-41a4-a269-593bd5d60feb.png)

**Comment by rmbadmin** [comment]
代理设置中修改dns看看，@MisakMikot 加速流量都没有则表示加速没有启动成功，提供下错误日志

**Comment by MisakMikot** [comment]
> 代理设置中修改dns看看，@MisakMikot 加速流量都没有则表示加速没有启动成功，提供下错误日志

现在又好了，不知道啥情况

**Comment by Asnirelia** [comment]
修改DNS还是不行

**Comment by rmbadmin** [comment]
> 修改DNS还是不行

能不能提交日志文件，根据你截选的日志这一段没有办法看出问题

**Comment by Asnirelia** [comment]
[nlog-all-2022-07-28.log](https://github.com/BeyondDimension/SteamTools/files/9220261/nlog-all-2022-07-28.log)
