### ISSUE TITLE
🐛[BUG] mod.io无法正常访问

### ISSUE THREAD

**Issue by ChrisCatCP** [BeyondDimension/SteamTools#1797]
### 📷 复现步骤(Steps to Reproduce)

1. 勾选mod.io
2. 使用DNS驱动模式加速

### 📄 日志信息(Log Information)

```
2022-07-31 13:04:25.5896|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://api.mod.io/v1/games/2475/mods/1034237/dependencies responded 502 in 0.5143 ms
System.ApplicationException: Because https://api.mod.io/v1/games/2475/mods/1034237/dependencies?api_key=b4aab104219c1f6d752beb37e483b17b actually points to WattToolkit itself, WattToolkit has interrupted this forwarding
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 
```

-->

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2 for windows
- 系统版本号(OS Version): win11 21H2 (22000.795)
- 是否为应用商店版本(Whether it is a Store version): Y

**Comment by chriscp-cat** [comment]
这是网页返回的  
```
{"error":"Request","message":"Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (HTTP connection to 162.125.32.12 timed out.) (drg.mod.io:443)"}
```

**Comment by ChrisCatCP** [comment]
突然又可以了  可能反代到的那个服务器抽风了吧

**Comment by ChrisCatCP** [comment]
还是非常难用  基本没法正常使用  报错也是一直502  hosts模式和dns模式都一样

**Comment by rmbadmin** [comment]
现阶段还没有支持mod.io

**Comment by ChrisCatCP** [comment]
> 现阶段还没有支持mod.io

但是最新版本已经加上了啊  商店的版本  
steam++的hosts里也有
![image](https://user-images.githubusercontent.com/68489543/182012004-c3679559-33bd-4dde-bafd-35fe7ceea83a.png)

**Comment by ChrisCatCP** [comment]
目前的话 对api.mod.io  基本没啥反应  全是502   
```
2022-07-31 13:43:53.0170|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://api.mod.io/v1/me/subscribed responded 502 in 0.6545 ms
System.ApplicationException: Because https://api.mod.io/v1/me/subscribed?_limit=100&_offset=0&game_id=2475&api_key=b4aab104219c1f6d752beb37e483b17b actually points to WattToolkit itself, WattToolkit has interrupted this forwarding
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 
```

**Comment by AigioL** [comment]
mod.io 的代理数据还没弄好，上一次从测试环境同步加速项目的数据到正式环境中，导致开放出来了
现在已在正式环境中禁用该条数据，重新刷新加速项目应该就没了

**Comment by ChrisCatCP** [comment]
> mod.io 的代理数据还没弄好，上一次从测试环境同步加速项目的数据到正式环境中，导致开放出来了 现在已在正式环境中禁用该条数据，重新刷新加速项目应该就没了

好的 明白了
