### ISSUE TITLE
🧐[Question] 一键登录与切换账号问题

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [BeyondDimension/SteamTools#1800]
### 🧐 问题描述(Description)
一键登录与切换账号时无法切换至对应账号

### 🚑 其他信息(Other Information)
Log：
2022-07-31 18:51:08.4168|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-07-31 18:51:11.4321|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version): Windows 10.19044.1826
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
无法切换的具体情况是什么？

**Comment by 0O0o0oOoO00** [comment]
点击后，程序会卡一小会后恢复正常，会打开steam但没有切换账号，且steam会要求重新登录

**Comment by rmbadmin** [comment]
> 点击后，程序会卡一小会后恢复正常，会打开steam但没有切换账号，且steam会要求重新登录

确认要求重新登录之后 账号是否是切换的对应账号，如果是，那么功能没有问题，是你的账号登录状态失效导致

**Comment by 0O0o0oOoO00** [comment]
> 

没有切换，依旧是切换前的账号

**Comment by rmbadmin** [comment]
> > 
> 
> 没有切换，依旧是切换前的账号

尝试覆盖重装一遍steam，在检查下问题是否依旧

**Comment by 0O0o0oOoO00** [comment]
覆盖重装后没问题了
