### ISSUE TITLE
🐛[BUG] windows11 2.8.2版本每次登录都要重新输入一次密码和令牌登入码

### ISSUE THREAD

**Issue by JIJIGUOWANG123** [BeyondDimension/SteamTools#1838]
### 🐛 描述(Description)
就是每次重新登录都要再次输入密码和输入令牌码

### 📷 复现步骤(Steps to Reproduce)
1. 登录退出steam
2. 重新启动程序，再登录steam就需要重新输入密码和令牌
3. 就是这么一个情况

### 📄 日志信息(Log Information)
```
2022-08-07 10:26:37.6685|Error|AddAuthWindowViewModel|LoginSteamImport | WinAuth.WinAuthInvalidEnrollResponseException: Error enrolling new authenticator
 ---> WinAuth.WinAuthInvalidRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   at System.Application.UI.ViewModels.AddAuthWindowViewModel.<>c__DisplayClass62_0.<LoginSteamImport>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-08-07 21:26:22.2831|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-08-07 21:26:25.3722|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-08-07 21:26:28.3808|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-08-07 21:26:31.3881|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version): windows11 22000.832
- 是否为应用商店版本(Whether it is a Store version):否 NO

### 🖼 截图(Screenshots)
没得截图哈

**Comment by rmbadmin** [comment]
https://steampp.net/faq#ChangeAccount

**Comment by JIJIGUOWANG123** [comment]
> https://steampp.net/faq#ChangeAccount

好的

**Comment by JIJIGUOWANG123** [comment]
> https://steampp.net/faq#ChangeAccount

根本解决不了，之前2.6.9就修复过了，现在又重现几个意思

**Comment by rmbadmin** [comment]
这个问题与steam++是无关的，请先确保自己ip没有频繁变动而导致steam不信任当前设备的登录状态
