### ISSUE TITLE
🐛[BUG] 统计图出现问题

### ISSUE THREAD

**Issue by David-Xian66** [BeyondDimension/SteamTools#1845]
### 🐛 描述(Description)
刚刚我将电脑睡眠一会后  重新打开 统计图出现了问题

### 📷 复现步骤(Steps to Reproduce)

1. 开始加速
2. 睡眠一会

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version): MacOs Big Sur 11.6.5  (20G527)
- 是否为应用商店版本(Whether it is a Store version): N

### 🖼 截图(Screenshots)
![截屏2022-08-09 11 49 33](https://user-images.githubusercontent.com/70191815/183561480-06b39e69-bec9-4a20-92e6-3228251ef63d.png)
![截屏2022-08-09 12 02 14](https://user-images.githubusercontent.com/70191815/183561526-a29105b8-4a69-447c-9b36-821df7239a80.png)

**Comment by David-Xian66** [comment]
设置点了之后没有反应 （不会切换页面）

**Comment by David-Xian66** [comment]
因为我点不了设置 所以导致无法提供日志 （如果知道日志路径的发下呗 谢谢）

**Comment by Mossimos** [comment]
/Users/修改成你的用户名/Library/Caches/Steam++

**Comment by David-Xian66** [comment]
好的 感谢 @Mossimos 

不过我不确定这个日志管不管用 但是 2022-08-08 11:48最近的日志只有这个了 这个 11:46 应该是我开始睡眠的时间 应该这会出错了 导致的连环问题

```
2022-08-08 11:46:14.6769|Error|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HMJORAPV1D67", Request id "0HMJORAPV1D67:00000003": An unhandled exception was thrown by the application. |ConnectionId=0HMJORAPV1D67, TraceIdentifier=0HMJORAPV1D67:00000003, EventId=13, EventName=ApplicationError System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_ContentType(StringValues value)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_ContentType(String value)
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync[TValue](HttpResponse response, TValue value, JsonSerializerOptions options, String contentType, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.HandleErrorAsync(HttpContext context, ForwarderError error)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyPacMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpLocalRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Mossimos** [comment]
和这个错误压根没关系。应该是没写日志 ，但是这个问题也不影响使用

**Comment by David-Xian66** [comment]
那就是没写 😂

**Comment by David-Xian66** [comment]
很好 我朋友也出现了这个问题
![272C7979C06623321C6DCC81A01F194D](https://user-images.githubusercontent.com/70191815/201346162-a97f3a08-6168-4bfc-b2b1-e1c1d1f9e0a2.png)

**Comment by David-Xian66** [comment]
怀疑算法问题
