### ISSUE TITLE
🐛[BUG] AUR bin版本功能缺失且异常崩溃

### ISSUE THREAD

**Issue by Mathanet** [BeyondDimension/SteamTools#1847]
### 🐛 描述(Description)
![image](https://user-images.githubusercontent.com/93783109/183668983-4b9f8102-7e63-4142-a5c0-6a0345018615.png)
如图，左侧选项卡中有好几个都不见了，我主要用它来加速github，可是加速选项卡不见了，还有设置界面打不开，
有一次我在选项卡中来回点时程序就异常崩溃了
```bash
➜  ~ watt-toolkit
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Application.UI.ViewModels.AboutPageViewModel.LoadDonateRankListData(Boolean refresh, Boolean nextPage)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at System.Application.UI.Program.StartAvaloniaApp(String[] args, ShutdownMode shutdownMode)
   at System.Application.UI.Program.ProgramHost.StartApplication(String[] args)
   at System.Application.CommandLine.CommandLineHost.<>c__DisplayClass16_0.<Run>g__MainHandler_|2(Action onInitStartuped, Func`1 sendMessage)
   at System.Application.CommandLine.CommandLineHost.<>c__DisplayClass16_0.<Run>g__MainHandler|1()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
➜  ~
```

### 📷 复现步骤(Steps to Reproduce)

Run the following commands
1. sudo pacman -S yay
2. yay -S watt-toolkit-bin
3. watt-toolkit

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.2 beta for linux (x64)
- 系统版本号(OS Version): Arch Linux 2022年7月最后版本
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/93783109/183667805-6f97a191-0782-43cd-8834-9c4904e7ac5d.png)

**Comment by AigioL** [comment]
在 Unix 上设置页面打不开的问题在 https://github.com/BeyondDimension/SteamTools/commit/33c6f0d5f9408a2cdd1ba554e344eeb4da6c6e99 中修复

从日志上看，闪退应该发生在关于页面加载捐助列表，触发了一个 NRE，也在上面的提交中尝试修复了

可以在目前的 action 上下载编译的版本测试
https://github.com/BeyondDimension/SteamTools/actions/runs/2826909792

**Comment by Mathanet** [comment]
用2.8.4或更高的版本就好了
