### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by zyklone4096** [BeyondDimension/SteamTools#1862]
### 🐛 描述(Description)

更新2.8.2之后无法启动

### 📷 复现步骤(Steps to Reproduce)

1. 以常规方式启动程序

### 📄 日志信息(Log Information)

2022-08-10 16:37:21.8247|Error|ViaFactory|Stopped program because of exception, name: AppDomain, isTerminating: True | System.Exception: DI.Get* fail, serviceType: Microsoft.Extensions.Logging.ILoggerFactory
   at System.DI.Get_Nullable[T]()
   at System.Log.get_Factory()
   at System.Log.CreateLogger(String tag)
   at System.Log.Error(String tag, String msg, Object[] args)
   at System.Application.Settings.SettingsHost.Load()
   at System.Application.UI.Program.OnCreateAppExecuting(Boolean isTrace)
   at System.Application.UI.Program.Main(String[] args)
2022-08-10 16:37:21.8951|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService
   at System.DI.Get_Nullable[T]()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
2022-08-10 16:37:21.8951|Error|ViaFactory|(App)Close exception when exception occurs | System.ArgumentNullException: Value cannot be null. (Parameter 'app')
   at System.Application.UI.App.get_Instance()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
2022-08-10 16:38:26.2926|Error|ViaFactory|Stopped program because of exception, name: AppDomain, isTerminating: True | System.Exception: DI.Get* fail, serviceType: Microsoft.Extensions.Logging.ILoggerFactory
   at System.DI.Get_Nullable[T]()
   at System.Log.get_Factory()
   at System.Log.CreateLogger(String tag)
   at System.Log.Error(String tag, String msg, Object[] args)
   at System.Application.Settings.SettingsHost.Load()
   at System.Application.UI.Program.OnCreateAppExecuting(Boolean isTrace)
   at System.Application.UI.Program.Main(String[] args)
2022-08-10 16:38:26.3547|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService
   at System.DI.Get_Nullable[T]()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
2022-08-10 16:38:26.3547|Error|ViaFactory|(App)Close exception when exception occurs | System.ArgumentNullException: Value cannot be null. (Parameter 'app')
   at System.Application.UI.App.get_Instance()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version): Windows11 25158.1000
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by zyklone4096** [comment]
现在甚至无法导出令牌

**Comment by AigioL** [comment]
删除 AppData 目录中的 Config.mpo 文件

## 📁 存储空间
- AppData
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalState```
    - Windows ```\AppData``` or ```%LocalAppData%\Steam++```
    - macOS ```~/Library/Steam++```
    - Linux ```$XDG_DATA_HOME/Steam++``` or ```$HOME/.local/share/Steam++```
    - Android ```/data/data/net.steampp.app/files```
- Cache
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache```
    - Windows ```\Cache``` or ```%Tmp%\Steam++```
    - macOS ```~/Library/Caches/Steam++```
    - Linux ```$XDG_CACHE_HOME/Steam++``` or ```$HOME/.cache/Steam++```
    - Android ```/data/data/net.steampp.app/cache```
- Logs
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache\Logs```
    - Windows ```\Logs``` or ```%Tmp%\Steam++\Logs```
    - macOS ```~/Library/Caches/Steam++/Logs```
    - Linux ```$XDG_CACHE_HOME/Steam++/Logs``` or ```$HOME/.cache/Steam++/Logs```
    - Android ```/data/data/net.steampp.app/cache/Logs```

**Comment by AigioL** [comment]
这个问题是因为 AppData 目录下的 Config.mpo 文件为 0 字节导致读取失败产生的闪退，将在下个版本中修复
目前可以先手动删除这个文件，再启动程序就正常了
还不清楚什么原因导致这个文件变成 0 字节
