### ISSUE TITLE
🐛[BUG] Win11启动闪退

### ISSUE THREAD

**Issue by datou1996** [BeyondDimension/SteamTools#1874]
### 🐛 描述(Description)

运行后闪退，看不见窗口，进程短暂出现显示已挂起后消失。重装2.8.2、2.8.1均无法解决问题。

### 📷 复现步骤(Steps to Reproduce)

启动即出现。

### 📄 日志信息(Log Information)

```
2022-08-11 10:42:51.8750|Error|ViaFactory|Stopped program because of exception, name: AppDomain, isTerminating: True | System.Exception: DI.Get* fail, serviceType: Microsoft.Extensions.Logging.ILoggerFactory
   at System.DI.Get_Nullable[T]()
   at System.Log.get_Factory()
   at System.Log.CreateLogger(String tag)
   at System.Log.Error(String tag, String msg, Object[] args)
   at System.Application.Settings.SettingsHost.Load()
   at System.Application.UI.Program.OnCreateAppExecuting(Boolean isTrace)
   at System.Application.UI.Program.Main(String[] args)
2022-08-11 10:42:52.0225|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService
   at System.DI.Get_Nullable[T]()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
2022-08-11 10:42:52.0225|Error|ViaFactory|(App)Close exception when exception occurs | System.ArgumentNullException: Value cannot be null. (Parameter 'app')
   at System.Application.UI.App.get_Instance()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.8.2（非应用商店版）、v2.8.1（非应用商店版）
- 系统版本号(OS Version): Windows 11 专业版.22621.382
- 是否为应用商店版本(Whether it is a Store version): 否(No)

### 🖼 截图(Screenshots)

N/A

**Comment by AigioL** [comment]
这个问题是因为 AppData 目录下的 Config.mpo 文件为 0 字节导致读取失败产生的闪退，将在下个版本中修复
目前可以先手动删除这个文件，再启动程序就正常了
还不清楚什么原因导致这个文件变成 0 字节

与 https://github.com/BeyondDimension/SteamTools/issues/1862#issuecomment-1210423305 重复
