### ISSUE TITLE
🐛[BUG] 微软商店版的一系列BUG

### ISSUE THREAD

**Issue by littleZ-233** [BeyondDimension/SteamTools#1875]
🐛 描述(Description)
1.“启动时自动运行Steam”功能失效
2.“当Steam客户端启动时弹出通知”功能失效
3.”账号切换“页面内，提示没有在您的电脑上读取到任何Steam帐户数据，但在刷新后却可以直接弹出之前登录过的所有账号
4.在”账号切换“页面内，任选一个账号，并选择一键登录Steam时，无法启动Steam，且自动关闭Watt Toolkit（？），在手动启动Steam时，依旧需要手动输入账号密码及Steam令牌验证码
（PS：以上不清楚是否为我本人设置的问题，但我之前使用微软商店版时根本没有这些问题，不知道是什么时候开始问题越来越多，已经忍了好久了，实在是受不了了。另外我记得原来貌似有一个启动Steam时跳过输入密码的功能，但却找不到了？）

📷 复现步骤(Steps to Reproduce)
每次启动时都是这样，无需刻意复现

📄 日志信息(Log Information)
你的日志内容
2022-08-11 11:21:58.9263|Error|ViaFactory|Stopped program because of exception, name: AppDomain, isTerminating: True | System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'explorer.exe' with working directory 'C:\Windows\System32'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at System.Application.Services.Implementation.WindowsPlatformServiceImpl.StartAsInvokerByExplorer(String fileName, String arguments)
   at System.Application.Services.Implementation.WindowsPlatformServiceImpl.StartAsInvoker(String fileName, String arguments)
   at System.Application.Services.Implementation.SteamServiceImpl.StartSteam(String arguments)
   at System.Application.UI.ViewModels.SteamAccountPageViewModel.ReStartSteamByUser(SteamUser user)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version): Windows 11 家庭中文版 22000.856
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by JIJIGUOWANG123** [comment]
我也是这样，真的无语了，之前也是让我看官方的解决办法，根本没办法解决。

**Comment by JIJIGUOWANG123** [comment]
我记得2.6.9就修复了这种情况，现在又把bug写回来的吧

**Comment by AigioL** [comment]
从日志上看，通过 explorer.exe 启动 steam 的操作没有成功，explorer.exe 在目录 C:\Windows\System32 上找不到
这个文件应该在 C:\Windows 上的，可能与你的系统环境变量有关，删除了默认系统的环境变量导致的

因为程序需要使用管理员权限，而 steam 通常不需要管理员权限启动，所以通过 explorer.exe 中转了启动实现的降权
下个版本中将 explorer.exe 启动时使用完整的目录，应该能解决这个问题
在此之前你可以试着在设置中 Steam 设置 启用 以管理员权限运行 Steam

这个问题看上去影响 1,2,4
第三点不能复现

**Comment by JIJIGUOWANG123** [comment]
我用了很多东西进行切换steam账户，就是steam++ 会出现这种问题，难道加速器还会影响你们软件切换吗？

**Comment by rmbadmin** [comment]
> 我用了很多东西进行切换steam账户，就是steam++ 会出现这种问题，难道加速器还会影响你们软件切换吗？

如果你的登录IP被加速器改变了，那么确实会影响，steam账号切换功能其它软件如何实现的我不知道，
但steam++的实现是完全依靠steam自身存在的功能而实现的。

**Comment by JIJIGUOWANG123** [comment]
不能修复就算了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月11日(星期四) 晚上10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BeyondDimension/SteamTools] 🐛[BUG] 微软商店版的一系列BUG (Issue #1875)





  
我用了很多东西进行切换steam账户，就是steam++ 会出现这种问题，难道加速器还会影响你们软件切换吗？
  
如果你的登录IP被加速器改变了，那么确实会影响，steam账号切换功能其它软件如何实现的我不知道，
 但steam++的实现是完全依靠steam自身存在的功能而实现的。

**Comment by JIJIGUOWANG123** [comment]
> > 我用了很多东西进行切换steam账户，就是steam++ 会出现这种问题，难道加速器还会影响你们软件切换吗？
> 
> 如果你的登录IP被加速器改变了，那么确实会影响，steam账号切换功能其它软件如何实现的我不知道， 但steam++的实现是完全依靠steam自身存在的功能而实现的。

再前几个版本 用加速器都没这种情况怎么说 还是说什么呢？？？？？？？？？？？？？？？？

**Comment by rmbadmin** [comment]
> > > 我用了很多东西进行切换steam账户，就是steam++ 会出现这种问题，难道加速器还会影响你们软件切换吗？
> > 
> > 
> > 如果你的登录IP被加速器改变了，那么确实会影响，steam账号切换功能其它软件如何实现的我不知道， 但steam++的实现是完全依靠steam自身存在的功能而实现的。
> 
> 再前几个版本 用加速器都没这种情况怎么说 还是说什么呢？？？？？？？？？？？？？？？？

从现在回溯到steam++的第一个版本为止，账号切换功能都没有更换过其它实现方式，所以每个版本都是一样的，只是中间有过一次因为steam beta机制更改，导致了旧的切换实现失效所以更改了一次切换方式。至于你的问题你应该先找寻问题原因，先弄清楚到底是ip变动导致设备信任失效还是其他原因
