### ISSUE TITLE
🧐[Question] 获取steam令牌交易数据失败，请确认是否正常加速了steam社区功能

### ISSUE THREAD

**Issue by tsy2468** [BeyondDimension/SteamTools#1921]
### 🧐 问题描述(Description)
 显示获取steam令牌交易数据失败，请确认是否正常加速了steam社区功能，但是已经加速了steam社区

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/109493872/185370576-dc12fd20-c3a4-4908-9044-fda95725e70b.png)

![image](https://user-images.githubusercontent.com/109493872/185370506-0c334df4-9e6a-435a-adb4-8de63c82138b.png)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by rmbadmin** [comment]
点击确认交易上方的注销，重登试试

**Comment by tsy2468** [comment]
> 

还是一样的，没用

**Comment by tsy2468** [comment]
![image](https://user-images.githubusercontent.com/109493872/185371393-74ff3b06-5834-423d-a77e-5d20677821e0.png)

**Comment by tsy2468** [comment]
刚刚刷新网络缓存和重置dns，都没有用

**Comment by rmbadmin** [comment]
那就先确认加速是否正常吧，浏览器能开steam社区么

**Comment by tsy2468** [comment]
浏览器能开，steam也能开，但是好像市场无法出售东西

**Comment by tsy2468** [comment]
改了下加速模式，可以了

**Comment by rmbadmin** [comment]
> 浏览器能开，steam也能开，但是好像市场无法出售东西

我测试了一下，发现可能与加速的脚本相关，你把脚本关了应该就可以了，或者打开脚本的仅对steam浏览器生效，我之后会具体检查一下问题在哪。

**Comment by tsy2468** [comment]
好的

**Comment by tsy2468** [comment]
好像不对，我把脚本关了换DNS驱动模式加速不行，但是hosts加速可以

**Comment by exaggerate-const** [comment]
我也是一样的问题，而且什么加速模式都没用，而且系统代理模式会让浏览器出现http error 500

**Comment by NealScx** [comment]
同样的问题   要不就卡在正在登陆中...
![1](https://github.com/BeyondDimension/SteamTools/assets/85844254/fca07ae6-ff2b-4472-8724-4fec0d60c8c2)

log:
2023-07-23 22:41:21.1586|Error|Process|可能是没有开加速器导致无法连接 Steam 社区登录地址 | WinAuth.WinAuthInvalidSteamRequestException: The remote server returned an error: (429) Too Many Requests.
 ---> System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.HttpWebRequest.GetResponse()
   at WinAuth.WinAuthSteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
   --- End of inner exception stack trace ---
   at System.Application.UI.ViewModels.AuthTradeWindowViewModel.<>c__DisplayClass60_0.<<Process>b__0>d.MoveNext()
