### ISSUE TITLE
🧐[Question] 可能出现打不开软件的情况

### ISSUE THREAD

**Issue by Viftten** [BeyondDimension/SteamTools#1989]
### 🧐 问题描述(Description)
时间不固定，有可能是一个月也有可能更久，自启动就启不动了，再去手动点也点不开，想继续用只能卸载重装，出现好几次了
想加群3个满员，4群不让进人，我加个锤子

### 🚑 其他信息(Other Information)
[image](https://user-images.githubusercontent.com/112924220/188554345-609eb028-f2b7-4b9b-a159-f69d0d26543e.png)甚至图标都经常不显示

- 程序版本(Program Version): 2.8.2
- 系统版本号(OS Version): Win10 19044.1889
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by AigioL** [comment]
更新到2.8.4后能复现么？

**Comment by Viftten** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Viftten** [comment]
我还在用，目前没出现情况，希望没事吧

**Comment by crimes2** [comment]
我也出现这个情况

**Comment by crimes2** [comment]
> 
错误应用程序名称: Steam++.exe，版本: 2.8.2.0，时间戳: 0x62b2f20f
错误模块名称: KERNELBASE.dll，版本: 10.0.22000.832，时间戳: 0x7efab3dc
异常代码: 0xe0434352
错误偏移量: 0x000000000004474c
错误进程 ID: 0x4bc
错误应用程序启动时间: 0x01d8c38fedc240b0
错误应用程序路径: C:\Program Files\Steam++\Steam++.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 95c168df-7fba-4b14-b754-636a409e7d6a
错误程序包全名: 
错误程序包相对应用程序 ID: 

Application: Steam++.exe
CoreCLR Version: 6.0.722.32202
.NET Version: 6.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: DI.Get* fail, serviceType: Microsoft.Extensions.Logging.ILoggerFactory
   at System.DI.Get_Nullable[T]()
   at System.Log.get_Factory()
   at System.Log.CreateLogger(String tag)
   at System.Log.Error(String tag, String msg, Object[] args)
   at System.Application.Settings.SettingsHost.Load()
   at System.Application.UI.Program.OnCreateAppExecuting(Boolean isTrace)
   at System.Application.UI.Program.Main(String[] args)

更新.NET及2.8.4后好了
