### ISSUE TITLE
🐛[BUG] 无法一键切换账号

### ISSUE THREAD

**Issue by Mishasama** [BeyondDimension/SteamTools#1993]
### 🐛 描述(Description)

在账号切换里点击一键登陆 Steam 后只关闭了 Steam，并没有启动 Steam。

### 📷 复现步骤(Steps to Reproduce)

1. 账号切换里点击一键登陆 Steam 或者离线启动
2. 弹出命令行窗口，Steam 进程被结束
3. 没然后了

### 📄 日志信息(Log Information)

[nlog-all-2022-09-09.log](https://github.com/BeyondDimension/SteamTools/files/9528215/nlog-all-2022-09-09.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version): 10.19042.1645
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by AigioL** [comment]
日志中没有纪录关于描述中的问题，倒是有几个 ERROR

#### 网络加速
```
连接超时
2022-09-09 00:04:02.8993|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|POST https://google.com/domainreliability/upload responded 502 in 30272.7266 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (HTTP connection to 2404:6800:4004:825::2003 timed out.) (HTTP connection to 64.233.164.94 timed out.) (HTTP connection to 142.251.42.131 timed out.) (www.recaptcha.net:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (HTTP connection to 2404:6800:4004:825::2003 timed out.) (HTTP connection to 64.233.164.94 timed out.) (HTTP connection to 142.251.42.131 timed out.)
 ---> System.TimeoutException: HTTP connection to 2404:6800:4004:825::2003 timed out.
   --- End of inner exception stack trace ---
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.TimeoutException: HTTP connection to 64.233.164.94 timed out.<---

 ---> (Inner Exception #2) System.TimeoutException: HTTP connection to 142.251.42.131 timed out.<---

   --- End of inner exception stack trace ---

DNS 解析失败
2022-09-09 00:08:48.6848|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://steam-chat.com/miniprofile/188593223/json responded 502 in 11980.6005 ms
System.Net.Http.HttpRequestException: そのようなホストは不明です。 (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (11001): そのようなホストは不明です。
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
```

#### 关于页面的加载捐助用户接口
```
2022-09-09 00:11:41.1778|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/ExternalTransaction/table | System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.WinHttpException (80072EE7, 12007): Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'サーバー名またはアドレスは解決されませんでした'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
2022-09-09 00:11:41.1778|Error|ApiConnectionPH|requestUri: api/ExternalTransaction/table, message: 客户端错误 1006 - An error occurred while sending the request.
Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'サーバー名またはアドレスは解決されませんでした'. | 
```

区域或语言设置的日语吗？
在通用设置中勾选了 使用 WinHttpHandler？这个不勾选没有问题的情况下是不推荐勾选的

**Comment by Mishasama** [comment]
> 区域或语言设置的日语吗？ 在通用设置中勾选了 使用 WinHttpHandler？这个不勾选没有问题的情况下是不推荐勾选的

我不清楚，下载了之后就这样用了。
我是 2.8.4 才下载来使用的新用户。

**Comment by AigioL** [comment]
> > 区域或语言设置的日语吗？ 在通用设置中勾选了 使用 WinHttpHandler？这个不勾选没有问题的情况下是不推荐勾选的
> 
> 我不清楚，下载了之后就这样用了。 我是 2.8.4 才下载来使用的新用户。

在程序内的 ```设置 - 通用设置``` 有一项 使用 ```WinHttpHandler``` 有勾选吗？

**Comment by AigioL** [comment]
弹出的命令行窗口，有显示内容吗？
复现步骤中第三步再点击 一键登陆 Steam 有什么效果吗？

**Comment by Mishasama** [comment]
> > > 区域或语言设置的日语吗？ 在通用设置中勾选了 使用 WinHttpHandler？这个不勾选没有问题的情况下是不推荐勾选的
> > 
> > 
> > 我不清楚，下载了之后就这样用了。 我是 2.8.4 才下载来使用的新用户。
> 
> 在程序内的 `设置 - 通用设置` 有一项 使用 `WinHttpHandler` 有勾选吗？

有开，要关掉吗？

> 弹出的命令行窗口，有显示内容吗？ 复现步骤中第三步再点击 一键登陆 Steam 有什么效果吗？

我眼睛跟不上屏幕的刷新，一闪而过，看不到内容。
反复点击是一样的效果。（即 Steam 已经没有进程在运行的状态下）
