### ISSUE TITLE
Steam++无法加速，商店和社区好友界面打不开，求助

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#2085]
无法加速，商店和社区界面打不开，错误日志如下。
2022-10-06 15:47:24.9765|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-10-06 15:47:48.2766|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://api.steampowered.com/ISteamDirectory/GetCMListForConnect/v0001/ responded 502 in 9.8768 ms
System.ApplicationException: Because https://api.steampowered.com/ISteamDirectory/GetCMListForConnect/v0001/?cellid=205&format=vdf actually points to WattToolkit itself, WattToolkit has interrupted this forwarding
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 
2022-10-06 15:48:32.1774|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|POST https://api.steampowered.com/ISteamUserAuth/AuthenticateUser/v0001/ responded 502 in 0.8922 ms
System.ApplicationException: Because https://api.steampowered.com/ISteamUserAuth/AuthenticateUser/v0001/ actually points to WattToolkit itself, WattToolkit has interrupted this forwarding
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 
2022-10-06 15:48:32.1774|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|POST https://api.steampowered.com/ISteamUserAuth/AuthenticateUser/v0001/ responded 502 in 0.3789 ms
System.ApplicationException: Because https://api.steampowered.com/ISteamUserAuth/AuthenticateUser/v0001/ actually points to WattToolkit itself, WattToolkit has interrupted this forwarding
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) | 
2022-10-06 15:52:51.4013|Error|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HML7DS1A4PTV", Request id "0HML7DS1A4PTV:00000001": An unhandled exception was thrown by the application. |ConnectionId=0HML7DS1A4PTV, TraceIdentifier=0HML7DS1A4PTV:00000001, EventId=13, EventName=ApplicationError System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateScope()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.CreateScope()
   at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.get_RequestServices()
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestServices()
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.ResolveSerializerOptions(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync[TValue](HttpResponse response, TValue value, JsonSerializerOptions options, String contentType, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync[TValue](HttpResponse response, TValue value, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.HandleErrorAsync(HttpContext context, ForwarderError error)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyPacMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpLocalRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2022-10-06 16:03:58.2418|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2022-10-06 16:07:15.6733|Error|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HML7E59UI010", Request id "0HML7E59UI010:00000001": An unhandled exception was thrown by the application. |ConnectionId=0HML7E59UI010, TraceIdentifier=0HML7E59UI010:00000001, EventId=13, EventName=ApplicationError System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateScope()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.CreateScope()
   at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.get_RequestServices()
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestServices()
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.ResolveSerializerOptions(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync[TValue](HttpResponse response, TValue value, JsonSerializerOptions options, String contentType, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync[TValue](HttpResponse response, TValue value, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.HandleErrorAsync(HttpContext context, ForwarderError error)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyPacMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpLocalRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2022-10-06 19:18:54.8303|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://steamcommunity.com/profiles/76561198422437934/home/ responded 502 in 40200.4674 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (HTTP connection to 23.32.237.58 timed out.) (HTTP connection to 23.32.237.43 timed out.) (HTTP connection to 2001::c73b:95ec timed out.) (HTTP connection to 173.252.88.133 timed out.) (steamcommunity.com:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (HTTP connection to 23.32.237.58 timed out.) (HTTP connection to 23.32.237.43 timed out.) (HTTP connection to 2001::c73b:95ec timed out.) (HTTP connection to 173.252.88.133 timed out.)
 ---> System.TimeoutException: HTTP connection to 23.32.237.58 timed out.
   --- End of inner exception stack trace ---
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.TimeoutException: HTTP connection to 23.32.237.43 timed out.<---

 ---> (Inner Exception #2) System.TimeoutException: HTTP connection to 2001::c73b:95ec timed out.<---

 ---> (Inner Exception #3) System.TimeoutException: HTTP connection to 173.252.88.133 timed out.<---

   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) |

**Comment by rmbadmin** [comment]
使用的程序版本号是最新的吗？  错误提示是程序反复代理了自身导致的请求中止

**Comment by CN-Hinata** [comment]
> 

是最新的。2.8.4Windows版本

**Comment by ghost** [comment]
> 使用的程序版本号是最新的吗？ 错误提示是程序反复代理了自身导致的请求中止

是最新的，2.8.4Windows版本

**Comment by CN-Hinata** [comment]
> 使用的程序版本号是最新的吗？ 错误提示是程序反复代理了自身导致的请求中止
更换自定义代理DNS之后，Steam商店和社区出现错误105。现在B站好多人都出现这种问题了。

**Comment by ghost** [comment]
> 使用的程序版本号是最新的吗？ 错误提示是程序反复代理了自身导致的请求中止

更换自定义代理DNS之后，Steam商店和社区出现错误105。现在B站好多人都出现这种问题了。
