### ISSUE TITLE
🐛[BUG] 一启动应用就提示【Failed initializing notifications】

### ISSUE THREAD

**Issue by HegeKen** [BeyondDimension/SteamTools#2189]
### 🐛 描述(Description)
一启动应用就提示【Failed initializing notifications】

### 📷 复现步骤(Steps to Reproduce)
一启动应用就提示【Failed initializing notifications】，并且游戏库存列表一直处于正在加载中的状态；
很抱歉之前确实没有注意到，不知道是不是因为升级Win11 Dev导致的。

### 📄 日志信息(Log Information)
2022-10-30 23:06:37.7213|Error|SteamConnectService|SteamConnect Task LongRunning | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at System.Application.Services.Implementation.Windows10NotificationServiceImpl.System.Application.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at System.Application.Services.SteamConnectService.<Initialize>b__49_0()
2022-10-30 23:08:38.1004|Error|SteamConnectService|SteamConnect Task LongRunning | System.InvalidOperationException: Failed initializing notifications

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.8.4
- 系统版本号(OS Version):  Win 11 Dev 25231.1000
- 是否为应用商店版本(Whether it is a Store version): 否(No)

**Comment by CDmking** [comment]
初始化失败一般是程序不正确启动造成，试着卸载重装。若不能解决问题，请及时回复并上传相关日志。

**Comment by HegeKen** [comment]
好的，我试试重装。

**Comment by HegeKen** [comment]
重装后问题依旧存在。


2022-10-31 15:59:46.0404|Error|SteamConnectService|SteamConnect Task LongRunning | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at System.Application.Services.Implementation.Windows10NotificationServiceImpl.System.Application.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at System.Application.Services.SteamConnectService.<Initialize>b__49_0()
2022-10-31 16:01:12.6847|Error|SteamConnectService|SteamConnect Task LongRunning | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at System.Application.Services.Implementation.Windows10NotificationServiceImpl.System.Application.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at System.Application.Services.SteamConnectService.<Initialize>b__49_0()

**Comment by CDmking** [comment]
您是在 Windows 11 上使用UWP版本而无法使用的吗？如果是，但不想退回 Windows 10，可以考虑使用安装包或便携版。同时请保留此Issue，以便于开发者完善代码。

**Comment by HegeKen** [comment]
我用的是安装包进行安装的，看到您说的使用Windows 商店安装了一下UWP版本，问题解决了。谢谢。
