### ISSUE TITLE
🐛[BUG] 闪退，无法打开应用

### ISSUE THREAD

**Issue by DaYePython** [BeyondDimension/SteamTools#2321]
### 🐛 描述(Description)
闪退，无法打开应用

### 📷 复现步骤(Steps to Reproduce)

1. 打开就闪退

### 📄 日志信息(Log Information)

```
2022-12-05 08:55:27.3252|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService
   at System.DI.Get_Nullable[T]()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
2022-12-05 08:55:27.3252|Error|ViaFactory|(App)Close exception when exception occurs | System.ArgumentNullException: Value cannot be null. (Parameter 'app')
   at System.Application.UI.App.get_Instance()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
```

-->

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version):window11 21H2 22000.1219
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by DaYePython** [comment]
升级到2.8.4就可以了
