### ISSUE TITLE
🐛[BUG] 启用加速服务后占用22端口导致使用git push失败

### ISSUE THREAD

**Issue by Cey1anze** [BeyondDimension/SteamTools#2500]
🐛 描述(Description)
开启加速服务后，会占用22端口，导致git auto fetch和push失败

📷 复现步骤(Steps to Reproduce)
1. 开启watt toolkit加速服务
2. 本机进行git push
3. push失败

📄 日志信息(Log Information)
```
--- End of stack trace from previous location ---
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.HandleScriptInject(HttpContext context, IEnumerable`1 scripts, MemoryStream body, Stream originalBody)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyPacMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpLocalRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2023-01-28 21:06:36.0446|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HMO0QRJAFR9C. |ConnectionId=0HMO0QRJAFR9C System.Net.Sockets.SocketException (10055): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.TcpReverseProxyHandler.CreateConnectionAsync(CancellationToken cancellationToken)
2023-01-28 21:07:23.9520|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HMO0QRJAG12O. |ConnectionId=0HMO0QRJAG12O System.Net.Sockets.SocketException (10055): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.TcpReverseProxyHandler.CreateConnectionAsync(CancellationToken cancellationToken)
2023-01-28 21:07:39.3483|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HMO0QRJAG1D0. |ConnectionId=0HMO0QRJAG1D0 System.Net.Sockets.SocketException (10055): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.TcpReverseProxyHandler.CreateConnectionAsync(CancellationToken cancellationToken)
2023-01-28 21:08:00.9108|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HMO0QRJAG1MF. |ConnectionId=0HMO0QRJAG1MF System.Net.Sockets.SocketException (10055): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.TcpReverseProxyHandler.CreateConnectionAsync(CancellationToken cancellationToken)
2023-01-28 21:08:02.3223|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HMO0QRJAG1VR. |ConnectionId=0HMO0QRJAG1VR System.Net.Sockets.SocketException (10055): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.HttpServer.TcpReverseProxyHandler.CreateConnectionAsync(CancellationToken cancellationToken)
```

🚑 基本信息(Basic Information)

- 程序版本(Program Version):v2.8.6
- 系统版本号(OS Version):win11 professional 22623.1245
- 是否为应用商店版本(Whether it is a Store version): 是(Yes)

🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/87941132/215268394-d13b2497-5778-4417-8106-72819f3c3333.png)
![image](https://user-images.githubusercontent.com/87941132/215268447-2f9ed7c3-9e11-4af4-a109-765fed346e1c.png)

**Comment by HappyRespawnanchor** [comment]
![image](https://user-images.githubusercontent.com/80967824/215762756-e5b6ca82-032a-48b7-9b29-bb458a4205e2.png)
![image](https://user-images.githubusercontent.com/80967824/215762934-bceb5881-0446-4bb8-b71d-467a9a23d11e.png)
成功复现。（同不加速github网站git push就正常，但是那样网页就会被间歇墙）

**Comment by flycran** [comment]
占坑，我也是push失败

**Comment by looly** [comment]
同push失败。

开启加速github网页可以访问，但是git push失败。关闭加速github网页无法访问，但是git push正常。

**Comment by houranled** [comment]
开启加速后, git pull , git push 都失败. 报错:
![Image](https://github.com/user-attachments/assets/8e4a6e4d-1530-47ca-ba8b-b26c39bbf256)


在终端执行命令可以临时解决:git config --global http.sslVerify false
