### ISSUE TITLE
加速界面卡住，无加速效果🐛[BUG] 

### ISSUE THREAD

**Issue by TZHCODY** [BeyondDimension/SteamTools#2520]
### 🐛 描述(Description)
有概率出现，无法加速，而且最近还有一个问题就是就算加速成功了好友网络也无法连接，要等一会才能连接

### 📷 复现步骤(Steps to Reproduce)

1. 打开软件
2. 开始加速
3. 有概率直接出现

### 📄 日志信息(Log Information)
2023-02-06 09:08:20.3512|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-02-06 09:08:23.4086|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-02-06 09:08:26.4268|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-02-06 09:08:29.4451|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-02-06 09:08:32.4723|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.6
- 系统版本号(OS Version): Windows 11 22623.870
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

![Clip_20230206_091633](https://user-images.githubusercontent.com/33798989/216860436-b6aa23ce-0897-4a8c-9317-bf0d7473cb86.png)

**Comment by ZmdNotFound** [comment]
Android arm64 客户端（V2.8.3）出现相同问题
