### ISSUE TITLE
突然Steam++打不开了 UAC会显示 确定以后软件无反应

### ISSUE THREAD

**Issue by takaqiao** [BeyondDimension/SteamTools#2682]
log文件`2023-03-29 16:19:53.1106|Error|SettingsHost|Config Load, isLoad: False | MessagePack.MessagePackSerializationException: Failed to deserialize System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] value.
 ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 0 (positive fixint) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
   at MessagePack.MessagePackReader.ReadMapHeader()
   at MessagePack.Formatters.DictionaryFormatterBase`5.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.DeserializeFromSequenceAndRewindStreamIfPossible[T](Stream streamToRewind, MessagePackSerializerOptions options, ReadOnlySequence`1 sequence, CancellationToken cancellationToken)
   at MessagePack.MessagePackSerializer.Deserialize[T](Stream stream, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at System.Serializable.DMP[T](Stream buffer, CancellationToken cancellationToken)
   at System.Application.Settings.FileSettingsProvider.Load()
   at System.Application.Settings.SettingsHost.Load()
2023-03-29 16:19:53.1406|Error|MessagePack.MessagePackSerializer|Stopped program because of exception, name: AppDomain, isTerminating: True | MessagePack.MessagePackSerializationException: Failed to deserialize System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] value.
 ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 0 (positive fixint) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
   at MessagePack.MessagePackReader.ReadMapHeader()
   at MessagePack.Formatters.DictionaryFormatterBase`5.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.DeserializeFromSequenceAndRewindStreamIfPossible[T](Stream streamToRewind, MessagePackSerializerOptions options, ReadOnlySequence`1 sequence, CancellationToken cancellationToken)
   at MessagePack.MessagePackSerializer.Deserialize[T](Stream stream, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at System.Serializable.DMP[T](Stream buffer, CancellationToken cancellationToken)
   at System.Application.Settings.FileSettingsProvider.Load()
   at System.Application.Settings.SettingsHost.Load()
   at System.Application.UI.Program.OnCreateAppExecuting(Boolean isTrace)
   at System.Application.UI.Program.Main(String[] args)
`
现已确认local中的Steam++数据删除后就正常开启 具体原因未知

**Comment by takaqiao** [comment]
[internal-nlog.txt](https://github.com/BeyondDimension/SteamTools/files/11097579/internal-nlog.txt)
[nlog-all-2023-03-29.log](https://github.com/BeyondDimension/SteamTools/files/11097580/nlog-all-2023-03-29.log)

**Comment by Mossimos** [comment]
该问题是配置文件 保存出错了，导致无法正确读取 导致的不启动

**Comment by takaqiao** [comment]
> 该问题是配置文件 保存出错了，导致无法正确读取 导致的不启动

我自己刚刚试了 config文件删掉就能启动了 但是如果不懂基础电脑的人遇到这个问题会很头疼啊 有没有failsafe的功能 希望后续3.0能更新一个 防止该问题发生
