### ISSUE TITLE
🐛[BUG] pixiv加速突然就用不了了重新下载后偶尔有能访问上

### ISSUE THREAD

**Issue by MDeath** [BeyondDimension/SteamTools#2692]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

pixiv加速突然就用不了了重新下载后偶尔有能访问上

### 📷 复现步骤

1. 17号早上就开始访问pixiv报502
2. 切换加速模式重置host都无效
3. 删除干净后重新下载，加速后短暂可以访问，过一阵又会提示443

### 📄 日志信息

```
2023-04-18 00:04:06.8161|Error|System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware|GET https://www.pixiv.net/ responded 502 in 20016.5125 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (HTTP connection to 31.13.75.5 timed out.) (HTTP connection to 104.244.43.35 timed out.) (www.pixiv.net:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (HTTP connection to 31.13.75.5 timed out.) (HTTP connection to 104.244.43.35 timed out.)
 ---> System.TimeoutException: HTTP connection to 31.13.75.5 timed out.
   --- End of inner exception stack trace ---
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.TimeoutException: HTTP connection to 104.244.43.35 timed out.<---

   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer) 
```
重装后短暂的可以访问，但过一阵后依旧报错
### 🖼 截图

![image](https://user-images.githubusercontent.com/42289879/232550541-47040fc0-eab8-41ff-8bb4-646e9f62c2fc.png)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：example Windows 11 22H2 (22621.1555)
- 下载渠道：Github
- 程序版本：2.8.6
- 是否包含独立运行时：fde

**Comment by la2ygoo** [comment]
俺也一样
显示：Request:Could not find any IP that can be successfully connected. (HTTP connection to 108.160.166.49 timed out.) (HTTP connection to 202.160.128.238 timed out.) (www.pixiv.net:443)

**Comment by Dingzheng0615** [comment]
俺也一样

**Comment by efccj** [comment]
一样，试了各种方法都无效，从昨天晚上就开始出现这种情况

**Comment by toyoshita** [comment]
同样的问题，昨天傍晚开始除了steam其他的加速都失效了

**Comment by zza66** [comment]
俺也一样

**Comment by danjvanjun** [comment]
俺也一样

**Comment by CXZom** [comment]
同啊

**Comment by rmbadmin** [comment]
已经修复，等待dns缓存刷新，或者手动 ipconfig /flushdns 后重新加速应该就好了
