### ISSUE TITLE
🐛[BUG] 内置 Steam 令牌功能无法通过 Steam 账户导入令牌

### ISSUE THREAD

**Issue by imhuangyu** [BeyondDimension/SteamTools#2696]
## 请认真检查以下清单中的每一项
- [ √] 已经搜索过，没有发现类似的 issue
- [ √] 已经搜索过文档，没有发现相关内容
- [ √] 已经尝试使用过最新版，问题依旧存在
- [ √] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

当我在尝试通过 “Steam 账号导入” 功能导入 Steam 令牌时，提示
"Error enrolling new authenticator
The remote server returned an error: (404) Not Found.
The remote server returned an error: (404) Not Found."
已开启加速器且非共享加速器；确定节点可以与 Steam 伺服器通讯

### 📷 复现步骤

1. 启动 Watt Tookit
2. 在“令牌”页面点击“新增”
3. 通过 ”Steam 账号导入“ 导入令牌

### 📄 日志信息
 WinAuth.WinAuthInvalidRequestException: The remote server returned an error: (404) Not Found.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   at System.Application.UI.ViewModels.AddAuthWindowViewModel.LoginSteamImport()
2023-04-23 00:44:02.1348|Error|AddAuthWindowViewModel|LoginSteamImport | WinAuth.WinAuthInvalidEnrollResponseException: Error enrolling new authenticator
 ---> WinAuth.WinAuthInvalidRequestException: The remote server returned an error: (404) Not Found.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   at System.Application.UI.ViewModels.AddAuthWindowViewModel.LoginSteamImport()
2023-04-23 00:44:10.4634|Error|AddAuthWindowViewModel|LoginSteamImport | WinAuth.WinAuthInvalidEnrollResponseException: Error enrolling new authenticator
 ---> WinAuth.WinAuthInvalidRequestException: The remote server returned an error: (404) Not Found.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   at System.Application.UI.ViewModels.AddAuthWindowViewModel.LoginSteamImport()
2023-04-23 00:44:40.9430|Error|AddAuthWindowViewModel|LoginSteamImport | WinAuth.WinAuthInvalidEnrollResponseException: Error enrolling new authenticator
 ---> WinAuth.WinAuthInvalidRequestException: The remote server returned an error: (404) Not Found.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   at System.Application.UI.ViewModels.AddAuthWindowViewModel.LoginSteamImport()
2023-04-23 00:44:44.1230|Error|AddAuthWindowViewModel|LoginSteamImport | WinAuth.WinAuthInvalidEnrollResponseException: Error enrolling new authenticator
 ---> WinAuth.WinAuthInvalidRequestException: The remote server returned an error: (404) Not Found.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   at System.Application.UI.ViewModels.AddAuthWindowViewModel.LoginSteamImport()
2023-04-23 01:24:02.4954|Error|AddAuthWindowViewModel|LoginSteamImport | WinAuth.WinAuthInvalidEnrollResponseException: Error enrolling new authenticator
 ---> WinAuth.WinAuthInvalidRequestException: The remote server returned an error: (404) Not Found.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout)
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   --- End of inner exception stack trace ---
   at System.Application.Models.GAPAuthenticatorValueDTO.SteamAuthenticator.Enroll(EnrollState state)
   at System.Application.UI.ViewModels.AddAuthWindowViewModel.LoginSteamImport()
`

-->

### 🖼 截图

![image](https://user-images.githubusercontent.com/112412144/233798273-4e8905df-e810-4dda-b607-2b1b05362013.png)

### 🚑 其他信息

- 处理器体系结构： x64
- 系统版本号： Windows 11 Professional 22621.1413
- 下载渠道： GitHub
- 程序版本：2.8.6
- 是否包含独立运行时：包含

**Comment by imhuangyu** [comment]
日志文件：https://github.com/BeyondDimension/SteamTools/files/11301944/nlog-all-2023-04-23.log

**Comment by ghost** [comment]
请问解决了吗？我也遇到这个问题了。

**Comment by imhuangyu** [comment]
> 请问解决了吗？我也遇到这个问题了。

没有，目前更换了几个加速器与设备均会出现本情况，估计是程序的问题吧 等等开发者吧:)

**Comment by rmbadmin** [comment]
应该是 steam 方面更新了新版本令牌之后移除了旧的令牌绑定接口，所以等更新新版本的导入吧

**Comment by imhuangyu** [comment]
> 应该是 steam 方面更新了新版本令牌之后移除了旧的令牌绑定接口，所以等更新新版本的导入吧

感谢

**Comment by zaqwerfvcx** [comment]
哎 我也是 重装系统忘了备份 好几个号要重新解绑重新登陆 还遇到这个问题。。。

**Comment by ZSkycat** [comment]
能否通过其他第三方软件绑定后导出，实现曲线救国方案？

**Comment by skyyuh002** [comment]
> 能否通过其他第三方软件绑定后导出，实现曲线救国方案？
要么安卓12以下的模拟器安装2.x版本的steam，登录并提取uuid 和SteamGuard来添加（模拟器须有root权限）
要么使用sda（SteamDesktopAuthenticator）登录，然后使用steam++导入
//只要思想不滑坡，办法总比困难多

**Comment by ZSkycat** [comment]
我试用过了 SteamDesktopAuthenticator（不确定是否是我操作错误），绑定之后，主界面不显示令牌，之后只能用安全码解绑。而且我看这个软件从20年就没有再更新了，似乎已经失效了。

**Comment by ya-zhe** [comment]
我也是提示404

**Comment by Immortal-Sty** [comment]
我也出现了一样的情况，但报错不太一样：

## 🖼 截图

![](https://raw.githubusercontent.com/Immortal-Sty/imgBed/master/PicGo/202308220248184.png?token=AWP2C6OCUUTPRL3IWTT2CCTE4OY56)

## 🚑 其他信息

- 处理器体系结构： x64
- 系统版本号： Windows 11 22H2
- 下载渠道： GitHub
- 程序版本：2.8.6
