### ISSUE TITLE
🐛[BUG] Manjaro上开启加速后Steam卡在Logging in但是一直有流量,关闭后Steam正常

### ISSUE THREAD

**Issue by Seraphli** [BeyondDimension/SteamTools#2758]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

Manjaro上开启加速后Steam卡在Logging in但是一直有流量,关闭加速后就登录进去了。加速情况下在浏览器上访问网页没有问题。只有客户端登录不上去

flatpak安装的就有问题，但是multilib的Steam(Runtime)就没有问题

### 📷 复现步骤

1. 开启加速
2. 打开flatpak版的Steam

### 📄 日志信息

```
2023-07-04 23:13:27.0114|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load Steam
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-07-04 23:13:42.0499|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load Steam
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-07-04 23:13:45.0569|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load Steam
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-07-04 23:13:48.0639|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load Steam
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-07-04 23:13:51.0710|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load Steam
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```
全部是同样的错误

### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/1586755/cdee7123-416b-48ef-b057-4b043b758150)
![image](https://github.com/BeyondDimension/SteamTools/assets/1586755/1ede7a2d-99b7-4003-830f-cd58d94a7880)
![image](https://github.com/BeyondDimension/SteamTools/assets/1586755/bc5904cc-87d7-49fb-a4cb-97b713d758ff)

### 🚑 其他信息

- 处理器体系结构： x64
- 系统版本号： Manjaro  6.1.31-2-MANJARO
- 下载渠道： Github
- 程序版本： 2.8.4
- 是否包含独立运行时： AUR版本

**Comment by sparrowhe** [comment]
疑似是flatpak steam与chrome没有共享信任证书的问题

**Comment by Seraphli** [comment]
> 疑似是flatpak steam与chrome没有共享信任证书的问题

我明明已经写了是AUR版本

**Comment by sparrowhe** [comment]
> > 疑似是flatpak steam与chrome没有共享信任证书的问题
> 
> 我明明已经写了是AUR版本

> 1. 打开flatpak版的Steam

> 疑似是**flatpak** **steam**

我这里可以复现同样的问题

**Comment by Seraphli** [comment]
哦哦说的是Steam，看错了。这个问题存在很久了，一直没有解决。

**Comment by Mossimos** [comment]
该问题 暂时无法解决 只能登录时停止加速先 
是因为 Steam 的 CEF 在登录窗口的 
` https://steamloopback.host`
没处理好 导致请求到了 Steam++ 上 然而这个是本应该 CEF 内部处理的地址

**Comment by Seraphli** [comment]
是的我也是这样操作的

**Comment by Substance7384** [comment]
此问题在所有Linux发行版上存在
测试过存在此问题的发行版: Arch Linux、endeavourOS、Manjaro、Debian、Deepin、Ubuntu/Kubuntu、Linux Mint、Fedora

**Comment by Mossimos** [comment]
沙盒环境中的证书问题 得自己处理

**Comment by Mossimos** [comment]
回复错了，这个问题是由于 Steam 使用的 Chrome BUG 导致的 。 目前只能在登录时关闭加速。  你使用任意抓包软件也能复现 在登陆时开启抓包软件无法登录
