### ISSUE TITLE
🧐[Question] 3.0版本 令牌交易闪退

### ISSUE THREAD

**Issue by yorshkas** [BeyondDimension/SteamTools#2824]
程序版本3.0.0.107

安装路径 D:\software\System\Tools

设备信息
版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.2134
体验	Windows Feature Experience Pack 1000.22659.1000.0

在尝试点击 令牌的交易功能 时 程序直接 闪退

log 信息为：

2023-09-08 10:47:42.2776|Error|SteamConnectService|Initialize Error | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at BD.WTTS.Services.SteamConnectService.<Initialize>b__53_0()

**Comment by rmbadmin** [comment]
这个闪退日志应该与交易确认无关，能详细描述下交易确认的闪退过程么

**Comment by yorshkas** [comment]
![动画](https://github.com/BeyondDimension/SteamTools/assets/29173838/4a4ff388-c313-4a1b-83a9-c88bdd51ffbf)
如图所示 
每次点击  确认交易 那个按钮的时候  下一步它就自动闪退了 包括 任务栏小图标

**Comment by yorshkas** [comment]
> 这个闪退日志应该与交易确认无关，能详细描述下交易确认的闪退过程么
![QQ截图20230909001216](https://github.com/BeyondDimension/SteamTools/assets/29173838/dfabd73c-bda3-43b1-9907-f82c1c500a3a)

如图所示 
每次按下 圈处的按钮 软件就真的闪退了 任务栏处小图标也没了

**Comment by rmbadmin** [comment]
> > 这个闪退日志应该与交易确认无关，能详细描述下交易确认的闪退过程么
> > ![QQ截图20230909001216](https://user-images.githubusercontent.com/29173838/266673997-dfabd73c-bda3-43b1-9907-f82c1c500a3a.png)
> 
> 如图所示 每次按下 圈处的按钮 软件就真的闪退了 任务栏处小图标也没了

查看令牌详细信息是否也会闪退，日志文件是否还有其他错误日志

**Comment by yorshkas** [comment]
查看

> > > 这个闪退日志应该与交易确认无关，能详细描述下交易确认的闪退过程么
> > > ![QQ截图20230909001216](https://user-images.githubusercontent.com/29173838/266673997-dfabd73c-bda3-43b1-9907-f82c1c500a3a.png)
> > 
> > 
> > 如图所示 每次按下 圈处的按钮 软件就真的闪退了 任务栏处小图标也没了
> 
> 查看令牌详细信息是否也会闪退，日志文件是否还有其他错误日志

查看详细信息 无反应 

`2023-09-09 00:07:49.1739|Error|SteamS|KillSteamProcess fail. | System.ComponentModel.Win32Exception (5): 拒绝访问。
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at BD.SteamClient.Services.Implementation.SteamServiceImpl.KillSteamProcess()
   at BD.SteamClient.Services.Implementation.SteamServiceImpl.TryKillSteamProcess()
2023-09-09 00:15:41.9344|Error|SteamConnectService|Initialize Error | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at BD.WTTS.Services.SteamConnectService.<Initialize>b__53_0()
2023-09-09 00:16:40.2815|Error|SteamConnectService|Initialize Error | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at BD.WTTS.Services.SteamConnectService.<Initialize>b__53_0()
2023-09-09 00:16:51.2444|Error|SteamConnectService|Initialize Error | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at BD.WTTS.Services.SteamConnectService.<Initialize>b__53_0()
2023-09-09 00:21:59.2331|Error|SteamConnectService|Initialize Error | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at BD.WTTS.Services.SteamConnectService.<Initialize>b__53_0()
2023-09-09 00:22:21.2139|Error|SteamConnectService|Initialize Error | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at BD.WTTS.Services.SteamConnectService.<Initialize>b__53_0()
2023-09-09 11:55:48.3644|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-09-09 11:55:51.9694|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-09-09 11:55:54.9776|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-09-09 11:55:57.9938|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-09-09 11:56:00.9995|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-09-09 11:56:11.7971|Error|SteamConnectService|Initialize Error | System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)
   at BD.WTTS.Services.SteamConnectService.<Initialize>b__53_0()
2023-09-09 11:59:34.0295|Error|SteamS|KillSteamProcess fail. | System.ComponentModel.Win32Exception (5): 拒绝访问。
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at BD.SteamClient.Services.Implementation.SteamServiceImpl.KillSteamProcess()
   at BD.SteamClient.Services.Implementation.SteamServiceImpl.TryKillSteamProcess()
`

**Comment by 1999wx** [comment]
我也有这个问题唉,而且查看不了详细数据,还好手机app能复制令牌数据

**Comment by yorshkas** [comment]
> 我也有这个问题唉,而且查看不了详细数据,还好手机app能复制令牌数据

emm 只能看下个版本了
