### ISSUE TITLE
🐛[BUG] 启动 Watt Tookit 弹出 Application Crash

### ISSUE THREAD

**Issue by WitherZuo** [BeyondDimension/SteamTools#2873]
## 请认真检查以下清单中的每一项  

- [ x ] 已经搜索过，没有发现类似的 issue
- [ x ] 已经搜索过文档，没有发现相关内容
- [ x ] 已经尝试使用过最新版，问题依旧存在
- [ x ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在最新的 Windows 预览版金丝雀渠道 Build 25951 上，启动 Watt Toolkit 有大概率弹出下图报错，然后过一段时间程序自动退出。也有可能下一次启动时就不会再弹出 Application Crash。

### 📷 复现步骤

1. 启动 Watt Tookit
2. 等待一会儿，程序会自动弹出 Application Crash 窗口
3. 点击确定关闭窗口，几秒后程序会自动退出

### 📄 日志信息

```
2023-09-16 09:14:35.3859|Error|BD.WTTS.Startup+GlobalExceptionHandler|Stopped program because of exception, name: AppDomain, isTerminating: True | dotnetCampus.Ipc.Exceptions.IpcInvokingTimeoutException: Exception of type 'dotnetCampus.Ipc.Exceptions.IpcInvokingTimeoutException' was thrown.
   at dotnetCampus.Ipc.CompilerServices.GeneratedProxies.GeneratedIpcProxy`1.InvokeWithTimeoutAsync[T](MemberInvokingType callType, UInt64 memberId, String memberName, IGarmObject[] args, Int32 millisecondsTimeout, Boolean ignoreException, Object defaultReturn)
   at dotnetCampus.Ipc.CompilerServices.GeneratedProxies.GeneratedIpcProxy`1.IpcInvokeAsync[T](MemberInvokingType callType, UInt64 memberId, String memberName, IGarmObject[] args, IpcProxyMemberNamedValues namedValues)
   at BD.WTTS.Services.ProxyService.StartProxyServiceAsync()
   at BD.WTTS.Services.ProxyService.<.ctor>b__7_5(Boolean proxyStatusLeft)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

```

### 🖼 截图

![QQ截图20230916091726](https://github.com/BeyondDimension/SteamTools/assets/25317916/c95b06d9-8ced-426d-bcc1-90dfd0103b3f)

![QQ截图20230916093609](https://github.com/BeyondDimension/SteamTools/assets/25317916/a0624581-ea9d-4d06-906e-1a234308f2a0)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 Insider Preview 25951.1010
- 下载渠道：GitHub
- 程序版本：3.0.0-rc1
- 是否包含独立运行时：程序自带运行时
- 对 Watt Tookit 的额外设置：开启“启动时自动启动加速”

**Comment by AigioL** [comment]
这个异常应该与加速子进程(Steam++.Accelerator.exe)因为什么原因没有正确启动有关，也有可能因为 UAC 弹窗阻止了管理员进程的启动

https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/1318840699u/overview
```
Exception Stack:
dotnetCampus.Ipc.Exceptions.IpcInvokingTimeoutException: Exception of type 'dotnetCampus.Ipc.Exceptions.IpcInvokingTimeoutException' was thrown.
  at dotnetCampus.Ipc.CompilerServices.GeneratedProxies.GeneratedIpcProxy`1.InvokeWithTimeoutAsync[T](MemberInvokingType callType, UInt64 memberId, String memberName, IGarmObject[] args, Int32 millisecondsTimeout, Boolean ignoreException, Object defaultReturn)
  at dotnetCampus.Ipc.CompilerServices.GeneratedProxies.GeneratedIpcProxy`1.IpcInvokeAsync[T](MemberInvokingType callType, UInt64 memberId, String memberName, IGarmObject[] args, IpcProxyMemberNamedValues namedValues)
  at BD.WTTS.Services.ProxyService.StartProxyServiceAsync()
  at BD.WTTS.Services.ProxyService.<.ctor>b__7_5(Boolean proxyStatusLeft)
  at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
  at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Most affected devices
? 18.6%
To be filled by O.E.M. 3.6%
82JQ 3.0%
Others 74.9%

Most affected OS
10.0.22621 37.1%
10.0.19045 33.5%
10.0.19044 7.1%
Others 22.4%

[Windows11_InsiderPreview_Client_x64_zh-cn_25951.iso](https://software.download.prss.microsoft.com/dbazure/Windows11_InsiderPreview_Client_x64_zh-cn_25951.iso?t=f682825d-8a9a-40f7-b29b-fe9e55d2a97c&e=1695102560&h=d146e4ba1b20ad927edde5cc058b71ad19a4e6bdb5ff1565aad6a6d1e64f101f)

**Comment by AigioL** [comment]
无法复现

![image](https://github.com/BeyondDimension/SteamTools/assets/24450093/560133b6-adb4-4a9f-8824-610bdcdd427e)

**Comment by PtJade-Ceramic** [comment]
我遇到了类似的异常：
<img width="970" height="644" alt="Image" src="https://github.com/user-attachments/assets/4c00215a-689c-46ca-b960-589b083abd46" />
