### ISSUE TITLE
🐛[BUG] 开机自启会弹窗报错

### ISSUE THREAD

**Issue by tianmiao8152** [BeyondDimension/SteamTools#2955]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

开启自启后弹窗报错

### 🐛 描述
开启自启后弹窗报错

### 📷 复现步骤

1. 设置开机自启后即弹窗报错

### 📄 日志信息

"2023-10-15 09:51:24.2574|Error|BD.WTTS.Startup+GlobalExceptionHandler|Stopped program because of exception, name: AppDomain, isTerminating: True | dotnetCampus.Ipc.Exceptions.IpcInvokingTimeoutException: Exception of type 'dotnetCampus.Ipc.Exceptions.IpcInvokingTimeoutException' was thrown.
   at dotnetCampus.Ipc.CompilerServices.GeneratedProxies.GeneratedIpcProxy`1.InvokeWithTimeoutAsync[T](MemberInvokingType callType, UInt64 memberId, String memberName, IGarmObject[] args, Int32 millisecondsTimeout, Boolean ignoreException, Object defaultReturn)
   at dotnetCampus.Ipc.CompilerServices.GeneratedProxies.GeneratedIpcProxy`1.IpcInvokeAsync[T](MemberInvokingType callType, UInt64 memberId, String memberName, IGarmObject[] args, IpcProxyMemberNamedValues namedValues)
   at BD.WTTS.Services.ProxyService.StartProxyServiceAsync()
   at BD.WTTS.Services.ProxyService.<.ctor>b__7_5(Boolean proxyStatusLeft)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()"

### 🖼 截图

![{44AEB054-40D3-4ef2-94E1-4C431CF6F227}](https://github.com/BeyondDimension/SteamTools/assets/83683108/1af78f66-d208-41a1-bc75-e185d2e58ae8)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10.19045.3570
- 下载渠道：Github
- 程序版本：3.0.0-rc2
- 是否包含独立运行时：

**Comment by yopoou** [comment]
同样问题，尝试将应用兼容性设置为全局管理员启动，会导致开机自启失效。

**Comment by RizukiJI** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/112483213/8e390f09-8609-42b3-a7d9-98b58a001051)
同样问题，尝试在任务计划程序里设置延迟启动，无法解决

**Comment by hanhaozi** [comment]
有同样的问题, 在任务计划程序里报错0xE0434352
