### ISSUE TITLE
挂卡时输入令牌并显示登录成功但报错闪退

### ISSUE THREAD

**Issue by ForestWords** [BeyondDimension/SteamTools#2973]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
挂卡时输入令牌并显示登录成功但报错闪退
启动ASF，提示输入两步验证代码，输入后，提示登录成功，之后很快报错闪退

### 🚑 其他信息
2023-10-22 19:18:48|Steam++-3720|INFO|ASF|InitCore() ArchiSteamFarm-custom V5.3.2.4 (source/040969d9-f412-4fb4-9374-1f5c37d92695 | .NET 6.0.12; win10-x64; Microsoft Windows 10.0.19045)
2023-10-22 19:18:48|Steam++-3720|INFO|ASF|InitCore() Copyright © 2015-2022 JustArchiNET
2023-10-22 19:18:48|Steam++-3720|INFO|ASF|Start() 正在启动 IPC 服务……
2023-10-22 19:18:48|Steam++-3720|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://localhost:6242
2023-10-22 19:18:48|Steam++-3720|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-10-22 19:18:48|Steam++-3720|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2023-10-22 19:18:48|Steam++-3720|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\Users\Forest_Fallen_Leaf\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalState\ASF
2023-10-22 19:18:48|Steam++-3720|INFO|ASF|Start() IPC 服务已就绪！
2023-10-22 19:18:48|Steam++-3720|WARN|Forest_Fallen_Leaf|InitStart() 您已在配置文件中禁用此机器人，该实例将不会启动！
2023-10-22 19:22:43|Steam++-3720|INFO|Forest_Fallen_Leaf|Start() 正在启动……
2023-10-22 19:22:43|Steam++-3720|INFO|Forest_Fallen_Leaf|Connect() 正在连接……
2023-10-22 19:22:43|Steam++-3720|INFO|Forest_Fallen_Leaf|OnConnected() 已连接到 Steam！
2023-10-22 19:22:43|Steam++-3720|INFO|Forest_Fallen_Leaf|OnConnected() 登录中……
2023-10-22 19:22:44|Steam++-3720|INFO|ASF|GetUserInput() 
<Forest_Fallen_Leaf> 请输入 Steam 手机验证器上的两步验证代码: 
2023-10-22 19:23:08|Steam++-3720|INFO|Forest_Fallen_Leaf|OnDisconnected() 已从 Steam 断开连接！
2023-10-22 19:23:13|Steam++-3720|INFO|Forest_Fallen_Leaf|OnDisconnected() 重新连接中……
2023-10-22 19:23:13|Steam++-3720|INFO|Forest_Fallen_Leaf|Connect() 正在连接……
2023-10-22 19:23:14|Steam++-3720|INFO|Forest_Fallen_Leaf|OnConnected() 已连接到 Steam！
2023-10-22 19:23:14|Steam++-3720|INFO|Forest_Fallen_Leaf|OnConnected() 登录中……
2023-10-22 19:23:15|Steam++-3720|INFO|Forest_Fallen_Leaf|OnLoggedOn() 成功以 xxxxxxxxxxxxxxxx 的身份登录。
2023-10-22 19:23:15|Steam++-3720|FATAL|ASF|OnUnhandledException() System.ArgumentNullException: Value cannot be null. (Parameter 'webAPIUserNonce')
   at ArchiSteamFarm.Steam.Integration.ArchiWebHandler.Init(UInt64 steamID, EUniverse universe, String webAPIUserNonce, String parentalCode)
   at ArchiSteamFarm.Steam.Bot.OnLoggedOn(LoggedOnCallback callback)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-10-22 19:23:15|Steam++-3720|ERROR|ASF|Exit() 正在以非 0 错误代码退出！
2023-10-22 19:23:15|Steam++-3720|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
2023-10-22 19:23:15|Steam++-3720|INFO|Forest_Fallen_Leaf|Stop() 正在停止……
2023-10-22 19:23:15|Steam++-3720|INFO|Forest_Fallen_Leaf|OnDisconnected() 已从 Steam 断开连接！

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by ForestWords** [comment]
处理器体系结构：64
系统版本号：win10 专业版 22H2
下载渠道：xx网盘
程序版本：2.8.6
是否包含独立运行时：否

**Comment by Dec-w** [comment]
同闪退，在windows商店下载的

**Comment by yingpanwang** [comment]
@ForestWords 最近Steam登录流程发生中断性变更,老版本ASF无法登录了
https://github.com/JustArchiNET/ArchiSteamFarm/issues/3043

**Comment by Li5ngYe** [comment]
System.ArgumentNullException: Value cannot be null. (Parameter 'webAPIUserNonce')它似乎已在 5.4.11.4 中修复https://github.com/JustArchiNET/ArchiSteamFarm/issues/3029   我并没有尝试感兴趣可以尝试ASF官方版本

**Comment by awslnotbad** [comment]
同样的问题，但是我是在更新软件之后出现的，我怀疑是之前装的第三方插件有冲突，删掉第三方插件就好了
