### ISSUE TITLE
🧐[Question] Mac 14.1 m1 使用系统代理无法打开GitHub、stream等网站，报404错误

### ISSUE THREAD

**Issue by TuAgT** [BeyondDimension/SteamTools#2990]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

使用system模式无法加速，GitHub等网站打开后是一行错误代码，baidu等网站打开是空白页。
### 🚑 其他信息

<img width="832" alt="image" src="https://github.com/BeyondDimension/SteamTools/assets/37065019/e71f11ca-e0f1-4be6-8a36-954b0fa93830">

- 处理器体系结构：arm64
- 系统版本号：mac OS Sonoma 14.1
- 下载渠道：Github
- 程序版本：3.0.0-rc2
- 是否包含独立运行时：否

**Comment by TuAgT** [comment]
部分日志
2023-11-05 22:51:37.2433|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-11-05 22:51:40.2454|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

**Comment by TuAgT** [comment]
📔部分日志
2023-11-05 22:51:37.2433|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-11-05 22:51:40.2454|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
