### ISSUE TITLE
🐛[BUG] 确认交易功能停留在登录窗口

### ISSUE THREAD

**Issue by df7x** [BeyondDimension/SteamTools#3062]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 点击确认交易
2. 输入账号密码，点击登录
3. 无响应，并停留在登录窗口

### 📄 日志信息

```
2023-12-03 13:49:48.1352|Error|Toast|.ctor Error | System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.status | LineNumber: 0 | BytePositionInLine: 404.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Serialization.Converters.Int32Converter.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at WinAuth.SteamAuthenticator.get_AccountName()
   at BD.WTTS.UI.ViewModels.SteamTradePageViewModel..ctor(IAuthenticatorDTO& authenticatorDto)

```

### 🖼 截图

![QQ截图20231203135042](https://github.com/BeyondDimension/SteamTools/assets/63087161/288b3818-1821-4d5c-a5be-504f1829edfc)

### 🚑 其他信息

- 处理器体系结构：x64/x86
- 系统版本号：Windows 10.19045.3324
- 下载渠道：Github
- 程序版本：3.0.0-rc.3
- 是否包含独立运行时：无

**Comment by rmbadmin** [comment]
可否检查下令牌详细数据里 mafile 的 json 格式，里面的status字段是否存在以及值是什么，我会尝试下个版本修复，你现在可以尝试移除status这个字段重新导入应该正常
