### ISSUE TITLE
🐛[BUG] steam库存游戏信息编辑时卡退，已修改的信息无法保存

### ISSUE THREAD

**Issue by AbyssVII** [BeyondDimension/SteamTools#3093]
### 🐛 描述
steam库存游戏信息编辑（我使用的时改变steam库内游戏名称这个功能）时会突然卡退，由于卡退，除了已保存的修改过的游戏信息，所有还没有应用的信息修改都不起作用。经过多次尝试，应该是进行了一定数量的游戏信息修改后才会发生卡退现象。

### 📷 复现步骤
1.点击左方菜单栏“库存游戏”功能。
![1](https://github.com/BeyondDimension/SteamTools/assets/127013212/9257b600-a280-44c0-97e1-1d65b82b88dc)
2.点击上方“库”
![1702794914552](https://github.com/BeyondDimension/SteamTools/assets/127013212/2a31267b-b74d-4f58-953d-4e745f8ef685)
3.点击游戏右下方编辑，点击“编辑游戏信息”
![1702794955421](https://github.com/BeyondDimension/SteamTools/assets/127013212/138a30be-1104-4981-b9a4-d9e20145e5be)
![1702794971540](https://github.com/BeyondDimension/SteamTools/assets/127013212/71660546-7f39-4cb8-8650-152bef364259)
4.上面点击“编辑”，然后保存
![1703138727723](https://github.com/BeyondDimension/SteamTools/assets/127013212/c570d961-0273-48ee-ae8d-203b3389b346)

### 📄 日志信息
2023-12-18 13:44:18.9572|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-12-18 13:44:23.6760|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-12-18 13:44:26.7222|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2023-12-18 13:46:50.1705|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

（好像对于我的操作并没记录）

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10.19045.3803
- 下载渠道：Github
- 程序版本：3.0.0-rc.2
- 是否包含独立运行时：不包含

**Comment by rmbadmin** [comment]
编辑后需要去 编辑列表点击应用到Steam才会保存

**Comment by AbyssVII** [comment]
> 编辑后需要去 编辑列表点击应用到Steam才会保存

最后的应用我没截图，我是点了的。我的意思是，就是点击应用的时候会闪退，导致你之前修改的直接没了

**Comment by AbyssVII** [comment]
> 编辑后需要去 编辑列表点击应用到Steam才会保存

我去补下图，谢了
