### ISSUE TITLE
Ubuntu 18.04 运行启动报错

### ISSUE THREAD

**Issue by DaBaiTuu** [BeyondDimension/SteamTools#3122]
详细的描述该问题### 📷 复现步骤
：ubuntu 18.04 无论是直接使用官网命令行下载启动还是 在下载后 启动 Steam++.sh 都出现 报错以及无法启动的问题

![Screenshot from 2024-01-04 14-43-31](https://github.com/BeyondDimension/SteamTools/assets/120782756/4750a587-2c67-4fea-824b-964b6e29a113)

![Screenshot from 2024-01-04 14-44-38](https://github.com/BeyondDimension/SteamTools/assets/120782756/50f1a294-7958-4c7b-baa0-7f6b093c3cf2)
错误信息：
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'BD.Common.VersionTracking2' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/assemblies/e_sqlite3.so: cannot open shared object file: No such file or directory
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/dotnet/shared/Microsoft.NETCore.App/8.0.0/e_sqlite3.so: cannot open shared object file: No such file or directory
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/assemblies/libe_sqlite3.so: cannot open shared object file: No such file or directory
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/dotnet/shared/Microsoft.NETCore.App/8.0.0/libe_sqlite3.so: cannot open shared object file: No such file or directory
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/assemblies/e_sqlite3: cannot open shared object file: No such file or directory
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/dotnet/shared/Microsoft.NETCore.App/8.0.0/e_sqlite3: cannot open shared object file: No such file or directory
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/assemblies/libe_sqlite3: cannot open shared object file: No such file or directory
/home/dongsongb/Downloads/Steam _v3.0.0-rc.3_linux_x64/dotnet/shared/Microsoft.NETCore.App/8.0.0/libe_sqlite3: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at BD.WTTS.GlobalDllImportResolver.Delegate(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at SQLite.SQLiteConnection..cctor()
   --- End of inner exception stack trace ---
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
   at BD.Common.Repositories.Abstractions.Repository.get_ConnectionSync()
   at BD.Common.Services.Implementation.PreferencesPlatformServiceImpl..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at BD.Common.Services.IPreferencesPlatformService.get_Instance()
   at BD.Common.VersionTracking2.InitVersionTracking()
   at BD.Common.VersionTracking2..cctor()
   --- End of inner exception stack trace ---
   at BD.Common.VersionTracking2.Track()
   at BD.WTTS.UI.Views.Windows.AppSplashScreen.<>c.<<FluentAvalonia-UI-Windowing-IApplicationSplashScreen-RunTasks>b__14_0>d.MoveNext()
--- End of stack trace from previous location ---
   at FluentAvalonia.UI.Windowing.SplashScreenContext.RunJobs()
   at FluentAvalonia.UI.Windowing.AppWindow.OnOpened(EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime2.Start(String[] args)
   at BD.WTTS.Program.StartUIApplication()
   at BD.WTTS.Startup.<ConfigureCommands>b__0_12()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by Mossimos** [comment]
目前 初步排查 是 dotnet 不兼容旧版本系统 可以使用 2.8.6
