### ISSUE TITLE
🐛[BUG] Gravatar加速无法正常使用

### ISSUE THREAD

**Issue by trimness4264** [BeyondDimension/SteamTools#3158]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）
### 🐛 描述
gravatar加速无法正常使用
### 📷 复现步骤
1. 启动watt toolkit的“公共cdn”加速 

### 📄 日志信息
```
2024-01-30 16:48:28.0998|Error|BD.WTTS.Services.Implementation.RequestLoggingMiddleware|GET https://gravatar.com/profile responded 502 in 1407.9109 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (gravatar.loli.net:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---
```

### 🖼 截图
![PixPin_2024-01-30_16-56-38](https://github.com/BeyondDimension/SteamTools/assets/100410797/f14a7fe0-04f2-4f7f-af6c-796947ffce9a)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 22H2 22621.3085
- 下载渠道：官网
- 程序版本：3.0.0-rc3
- 是否包含独立运行时：是

**Comment by rmbadmin** [comment]
已热更新修复
