### ISSUE TITLE
🐛[BUG] 无法加速，报 StartProxyFail 错误

### ISSUE THREAD

**Issue by hongweipeng** [BeyondDimension/SteamTools#3186]
![image](https://github.com/BeyondDimension/SteamTools/assets/7546325/b9244a82-f7e1-4f9b-8b6b-bae4910bc82c)

报错日志：
```
2024-02-27 18:33:03.5377|Error|Toast|Notify Error | System.TypeInitializationException: The type initializer for 'Windows.UI.Notifications.ToastNotificationManager' threw an exception.
 ---> System.UnauthorizedAccessException: ClassFactory 无法供应请求的类

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at Windows.UI.Notifications.ToastNotificationManager..cctor()
   --- End of inner exception stack trace ---
   at Windows.UI.Notifications.ToastNotificationManager.get__objRef_global__Windows_UI_Notifications_IToastNotificationManagerStatics()
   at Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier(String applicationId)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at BD.WTTS.Services.Implementation.Windows10NotificationServiceImpl.BD.WTTS.Services.INotificationService.Notify(String text, NotificationType notificationType, Boolean autoCancel, String title, Entrance entrance, String requestUri)

```
- 程序版本：3.0.0-rc3

**Comment by Yuyuyuyu-an** [comment]
请看这个issue:https://github.com/BeyondDimension/SteamTools/issues/2872#issue-1898032460

**Comment by hongweipeng** [comment]
貌似与它错误类型都不一样，它是 `BindPortError` ，我的是 `StartProxyFail` 。

另外，补充运行信息
## 🚑 其他信息
处理器体系结构：x64，cpu: i7-7700K
系统版本号：windows10
下载渠道：github release 页面下载的 exe 文件
程序版本：3.0.0-rc3
是否包含独立运行时：应该是没有

**Comment by youfeng-zZZ** [comment]
https://wwt.lanzoum.com/iQuXU1tt6vxa 这个是1.14版本的，我也是这个问题，一模一样，用1.14版本能用，就是这个版本有问题，觉得太久找新一点的版本也行

**Comment by youfeng-zZZ** [comment]
https://steampp.net/这里找nas分流下载会有全部版本都试一下就行

**Comment by hongweipeng** [comment]
> https://wwt.lanzoum.com/iQuXU1tt6vxa 这个是1.14版本的，我也是这个问题，一模一样，用1.14版本能用，就是这个版本有问题，觉得太久找新一点的版本也行

不是官方渠道，不太敢下呀
