### ISSUE TITLE
🐛[BUG] rc5版本macOS无法启动，开启后便闪退

### ISSUE THREAD

**Issue by Polaris-Ye** [BeyondDimension/SteamTools#3244]
### 🐛 描述
rc5版本macOS无法启动

### 📷 复现步骤

1. 
2. 
3. 

### 📄 日志信息
 System.IO.IOException: Permission denied
   Exception_EndOfInnerExceptionStack
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at BD.WTTS.Services.Implementation.HostsFileServiceImpl.HandleHosts(Boolean isUpdateOrRemove, IReadOnlyDictionary`2 hosts)
2024-03-11 09:41:27.3814|Error|IPCMainProcessServiceImpl|[ServerStreamMessageReader][Error] Exception=Operation canceled;LocalPeerName=ipc_jqxmii895765319461; RemotePeerName=ipc_jqxmii895765319461_Accelerator; | System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.InternalReadAsync(Int32 numBytes)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.ReadAsync[T](Int32 byteCount, Func`2 converter)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.GetHeader(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.ReadAsync(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.ServerStreamMessageReader.RunAsync()
2024-03-11 09:42:00.2764|Error|HostsFileS|UpdateHosts catch. | System.UnauthorizedAccessException: UnauthorizedAccess_IODenied_Path, /etc/hosts
 ---> System.IO.IOException: Permission denied
   Exception_EndOfInnerExceptionStack
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at BD.WTTS.Services.Implementation.HostsFileServiceImpl.HandleHosts(Boolean isUpdateOrRemove, IReadOnlyDictionary`2 hosts)
2024-03-11 09:42:02.2386|Error|IPCMainProcessServiceImpl|[ServerStreamMessageReader][Error] Exception=Operation canceled;LocalPeerName=ipc_kwkdzm910624619722; RemotePeerName=ipc_kwkdzm910624619722_Accelerator; | System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.InternalReadAsync(Int32 numBytes)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.ReadAsync[T](Int32 byteCount, Func`2 converter)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.GetHeader(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.ReadAsync(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.ServerStreamMessageReader.RunAsync()
2024-03-11 09:42:10.1798|Error|HostsFileS|UpdateHosts catch. | System.UnauthorizedAccessException: UnauthorizedAccess_IODenied_Path, /etc/hosts
 ---> System.IO.IOException: Permission denied
   Exception_EndOfInnerExceptionStack
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at BD.WTTS.Services.Implementation.HostsFileServiceImpl.HandleHosts(Boolean isUpdateOrRemove, IReadOnlyDictionary`2 hosts)
2024-03-11 09:42:12.7194|Error|IPCMainProcessServiceImpl|[ServerStreamMessageReader][Error] Exception=Operation canceled;LocalPeerName=ipc_apetqk911633219742; RemotePeerName=ipc_apetqk911633219742_Accelerator; | System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.InternalReadAsync(Int32 numBytes)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.ReadAsync[T](Int32 byteCount, Func`2 converter)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.GetHeader(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.ReadAsync(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.ServerStreamMessageReader.RunAsync()

-->

### 🚑 其他信息

- 处理器体系结构：arm
- 系统版本号： macOS Monterey 14.3.1
- 下载渠道：Github
- 程序版本：3.0rc5

**Comment by Eccentric11** [comment]
我的情况是能打开，但是不能点程序图标，再次点击就会闪退
m1芯片
macOS 13.5.1
百度云下载
版本号：3.0rc5

**Comment by Mossimos** [comment]
该日志看起来是操作host 无权限 是不是开启了启动自动加速
