### ISSUE TITLE
🐛[BUG] Archlinux 环境下点击网络加速后卡死

### ISSUE THREAD

**Issue by shenyaoguan** [BeyondDimension/SteamTools#3280]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在KDE Plasma6 的环境下，点击网络加速的时候会导致窗口卡死，但是进程任然运行，在hosts修改模式下没有成功使hosts得到修改。如果强制用kill命令杀死进程后会导致KDE自身的菜单栏卡死

### 📷 复现步骤

1. 在AUR中下载watt-toolkit-bin 包，并安装
2. 打开后设置网络加速自动启动与自动加速，我加速了steam, DNS 和 网盘服务
3. 重启后便会出现这些错误

### 📄 日志信息

2024-03-25 22:12:26.7983|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-03-25 22:12:32.8815|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-03-25 22:12:35.9008|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-03-25 22:30:43.0018|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/115793922/10e56012-9b7f-4a3a-9f06-0b9f87b0ea13)

### 🚑 其他信息

- 处理器体系结构： x86_64
- 系统版本号：Arch Linux  Kernel: 6.8.1-arch1-1 

- 下载渠道： AUR
- 程序版本：3.0.0.rc.7-1
- 是否包含独立运行时： 否

**Comment by MangMax** [comment]
windows11同样有这个问题
![image](https://github.com/BeyondDimension/SteamTools/assets/68525017/3d95bdb6-0f36-4fd3-87df-24d968883a3f)

**Comment by Dangerise** [comment]
+1, 操作环境 gnome , 发行版为 endeavors os  (based on arch)， 同样来自aur

**Comment by CodyJWang** [comment]
+1, x11, Archlinux, 6.8.2-zen2-1-zen, 同样来自aur

**Comment by Lengyue57** [comment]
+1, ArchLinux, Hyprland, 也一样是aur
使用 ps 命令也没有发现类似 watt 或 steam 之类的字眼

**Comment by cmachsocket** [comment]
+1 ArchLinux , Wayland ,aur
强制杀死没有导致kde6卡死

**Comment by Mossimos** [comment]
看看是不是这个问题导致的

https://github.com/BeyondDimension/SteamTools/issues/3331#issuecomment-2095365914

**Comment by cmachsocket** [comment]
> 看看是不是这个问题导致的
> 
> [#3331 (comment)](https://github.com/BeyondDimension/SteamTools/issues/3331#issuecomment-2095365914)

感谢，确实是这个问题
