### ISSUE TITLE
🐛[BUG] id-cdn.twitch.tv无法加速

### ISSUE THREAD

**Issue by 22858** [BeyondDimension/SteamTools#3288]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

使用twitch第三方登录时发现网页没有正确加载，后来发现是id-cdn.twitch.tv的连接出了问题，连接超时了

### 📷 复现步骤

1. 打开加速
2. 打开id-cdn.twitch.tv下的某个文件
3. 页面显示：
```
Request:Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (HTTP connection to 128.242.245.212 timed out.) (HTTP connection to 128.242.245.212 timed out.) (id-cdn.twitch.tv:443)
```
里面显示的IP地址每次都不一样，但是每次打开都是超时。

### 📄 日志信息

```
2024-03-30 20:59:38.2332|Error|BD.WTTS.Services.Implementation.RequestLoggingMiddleware|GET https://id-cdn.twitch.tv/images/favicon.png responded 502 in 10620.5556 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (HTTP connection to 67.228.102.32 timed out.) (id-cdn.twitch.tv:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (HTTP connection to 67.228.102.32 timed out.)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.TimeoutException: HTTP connection to 67.228.102.32 timed out.<---

   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken) | 
```

### 🖼 截图

无

### 🚑 其他信息

- 处理器体系结构：x86
- 系统版本号：Windows 11 23H2 22631.2338
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.7
- 是否包含独立运行时：不包含 fde

**Comment by rmbadmin** [comment]
已热更新修复
