### ISSUE TITLE
🐛[BUG] 3.0.0存在内存泄漏

### ISSUE THREAD

**Issue by 2540709491** [BeyondDimension/SteamTools#3326]
## 已认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现最新版本类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经使用最新版，问题突然存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

点击加速,过一会内存占用异常
![1](https://github.com/BeyondDimension/SteamTools/assets/102959142/fa635679-0a2b-43e2-8a55-58c4f77a3377)

### 📷 复现步骤
同上

### 📄 日志信息

2024-05-01 17:53:56.5379|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-05-01 21:08:50.6366|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-05-01 21:16:48.3055|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-05-01 21:16:51.9094|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-05-01 21:16:54.9171|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-05-01 21:16:57.9271|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-05-01 21:26:14.7679|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-05-01 21:26:17.7828|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🖼 截图
同上上

### 🚑 其他信息

- 处理器体系结构：x64 
- 系统版本号：Windows 11 23H2.22631.3347(see winver) 
- 下载渠道： 蓝奏云网盘 
- 程序版本：3.0.0
- 是否包含独立运行时：不包含

**Comment by bowen08** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/109715829/50078ad0-de6c-4c45-9d67-eba658d3336e)
太离谱了，就在流量统计页面从几百 MB 涨到 1.6 GB

**Comment by rmbadmin** [comment]
> ![image](https://private-user-images.githubusercontent.com/109715829/344404509-50078ad0-de6c-4c45-9d67-eba658d3336e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2ODIyNzIsIm5iZiI6MTcxOTY4MTk3MiwicGF0aCI6Ii8xMDk3MTU4MjkvMzQ0NDA0NTA5LTUwMDc4YWQwLWRlNmMtNGM0NS05ZDY3LWViYTY1OGQzMzM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxNzI2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzlmMzJmNzhmMTM5MGIxZGE1NWUwZGYxNThhY2E3YzQ0ZDU2OWE2ZjE3ZjU5YzI2Zjk1OTk3NTNkMDJiNzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N2wWroX100XAcKLiNbxogcY851ALTl6wW7P7asF4zIE) 太离谱了，就在流量统计页面从几百 MB 涨到 1.6 GB

目前只知道问题大概率是来源于图表，但是并不能在我这稳定复现，一个可以稳定不触发的方法即是开了加速后直接最小化程序到托盘，这样UI部分都会暂停，也就不会因为图表造成内存泄露

**Comment by afetera** [comment]
> > ![image](https://private-user-images.githubusercontent.com/109715829/344404509-50078ad0-de6c-4c45-9d67-eba658d3336e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2ODIyNzIsIm5iZiI6MTcxOTY4MTk3MiwicGF0aCI6Ii8xMDk3MTU4MjkvMzQ0NDA0NTA5LTUwMDc4YWQwLWRlNmMtNGM0NS05ZDY3LWViYTY1OGQzMzM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxNzI2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzlmMzJmNzhmMTM5MGIxZGE1NWUwZGYxNThhY2E3YzQ0ZDU2OWE2ZjE3ZjU5YzI2Zjk1OTk3NTNkMDJiNzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N2wWroX100XAcKLiNbxogcY851ALTl6wW7P7asF4zIE) 太离谱了，就在流量统计页面从几百 MB 涨到 1.6 GB
> 
> 目前只知道问题大概率是来源于图表，但是并不能在我这稳定复现，一个可以稳定不触发的方法即是开了加速后直接最小化程序到托盘，这样UI部分都会暂停，也就不会因为图表造成内存泄露
>

> 长时间挂后台试试呢？我经常忘记关闭watt加速功能只关闭了窗口没有退出托盘，然后隔天就发现watt占用了超乎想象的内存大小,这个版本肯定有内存泄露。
![屏幕截图 2024-08-22 201519](https://github.com/user-attachments/assets/a6c818d9-8d9a-494d-a6d6-375c1dd1bcba)
