### ISSUE TITLE
🐛[BUG] 令牌导入后无法进行重命名等操作

### ISSUE THREAD

**Issue by Kelcoin** [BeyondDimension/SteamTools#3394]
### 🐛 描述
部分令牌导入后没有进行重命名等操作的按钮，软件退出重启或导出再导入也一样

### 📷 复现步骤
1. 导入谷歌账号令牌

### 📄 日志信息
```
2024-07-09 09:55:34.3267|Error|Toast|GenerateCode Error | WinAuth.WinAuthBase32DecodingException: Illegal character: 0
   at WinAuth.Base32.Decode(String encoded)
   at WinAuth.GoogleAuthenticator.Enroll(String b32key)
   at BD.WTTS.UI.ViewModels.AuthenticatorGeneralImportPageViewModel.GenerateCode()
2024-07-09 10:00:34.4869|Error|Toast|GenerateCode Error | WinAuth.WinAuthBase32DecodingException: Illegal character: 9
   at WinAuth.Base32.Decode(String encoded)
   at WinAuth.GoogleAuthenticator.Enroll(String b32key)
   at BD.WTTS.UI.ViewModels.AuthenticatorGeneralImportPageViewModel.GenerateCode()
2024-07-09 10:00:34.9257|Error|Toast|GenerateCode Error | WinAuth.WinAuthBase32DecodingException: Illegal character: 9
   at WinAuth.Base32.Decode(String encoded)
   at WinAuth.GoogleAuthenticator.Enroll(String b32key)
   at BD.WTTS.UI.ViewModels.AuthenticatorGeneralImportPageViewModel.GenerateCode()
2024-07-09 10:00:45.7151|Error|Toast|GenerateCode Error | WinAuth.WinAuthBase32DecodingException: Illegal character: 9
   at WinAuth.Base32.Decode(String encoded)
   at WinAuth.GoogleAuthenticator.Enroll(String b32key)
   at BD.WTTS.UI.ViewModels.AuthenticatorGeneralImportPageViewModel.GenerateCode()
2024-07-09 10:00:47.0872|Error|Toast|GenerateCode Error | WinAuth.WinAuthBase32DecodingException: Illegal character: 9
   at WinAuth.Base32.Decode(String encoded)
   at WinAuth.GoogleAuthenticator.Enroll(String b32key)
   at BD.WTTS.UI.ViewModels.AuthenticatorGeneralImportPageViewModel.GenerateCode()
2024-07-09 10:00:48.5689|Error|Toast|GenerateCode Error | WinAuth.WinAuthBase32DecodingException: Illegal character: 9
   at WinAuth.Base32.Decode(String encoded)
   at WinAuth.GoogleAuthenticator.Enroll(String b32key)
   at BD.WTTS.UI.ViewModels.AuthenticatorGeneralImportPageViewModel.GenerateCode()
```

### 🖼 截图
![image](https://github.com/BeyondDimension/SteamTools/assets/10922375/ae484417-85fa-412c-90ec-7a441c4a20a5)

### 🚑 其他信息

- 处理器体系结构： x64 
- 系统版本号： Windows 22631.3810 
- 下载渠道： 微软商店 
- 程序版本： 3.0.0-rc.8

**Comment by yingpanwang** [comment]
用来导入令牌的值确认是正确的吗? 正常来说应该是 base32 编码的

**Comment by Kelcoin** [comment]
> 用来导入令牌的值确认是正确的吗? 正常来说应该是 base32 编码的

看到回复又去试了下，发现应该是默认的名字太长导致重命名等按钮被挤掉了。。。我左右拉伸窗口能在特定分辨率下看到半个重命名按钮，将其重命名成短的之后就正常了
![image](https://github.com/BeyondDimension/SteamTools/assets/10922375/13815294-ecf9-4a91-91c1-1040db9db6a2)
