### ISSUE TITLE
🐛[BUG] UI渲染错误

### ISSUE THREAD

**Issue by xiangtou** [BeyondDimension/SteamTools#3395]
### 🐛 描述

UI渲染有问题，背景渲染为黑色，左上角标题文字乱码，右上角出现双重按钮，其他功能正常

### 📷 复现步骤

1. 安装Windows10 19045.4170版本
2. 在微软商店安装Watt Toolkit
3. 打开软件

### 📄 日志信息

```
2024-07-09 13:00:27.1373|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```

### 🖼 截图

![屏幕截图 2024-07-09 141017](https://github.com/BeyondDimension/SteamTools/assets/113241483/eb150799-fcdb-4135-b95b-e3d0feef81f6)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows10.19045.4170
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.8 for Windows Desktop Bridge (x64)
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
调整背景透明材质与透明度即可
