### ISSUE TITLE
🐛[BUG] 成就管理在archlinux aur包版本不可用

### ISSUE THREAD

**Issue by peter6riffin** [BeyondDimension/SteamTools#3403]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
无法正常使用成就管理功能 提示"文件或者文件夹 /usr/lib/watt-toolkit/Steam++.sh 不存在。"

### 📷 复现步骤

1. aur安装watt-toolkit-git或者watt-toolkit-bin
2. 打开watt toolkit使用成就管理

### 📄 日志信息
2024-07-13 08:21:33.7608|Error|Toast|GetConfirmations Error | WinAuth.WinAuthInvalidRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WinAuth.SteamClient.RequestAsync[T](String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout, Boolean isProtobuf)
   --- End of inner exception stack trace ---
   at WinAuth.SteamClient.RequestAsync[T](String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, Int32 timeout, Boolean isProtobuf)
   at WinAuth.SteamClient.GetConfirmations()
   at BD.WTTS.UI.ViewModels.SteamTradePageViewModel.GetConfirmations(SteamClient steamClient)
2024-07-13 08:22:22.1947|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-07-13 08:22:34.6264|Error|SteamworksWebApiS|SendAsync fail, requestUri: https://steam-chat.com/miniprofile/1248462575/json |requestUri=https://steam-chat.com/miniprofile/1248462575/json System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.HttpClientExtensions.SendAsync[T](HttpClient client, ILogger logger, JsonSerializer jsonSerializer, Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, JsonImplType jsonImplType, JsonSerializerOptions s_options, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken)
2024-07-13 21:49:12.5371|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-07-13 21:49:34.3579|Error|SteamworksWebApiS|SendAsync fail, requestUri: https://steam-chat.com/miniprofile/1248462575/json |requestUri=https://steam-chat.com/miniprofile/1248462575/json System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.HttpClientExtensions.SendAsync[T](HttpClient client, ILogger logger, JsonSerializer jsonSerializer, Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, JsonImplType jsonImplType, JsonSerializerOptions s_options, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken)
2024-07-13 22:26:50.4363|Error|IPCMainProcessServiceImpl|[ServerStreamMessageReader][Error] Exception=Operation canceled;LocalPeerName=ipc_iklrzs34260852262; RemotePeerName=ipc_iklrzs34260852262_Accelerator; | System.IO.IOException: Operation canceled
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.InternalReadAsync(Int32 numBytes)
   at dotnetCampus.Ipc.Utils.IO.AsyncBinaryReader.ReadAsync[T](Int32 byteCount, Func`2 converter)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.GetHeader(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.IpcMessageConverter.ReadAsync(Stream stream, Byte[] messageHeader, ISharedArrayPool sharedArrayPool)
   at dotnetCampus.Ipc.Internals.ServerStreamMessageReader.RunAsync()

### 🖼 截图

![图片](https://github.com/user-attachments/assets/b132a1b7-eb13-45f7-b842-e491f9a5b9e9)

### 🚑 其他信息

- 处理器体系结构： x64
- 系统版本号：Arch Linux
- 下载渠道：Aur
- 程序版本：3.0.0-rc.9
- 是否包含独立运行时：不包含

**Comment by arenekosreal** [comment]
我是 aur 的维护者，这是我打包时的问题。目前 watt-toolkit-bin 已经修正这个问题并上传到 aur，watt-toolkit-git 正在测试编译中，通过后将上传到 aur
