### ISSUE TITLE
🐛[BUG] macOS下软件在屏幕外崩溃

### ISSUE THREAD

**Issue by felinefeather** [BeyondDimension/SteamTools#3408]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

系统 macOS Monterey 12.7.5

软件不在当前屏幕时，可能在1~5分钟内发生崩溃；软件或系统未产生log外其它提示

### 📄 日志信息

你的日志内容
Your log content
```
2024-07-20 22:00:36.4835|Error|SteamworksWebApiS|SendAsync fail, requestUri: https://steam-chat.com/miniprofile/884191145/json |requestUri=https://steam-chat.com/miniprofile/884191145/json System.Net.Http.HttpRequestException: Connection refused (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.HttpClientExtensions.SendAsync[T](HttpClient client, ILogger logger, JsonSerializer jsonSerializer, Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, JsonImplType jsonImplType, JsonSerializerOptions s_options, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken)
2024-07-20 22:00:36.5811|Error|SteamworksWebApiS|SendAsync fail, requestUri: https://steam-chat.com/miniprofile/1177509110/json |requestUri=https://steam-chat.com/miniprofile/1177509110/json System.Net.Http.HttpRequestException: Connection refused (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.HttpClientExtensions.SendAsync[T](HttpClient client, ILogger logger, JsonSerializer jsonSerializer, Boolean isCheckHttpUrl, String requestUri, Func`1 requestFactory, String accept, Action`1 handlerResponse, Action`1 handlerResponseByIsNotSuccessStatusCode, JsonImplType jsonImplType, JsonSerializerOptions s_options, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken)

```

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：macOS Monterey 12
- 下载渠道：官网
- 程序版本：3.0.0-rc.9 for macOS(x64)
- 是否包含独立运行时：否

**Comment by codebysandwich** [comment]
macos 发现在菜单栏启动加速不会崩溃，在程序主界面启动反而会崩溃
