### ISSUE TITLE
🐛[BUG] twitch加速出现错误

### ISSUE THREAD

**Issue by 22858** [BeyondDimension/SteamTools#3429]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

使用twitch进行第三方登录时，发现网页没有正确加载，一直白屏

### 📷 复现步骤

1. 打开加速
2. 选择twitch登录
3. 白屏

### 📄 日志信息

```
2024-08-05 16:07:05.4475|Error|BD.WTTS.Services.Implementation.RequestLoggingMiddleware|GET https://fonts.googleapis.com/css2 responded 502 in 978.497 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (fonts.loli.net:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

 ---> (Inner Exception #2) System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

 ---> (Inner Exception #3) System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

 ---> (Inner Exception #4) System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

 ---> (Inner Exception #5) System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectAsync(SocketsHttpConnectionContext context, IPEndPoint ipEndPoint, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)<---

   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken) | 
```

### 🖼 截图

![图片](https://github.com/user-attachments/assets/45f12842-3000-4ffb-9c7c-cf569add20dc)

### 🚑 其他信息

- 处理器体系结构：x86
- 系统版本号：Windows 11 23H2 22631.2338
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.8
- 是否包含独立运行时：不包含 fde

**Comment by 22858** [comment]
顺便，今天github加速不了了，还连个log都没有

**Comment by rmbadmin** [comment]
看日志只有看到 谷歌字体库的加速失效，尝试热更新修复了， github和twitch我这边访问测试都正常
