### ISSUE TITLE
🐛[BUG] 网络加速无效果且无法停止

### ISSUE THREAD

**Issue by mscgzs12** [BeyondDimension/SteamTools#3443]
## 请认真检查以下清单中的每一项
- [√ ] 已经搜索过，没有发现类似的 issue
- [ √] 已经搜索过文档，没有发现相关内容
- [√ ] 已经尝试使用过最新版，问题依旧存在
- [√ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
版本3.0.0-rc9
开启"启动时自动开启加速" 设置"启动时默认打开页面"为"网络加速"
打开软件时网络加速自动启动,没有加速效果,右上角加速计时不动,点击"停止加速"出现如下错误:
![屏幕截图 2024-08-14 215908](https://github.com/user-attachments/assets/fd45858f-dd1b-48dd-8e12-3596b4351f62)
使用四种加速模式均出现此问题

不能及时回复，见谅

### 📷 复现步骤

https://github.com/user-attachments/assets/2b992d67-1965-4832-b3fc-b39bcb8710f7

### 📄 日志信息

```
2024-08-14 17:12:12.8445|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:12:15.1084|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:12:18.9806|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:12:26.2763|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:12:33.5012|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:12:38.4531|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:14:44.7559|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:15:08.4533|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:16:07.7203|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 17:41:22.6535|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 21:44:16.7357|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 21:52:36.6032|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 21:58:54.5880|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-14 22:09:16.3486|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.SHA256.HashData(Byte[] source)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)

```
log文件:
[nlog-all-2024-08-14.log](https://github.com/user-attachments/files/16614446/nlog-all-2024-08-14.log)

-->

### 🖼 截图
1.
![屏幕截图 2024-08-14 221723](https://github.com/user-attachments/assets/f5256b26-e283-480e-b31f-0e24e3906f6e)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：见截图1
- 下载渠道：官网 
- 程序版本：3.0.0-rc9
- 是否包含独立运行时：无

**Comment by mscgzs12** [comment]
重装后解决，或许是小概率问题
