### ISSUE TITLE
🧐[Question] 最近使用时，无法安装证书

### ISSUE THREAD

**Issue by Shoiyu7746** [BeyondDimension/SteamTools#3453]
## 请认真检查以下清单中的每一项
- [ ✓] 已经搜索过，没有发现类似的 issue
- [ ✓] 已经搜索过文档，没有发现相关内容
- [ ✓] 已经尝试使用过最新版，问题依旧存在
- [ ✓] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
安装证书时，显示无法安装CA证书，打开证书所在文件夹，并没有找到证书

### 🚑 其他信息
<img width="855" alt="截屏2024-08-21 下午9 11 56" src="https://github.com/user-attachments/assets/6848f5a5-65d1-4e3e-af22-6006251ef43b">
<img width="1072" alt="截屏2024-08-21 下午9 11 42" src="https://github.com/user-attachments/assets/7fdab9b8-fee8-4f34-8363-30ce6a008664">
<img width="1072" alt="截屏2024-08-21 下午9 11 36" src="https://github.com/user-attachments/assets/c7d96b18-ca9a-4fad-b7ca-79c8dbeaec90">

- 处理器体系结构：arm64
- 系统版本号：macOS Sequoia 15.1 beta2
- 下载渠道：Github
- 程序版本：3.0.0-rc9
- 是否包含独立运行时：是（吧？）

**Comment by Mossimos** [comment]
https://steampp.net/liunxSetupCer
在 Watt Toolkit 的设置 - 通用设置 - 存储空间 - 打开 AppData 目录中的 Plugins/Accelerator 目录下

**Comment by Shoiyu7746** [comment]
> https://steampp.net/liunxSetupCer 在 Watt Toolkit 的设置 - 通用设置 - 存储空间 - 打开 AppData 目录中的 Plugins/Accelerator 目录下

就是说那里没有啊（
已经尝试用虚拟机安装Windows把证书塞进Plugins/Accelerator 目录下了

**Comment by Mossimos** [comment]
程序日志发一下

**Comment by Shoiyu7746** [comment]
> 程序日志发一下

logs数据是吗？
[nlog-all-2024-08-31.log](https://github.com/user-attachments/files/16823944/nlog-all-2024-08-31.log)

**Comment by Mossimos** [comment]
这个日志说明没有权限操作 Host 文件   你打开日志文件夹 里面有加速的英文的文件夹里面日志发下

**Comment by Shoiyu7746** [comment]
[nlog-all-2024-08-31.log](https://github.com/user-attachments/files/16824004/nlog-all-2024-08-31.log)


> 这个日志说明没有权限操作 Host 文件 你打开日志文件夹 里面有加速的英文的文件夹里面日志发下

**Comment by Mossimos** [comment]
The specified item is no longer valid. It may have been deleted from the keychain.
证书是已经被删除了
你目录下应该是有证书的
![image](https://github.com/user-attachments/assets/86493687-160e-4ae7-b1ac-d089acb73cd2)
在这个目录你找下

**Comment by Shoiyu7746** [comment]
以前没有，后面用虚拟机把证书搞过来就有了

**Comment by Mossimos** [comment]
删除 重启程序 然后点加速应该会自动生成新证书

**Comment by Shoiyu7746** [comment]
好

**Comment by Shoiyu7746** [comment]
并没有

> 删除 重启程序 然后点加速应该会自动生成新证书

**Comment by Mossimos** [comment]
有时间吗 你去官网加交流反馈群 然后在群里找我我远控你电脑看看

**Comment by Shoiyu7746** [comment]
好

**Comment by Mossimos** [comment]
https://github.com/dotnet/announcements/issues/324 等这个问题被微软关闭就能修复这个错误了

**Comment by deathxlent** [comment]
升级完macos 15之后就无法加速了，应该就是上面dotnet证书相关问题
1. 如果是全删除重新安装的话，生成不了证书。
2. 用其他机器生成证书导入的话，一开始可以用，但很快就会像下面这样报错，之后所有的加速测试都变成了error

2024-09-19 17:39:13.341|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HN6OGDOCC2GS.| Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at BD.WTTS.Services.Implementation.CertGenerator.CreateEndCertificate(X509Certificate2 issuerCertificate, X500DistinguishedName subjectName, IEnumerable`1 extraDnsNames, Nullable`1 notBefore, Nullable`1 notAfter, Int32 rsaKeySizeInBits)
   at BD.WTTS.Services.Implementation.CertService.<>c__DisplayClass12_0.<GetOrCreateServerCert>g__GetOrCreateCert|0(ICacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at BD.WTTS.Services.Implementation.CertService.GetOrCreateServerCert(String domain)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass1_0.<UseTls>b__3(TlsHandshakeCallbackContext ctx)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.ServerOptionsCallback(SslStream sslStream, SslClientHelloInfo clientHelloInfo, Object state, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at BD.WTTS.Services.Implementation.TlsInvadeMiddleware.InvokeAsync(ConnectionDelegate next, ConnectionContext context)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()

**Comment by Mossimos** [comment]
macos 15 目前是已知的预览版 不能使用  等待微软修复 底层API改动
要用就降级回 14
