### ISSUE TITLE
🐛[BUG] 库存游戏-编辑游戏信息-保存全部更改到Steam-修改以后一段时间后被还原配置

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#3481]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 编辑《库存游戏》，《编辑游戏信息》"Don't Starve Together Dedicated Server"，《信息》中《名称》修改为"饥荒联机版开服"，并添加《启动项》“launch_preconfigured_servers.bat”
2. 《保存全部更改到Steam》
3. 查看重启以后的Steam界面，如预期显示游戏名称"饥荒联机版开服"与增加了启动项“launch_preconfigured_servers.bat”
4. 运行一段时间Steam
5. 查看Steam《库》界面，恢复成了修改之前的数据

### 📄 日志信息

```
2024-09-11 10:54:06.7257|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-09-11 11:09:27.9231|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-09-11 11:09:49.5032|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```
### 🖼 截图

1. 修改之后的Steam《库》界面
![image](https://github.com/user-attachments/assets/2f3a1fd1-ec07-4e4f-8c8b-bb14763a8931)
2. 过了一段时间的页面
![image](https://github.com/user-attachments/assets/ba0f111c-7192-471e-8989-d14fafcfdbe0)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10.19044.4780
- 下载渠道：Github
- 程序版本：3.0.0-rc.10
- 是否包含独立运行时：未知，预装后的快捷方式，未修改

**Comment by rmbadmin** [comment]
这是一个已知的问题，因为steam会不定期的还原被修改的文件，目前只能出现问题时手动去编辑里在保存一下将修改写入，
后续除了支持每次自动修改外，暂时也没有太好的办法

**Comment by ghost** [comment]
> 这是一个已知的问题，因为steam会不定期的还原被修改的文件，目前只能出现问题时手动去编辑里在保存一下将修改写入， 后续除了支持每次自动修改外，暂时也没有太好的办法

先不管被定期还原的机制，那从Toolkit启动的Steam，起码要检查是否有已经《编辑》的游戏，然后先《保存全部更改到Steam》，再启动Steam
目前情况是，只要被还原以后，再次从Toolkit启动Steam还是被还原的样子，除非手动点击《保存全部更改到Steam》

**Comment by rmbadmin** [comment]
> > 这是一个已知的问题，因为steam会不定期的还原被修改的文件，目前只能出现问题时手动去编辑里在保存一下将修改写入， 后续除了支持每次自动修改外，暂时也没有太好的办法
> 
> 先不管被定期还原的机制，那从Toolkit启动的Steam，起码要检查是否有已经《编辑》的游戏，然后先《保存全部更改到Steam》，再启动Steam 目前情况是，只要被还原以后，再次从Toolkit启动Steam还是被还原的样子，除非手动点击《保存全部更改到Steam》

因为现有的逻辑就是只有保存才会去写入，启动是与这个无关的，我所说的自动修改就是你描述的逻辑

**Comment by ghost** [comment]
> > > 这是一个已知的问题，因为steam会不定期的还原被修改的文件，目前只能出现问题时手动去编辑里在保存一下将修改写入， 后续除了支持每次自动修改外，暂时也没有太好的办法
> > 
> > 
> > 先不管被定期还原的机制，那从Toolkit启动的Steam，起码要检查是否有已经《编辑》的游戏，然后先《保存全部更改到Steam》，再启动Steam 目前情况是，只要被还原以后，再次从Toolkit启动Steam还是被还原的样子，除非手动点击《保存全部更改到Steam》
> 
> 因为现有的逻辑就是只有保存才会去写入，启动是与这个无关的，我所说的自动修改就是你描述的逻辑

好吧，那我关闭issue吧
