### ISSUE TITLE
🐛[BUG] 启用加速的网址都不能访问

### ISSUE THREAD

**Issue by cjiajiaGame** [BeyondDimension/SteamTools#3486]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

当启用任何模式加速时，任何被选中加速的网址都不能访问，并且浏览器中会显示图中的状态。Github和Steam都亦是如此。但是我可以用UU访问steam，而且不开加速就可以访问github。已经检查过Host文件，没有指南中127.0.0.1 xxx的问题。

### 📷 复现步骤

1. 正常启用加速就会这样，无论换那个模式都是这样

### 📄 日志信息
 System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (1.12.12.12:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Ae.Dns.Client.DnsHttpClient.Query(DnsMessage query, CancellationToken token)
   at BD.WTTS.Services.Implementation.DnsDohAnalysisService.Query(Uri dohAddresUri, String hostNameOrAddress, DnsQueryType queryType, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.DnsDohAnalysisService.DohAnalysisDomainIpAsync(String dohAddres, String hostNameOrAddress, Boolean isIPv6, Boolean useCache, CancellationToken cancellationToken)+MoveNext()
   at BD.WTTS.Services.Implementation.DnsDohAnalysisService.DohAnalysisDomainIpAsync(String dohAddres, String hostNameOrAddress, Boolean isIPv6, Boolean useCache, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+MoveNext()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+MoveNext()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken) |

2024-09-16 07:41:37.1559|Error|BD.WTTS.Services.Implementation.RequestLoggingMiddleware|GET https://steamcommunity.com/app/281990/workshop/ responded 502 in 21043.3187 ms
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (1.12.12.12:443) (steamcommunity.com:443)
 ---> System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (1.12.12.12:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Ae.Dns.Client.DnsHttpClient.Query(DnsMessage query, CancellationToken token)
   at BD.WTTS.Services.Implementation.DnsDohAnalysisService.Query(Uri dohAddresUri, String hostNameOrAddress, DnsQueryType queryType, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.DnsDohAnalysisService.DohAnalysisDomainIpAsync(String dohAddres, String hostNameOrAddress, Boolean isIPv6, Boolean useCache, CancellationToken cancellationToken)+MoveNext()
   at BD.WTTS.Services.Implementation.DnsDohAnalysisService.DohAnalysisDomainIpAsync(String dohAddres, String hostNameOrAddress, Boolean isIPv6, Boolean useCache, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+MoveNext()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+MoveNext()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.GetIPEndPointsAsync(DnsEndPoint dnsEndPoint, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken) | 

2024-09-16 07:41:57.5189|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HN6LRDRC8N1A. |ConnectionId=0HN6LRDRC8N1A Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at BD.WTTS.Services.Implementation.FlowAnalyzeStream.ReadAsync(Memory`1 destination, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader reader, Nullable`1 minimumSize, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at BD.WTTS.Services.Implementation.HttpProxyMiddleware.InvokeAsync(ConnectionDelegate next, ConnectionContext context)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()

```

### 🖼 截图

<!--
截图可以贴在这里
Screenshots can be posted here
-->

![屏幕截图 2024-09-16 074334](https://github.com/user-attachments/assets/41692fd5-53a8-4e65-8245-63150623b725)


### 🚑 其他信息

- 处理器体系结构：<!-- x64 / x86 / arm64 --> x64
- 系统版本号：<!-- example Windows 10.19042.844(see winver) / macOS Monterey 12 / Ubuntu 20.04.2 LTS --> Windows 11 23h2
- 下载渠道：<!-- 微软商店 / 官网 / Github / AppStore / xx网盘 --> 蓝奏网盘
- 程序版本：<!-- 2.8.4 --> 3.0.0 rc10
- 是否包含独立运行时：<!-- 文件名中带有 with_runtime 或 不包含 fde --> 没有with_runtime, 不包含fde

**Comment by LengBingYan** [comment]
I started the acceleration, and I can't even open the normal web page.

**Comment by DominicLiang** [comment]
我也遇到这个问题 从昨天开始的 steam页面都打开不了

**Comment by DIOsama2002** [comment]
我也是，从前天开始的

**Comment by letterk** [comment]
![image](https://github.com/user-attachments/assets/d2247732-1040-4bc9-aeda-46380ada2cb2)
现在勉强能打开商店, 之前商店也打不开

**Comment by XYMoYingJun** [comment]
我也是，连接性测试全是error

**Comment by tallpeekaboo** [comment]
这段时间真是多事之秋啊，我用的梯子leensa跑路了
然后steam++也失效了
访问都是报：Request:由于目标计算机积极拒绝，无法连接。 (github.com:443)

**Comment by wjh191** [comment]
我steam商店首页打不开，每次都要停止加速重新加速才行

**Comment by Hikarizon** [comment]
我也是，开了加速反而连steam首页都上不去

**Comment by Mossimos** [comment]
之前版本使用的 1.12.12.12 的 Doh 地址 [DNSPod](https://www.dnspod.cn/products/publicdns) 修改了地址导致 旧值无法使用 需要去 加速设置  代理设置 中 自定义 Doh 地址 随意切换一下修改为正常值

**Comment by Hikarizon** [comment]
> 之前版本使用的 1.12.12.12 的 Doh 地址 [DNSPod](https://www.dnspod.cn/products/publicdns) 修改了地址导致 旧值无法使用 需要去 加速设置 代理设置 中 自定义 Doh 地址 随意切换一下修改为正常值

正常了，非常感谢

**Comment by cjiajiaGame** [comment]
> 之前版本使用的 1.12.12.12 的 Doh 地址 [DNSPod](https://www.dnspod.cn/products/publicdns) 修改了地址导致 旧值无法使用 需要去 加速设置 代理设置 中 自定义 Doh 地址 随意切换一下修改为正常值

ok啊解决了

**Comment by letterk** [comment]
并不是dns的问题, 现在steam社区和市场依然打不开

**Comment by cjiajiaGame** [comment]
> 并不是dns的问题, 现在steam社区和市场依然打不开

换几个都不行吗

**Comment by letterk** [comment]
> > 并不是dns的问题, 现在steam社区和市场依然打不开
> 
> 换几个都不行吗

随便换那个都不行, 上面有我之前发的连通性测试

**Comment by cjiajiaGame** [comment]
> > > 并不是dns的问题, 现在steam社区和市场依然打不开
> > 
> > 
> > 换几个都不行吗
> 
> 随便换那个都不行, 上面有我之前发的连通性测试

要不然你新开一个issue吧

**Comment by letterk** [comment]
改成"dns驱动拦截模式"后正常了, 不打扰了
