### ISSUE TITLE
🐛[BUG] macOS 15.0 无法加速

### ISSUE THREAD

**Issue by fisherwei** [BeyondDimension/SteamTools#3491]
系统升级到 15.0 (24A335) 后无法加速。

尝试：

1. 删除并重新安装证书。
2. 重新给hosts增加读写权限。
3. 在macos系统设置中赋予steam++本地网络权限。

### 📄 日志信息
```
2024-09-21 12:07:28.1979|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HN6PU9JJILKI. |ConnectionId=0HN6PU9JJILKI Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at BD.WTTS.Services.Implementation.CertGenerator.CreateEndCertificate(X509Certificate2 issuerCertificate, X500DistinguishedName subjectName, IEnumerable`1 extraDnsNames, Nullable`1 notBefore, Nullable`1 notAfter, Int32 rsaKeySizeInBits)
   at BD.WTTS.Services.Implementation.CertService.<>c__DisplayClass12_0.<GetOrCreateServerCert>g__GetOrCreateCert|0(ICacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at BD.WTTS.Services.Implementation.CertService.GetOrCreateServerCert(String domain)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass1_0.<UseTls>b__3(TlsHandshakeCallbackContext ctx)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.ServerOptionsCallback(SslStream sslStream, SslClientHelloInfo clientHelloInfo, Object state, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at BD.WTTS.Services.Implementation.TlsInvadeMiddleware.InvokeAsync(ConnectionDelegate next, ConnectionContext context)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
```

```
2024-09-21 12:07:28.1986|Error|NetworkTestService|测试打开 URL 异常 | System.Net.Http.HttpRequestException: net_http_ssl_connection_failed
 ---> System.IO.IOException: net_io_eof
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BD.WTTS.Services.Implementation.NetworkTestService.TestOpenUrlAsync(String url, Func`1 httpClientFunc, CancellationToken cancellationToken)
```

### 🖼 截图

![image](https://github.com/user-attachments/assets/8ed76c41-d132-4996-9846-18675f63ef0c)
![image](https://github.com/user-attachments/assets/63f9c925-1830-457e-9369-730cc5f11b96)
![image](https://github.com/user-attachments/assets/9fa6c909-9776-409b-8b89-e223671565c5)

### 🚑 其他信息

- 处理器体系结构：arm64
- 系统版本号：macOS 15.0
- 下载渠道：Github
- 程序版本：3.0.0-rc.10 for macOS (arm64)

**Comment by Mossimos** [comment]
已经发了公告15系统无法使用了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Fisher ***@***.***>
发送时间: Saturday, September 21, 2024 12:21:48 PM
收件人: BeyondDimension/SteamTools ***@***.***>
抄送: Subscribed ***@***.***>
主题: [BeyondDimension/SteamTools] 🐛[BUG] macOS 15.0 无法加速 (Issue #3491)


系统升级到 15.0 (24A335) 后无法加速。

尝试：

  1.  删除并重新安装证书。
  2.  重新给hosts增加读写权限。
  3.  在macos系统设置中赋予steam++本地网络权限。

📄 日志信息

2024-09-21 12:07:28.1979|Error|Microsoft.AspNetCore.Server.Kestrel|Unhandled exception while processing 0HN6PU9JJILKI. |ConnectionId=0HN6PU9JJILKI Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at BD.WTTS.Services.Implementation.CertGenerator.CreateEndCertificate(X509Certificate2 issuerCertificate, X500DistinguishedName subjectName, IEnumerable`1 extraDnsNames, Nullable`1 notBefore, Nullable`1 notAfter, Int32 rsaKeySizeInBits)
   at BD.WTTS.Services.Implementation.CertService.<>c__DisplayClass12_0.<GetOrCreateServerCert>g__GetOrCreateCert|0(ICacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at BD.WTTS.Services.Implementation.CertService.GetOrCreateServerCert(String domain)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass1_0.<UseTls>b__3(TlsHandshakeCallbackContext ctx)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.ServerOptionsCallback(SslStream sslStream, SslClientHelloInfo clientHelloInfo, Object state, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at BD.WTTS.Services.Implementation.TlsInvadeMiddleware.InvokeAsync(ConnectionDelegate next, ConnectionContext context)
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ListenOptionsExtensions.<>c__DisplayClass0_1.<<UseFlowAnalyze>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()


2024-09-21 12:07:28.1986|Error|NetworkTestService|测试打开 URL 异常 | System.Net.Http.HttpRequestException: net_http_ssl_connection_failed
 ---> System.IO.IOException: net_io_eof
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BD.WTTS.Services.Implementation.NetworkTestService.TestOpenUrlAsync(String url, Func`1 httpClientFunc, CancellationToken cancellationToken)


🖼 截图

image.png (view on web)<https://github.com/user-attachments/assets/8ed76c41-d132-4996-9846-18675f63ef0c>
image.png (view on web)<https://github.com/user-attachments/assets/63f9c925-1830-457e-9369-730cc5f11b96>
image.png (view on web)<https://github.com/user-attachments/assets/9fa6c909-9776-409b-8b89-e223671565c5>

🚑 其他信息

  *   处理器体系结构：arm64
  *   系统版本号：macOS 15.0
  *   下载渠道：Github
  *   程序版本：3.0.0-rc.10 for macOS (arm64)
