### ISSUE TITLE
🐛[BUG] Steam令牌导入点击“确认导入”没反应

### ISSUE THREAD

**Issue by Q2297045667** [BeyondDimension/SteamTools#3494]
### 📄 日志信息
 System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:54:06.8905|Error|Toast|Import Error | System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
>  ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:54:07.0664|Error|Toast|Import Error | System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
>  ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:55:43.3992|Error|Toast|Import Error | System.ArgumentNullException: Value cannot be null. (Parameter 'PhoneImportUuid')
>    at System.ObjectExtensions.Throw(String paramName)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:55:48.9218|Error|Toast|Import Error | System.ArgumentNullException: Value cannot be null. (Parameter 'ImportAuthNewName')
>    at System.ObjectExtensions.Throw(String paramName)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:55:56.8798|Error|Toast|Import Error | System.Text.Json.JsonException: ',' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 410.
>  ---> System.Text.Json.JsonReaderException: ',' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 410.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:56:01.3851|Error|Toast|Import Error | System.Text.Json.JsonException: ',' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 410.
>  ---> System.Text.Json.JsonReaderException: ',' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 410.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:13.5908|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:13.7721|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:13.9763|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:14.1642|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:14.3268|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:14.4809|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:14.6602|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:14.8222|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:14.9782|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:15.1528|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:15.3162|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:15.4964|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:15.6724|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:15.8404|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:16.0206|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:16.1807|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:16.3165|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:16.5323|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:16.7283|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:39.4013|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:40.1977|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:40.4016|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:58:40.5669|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:59:04.9139|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:59:05.6598|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 12:59:05.8120|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:02:07.9832|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:02:08.1356|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:02:08.2976|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:02:08.4461|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:04:39.7599|Error|Toast|Import Error | System.ArgumentNullException: Value cannot be null. (Parameter 'PhoneImportUuid')
>    at System.ObjectExtensions.Throw(String paramName)
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:06:53.1547|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:06:53.3147|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:09:02.5951|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:09:14.2373|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:09:14.9352|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:09:15.1013|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> 2024-09-24 13:09:15.2619|Error|Toast|Import Error | System.ApplicationException: no shared_secret
>    at BD.WTTS.UI.ViewModels.SteamGuardImportPageViewModel.Import()
> -->

### 🚑 其他信息

- 版本	Windows 11 专业工作站版 Insider Preview
- 版本号	Dev
- 安装日期	‎2024/‎8/‎31
- 评估到期日期	‎2025/‎9/‎16 5:16
- 操作系统版本	27695.1000
- 功能包	Windows Feature Experience Pack 1000.26100.19.0

- 下载渠道：Github
- 程序版本：3.0.0-rc.10

**Comment by Q2297045667** [comment]
不清楚是我操作问题还是什么，点击之后完全没有提示

**Comment by rmbadmin** [comment]
选择的令牌文件有问题

**Comment by Q2297045667** [comment]
> 选择的令牌文件有问题

好的，谢谢，但这里还是没有，其实感觉不太对
