### ISSUE TITLE
🐛[BUG] 家庭库共享管理一拖动就闪退

### ISSUE THREAD

**Issue by 1109318404** [BeyondDimension/SteamTools#3505]
家庭库共享管理页面，一拖动顺序就闪退

### 📄 日志信息
2024-09-30 23:28:37.5732|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10 19045.4170
- 下载渠道：微软商店
- 程序版本：3.0.0-rc11

**Comment by Mossimos** [comment]
家庭库共享管理 应该已经失效了  steam 已经删除旧共享库了  新版共享可以自由选择使用的库

**Comment by 1109318404** [comment]
呜呜呜好吧，我周围的人互相不认识都还没用新的
