### ISSUE TITLE
🐛[BUG] 在多屏幕下, 从任务栏右键退出时弹出菜单在错误的位置

### ISSUE THREAD

**Issue by Cjsah** [BeyondDimension/SteamTools#3554]
## 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在上下两个屏幕, 且上面的屏幕为主屏幕时, 在托盘区右键软件图标时
弹出的菜单出现在下面的屏幕上方, 而不是托盘所在的屏幕

### 📷 复现步骤

1. 启动 Watt
2. 点击 Watt右上角的`x`, 此时软件运行在后台, 托盘区存在Watt的图标
3. 右键托盘区的Watt图标

### 📄 日志信息

当天的所有日志就只有一个叫`nlog-all-2024-11-26.log`的文件, 内容如下, 只有三行.
```
2024-11-26 17:20:10.0318|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```

### 🖼 截图
![image](https://github.com/user-attachments/assets/106ecfd8-b42b-4894-91d0-e308740d8796)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号： Windows 11 23H2 22631.4460
- 下载渠道：Github
- 程序版本：3.0.0-rc.11 for Windows (x64)
- 是否包含独立运行时：不清楚, 不过文件夹里有dotnet目录, 没有找到`with_runtime `和`fde`相关的文字

**Comment by rmbadmin** [comment]
这应该是一个Avalonia的bug
