### ISSUE TITLE
🐛[BUG] 使用系统代理会一直请求本地应用的webui端口

### ISSUE THREAD

**Issue by emptylight370** [BeyondDimension/SteamTools#3567]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在使用系统代理模式的时候会一直请求本地应用的webui端口（日志中表现为127.0.0.1:1235/webui/login），然后因为鉴权失败一直返回404。进而在日志中打印出无限的请求失败。
这时系统的手动配置中未勾选“请勿将代理服务器用于本地地址”选项，并且将二级代理转发至本地的AdGuard端口（这个经测试不影响）。
在系统的代理配置中勾选略过本地地址可以缓解。可能是因为网址是/webui/login的原因？

### 📷 复现步骤

1. 使用系统代理模式
2. 连接至二级代理（AdGuard）（可以没有）
3. 启动部分可重现的带有webui的应用（本次受害者为BitComet）
4. 启动代理（此时系统设置中略过本地地址自动关闭）
5. 查看日志中出现大量访问127.0.0.1:1235地址的请求，并且全部失败

### 📄 日志信息

```
2024-12-05 23:29:19.9686|Error|BD.WTTS.Services.Implementation.RequestLoggingMiddleware|POST http://localhost:1235/api/webui/login responded 502 in 5.8741 ms
System.Net.Http.HttpRequestException: Proxy connection failed:  (localhost:1235)
 ---> System.Exception: Proxy connection failed: 
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectHttpProxy(NetworkStream stream, SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectThroughProxyAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at BD.WTTS.Services.Implementation.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken) | 
```

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 23H2 22635.4515
- 下载渠道：GitHub
- 程序版本：3.0.0-rc13
- 是否包含独立运行时：否

**Comment by rmbadmin** [comment]
程序本身不会产生这种请求，系统代理会接管系统默认代理所以本机所有流量可能都会经过程序导致的，建议非必要是不要使用系统代理模式，或者你将localhost加入排除ip
