### ISSUE TITLE
🐛[BUG] Windows商店版本的界面碎掉了

### ISSUE THREAD

**Issue by txf0990** [BeyondDimension/SteamTools#3575]
## 请认真检查以下清单中的每一项
- [ 1] 已经搜索过，没有发现类似的 issue
- [ 1] 已经搜索过文档，没有发现相关内容
- [ 1] 已经尝试使用过最新版，问题依旧存在
- [ 1] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
界面的图标移位，没有文字

### 📷 复现步骤

打开软件就能看到了。。。

### 📄 日志信息

```
2024-12-12 08:53:04.0920|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-12 08:53:07.1931|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-12 08:53:10.1960|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-12 08:53:13.2121|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```

### 🖼 截图

![Screenshot 2024-12-13 120837](https://github.com/user-attachments/assets/34ec5e09-c005-4258-9844-3b1badcc34cf)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：
Edition	Windows 11 Home
Version	23H2
Installed on	‎01/‎12/‎2024
OS build	22631.4602
Experience	Windows Feature Experience Pack 1000.22700.1055.0
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.13 for Windows Desktop Bridge (x64)
- 是否包含独立运行时：
这个不知道，都是微软商店默认的，我从windows start直接打开

**Comment by rmbadmin** [comment]
设置中调整背景透明度或背景透明材质即可
