### ISSUE TITLE
🐛[BUG] rc.13打开“网络加速”标签页后右侧区域完全空白，同时软件卡死无法退出

### ISSUE THREAD

**Issue by VictoireWood** [BeyondDimension/SteamTools#3577]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

使用Github最新版本Steam++_v3.0.0-rc.13_win_x64
电脑
```
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎3/‎24
操作系统内部版本	19045.5247
体验	Windows Feature Experience Pack 1000.19060.1000.0
```
我原来使用的版本是rc.11，加速功能没有发现问题。今天下午先覆盖安装了新的rc.13版本，启动后，启动页面“主页”可以正常活动。点击“网络加速”标签页后，在下图所示的红框区域内是完全空白，同时窗口无法移动、无法最小化，软件内完全卡死，点击任何按钮都没有反应，但是并没有windows的“程序未响应”的提示。

![image](https://github.com/user-attachments/assets/4109932a-f091-4418-b8d1-d3eb4aac431b)

我打开任务栏托盘，右键程序图标，可以弹出如下托盘，但是点击任何选项都没有任何反应，点击“退出”也没有反应，我只能用任务管理器强行退出。

![image](https://github.com/user-attachments/assets/ca9af3cd-6419-4e2c-99f8-1d4a063e7ab4)

之后我又覆盖安装了一遍rc.13版本，结果打卡后进行一样的流程，还是出现一样的反应。最后只能再覆盖安装rc.11的旧版本，加速功能又恢复正常了。

### 📷 复现步骤

1. 覆盖rc.11安装rc.13。
2. 启动rc.13。
3. 点击“网络加速”标签页。

### 📄 日志信息

```
2024-12-13 17:03:16.9873|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:20.0130|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:23.0329|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:26.0475|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:29.0544|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:32.0644|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:35.0701|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:38.0861|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
2024-12-13 17:03:41.0962|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10.19045.5247
- 下载渠道：Github
- 程序版本：rc.13
- 是否包含独立运行时：不包含

**Comment by rmbadmin** [comment]
覆盖升级不完全时，插件与主程序版本不一致会导致这种情况

**Comment by VictoireWood** [comment]
> 覆盖升级不完全时，插件与主程序版本不一致会导致这种情况

您好，请问您指的是网络加速中使用的JS插件和主程序不匹配吗？

**Comment by VictoireWood** [comment]
> 覆盖升级不完全时，插件与主程序版本不一致会导致这种情况

![Image](https://github.com/user-attachments/assets/5003af0b-8248-4ffc-8673-a7a32231e091)

我完全卸载后下载7z的压缩包使用，也会出现这个问题……

**Comment by Altent** [comment]
请检查系统是否有Microsoft.AspNetCore.App 框架的 9.0.0 版本（x64 架构）
<img width="598" alt="Image" src="https://github.com/user-attachments/assets/7799302f-459b-4523-8bb1-0bb81e4c024c" />
如果没有的话请从 https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=9.0.0&arch=x64&rid=win-x64&os=win10这个链接下载并安装，之后再次打开14或13版本应该是可以打开网络加速页面的

**Comment by VictoireWood** [comment]
> 请检查系统是否有Microsoft.AspNetCore.App 框架的 9.0.0 版本（x64 架构） <img alt="Image" width="598" src="https://private-user-images.githubusercontent.com/77523062/411341153-7799302f-459b-4523-8bb1-0bb81e4c024c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk3NzY2NTUsIm5iZiI6MTczOTc3NjM1NSwicGF0aCI6Ii83NzUyMzA2Mi80MTEzNDExNTMtNzc5OTMwMmYtNDU5Yi00NTIzLThiYjEtMGJiODFlNGMwMjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE3VDA3MTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Mzg1YjkyNTlmY2FmNTkwY2UwYWVjYWQzZTk2ZWU0Nzg2YTU4OWYzODQ1YzYwYTU2YTE2ZjdiOWNhM2NlZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n3C8CW-9Ugr1EAp0T0hNiRE4AH2OZsypWGwfPNiZQm0"> 如果没有的话请从 [https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=9.0.0&arch=x64&rid=win-x64&os=win10这个链接下载并安装，之后再次打开14或13版本应该是可以打开网络加速页面的](https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=9.0.0&arch=x64&rid=win-x64&os=win10%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85%EF%BC%8C%E4%B9%8B%E5%90%8E%E5%86%8D%E6%AC%A1%E6%89%93%E5%BC%8014%E6%88%9613%E7%89%88%E6%9C%AC%E5%BA%94%E8%AF%A5%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80%E7%BD%91%E7%BB%9C%E5%8A%A0%E9%80%9F%E9%A1%B5%E9%9D%A2%E7%9A%84)



```
(base) PS C:\Users\s> dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
安装了之后还是打不开……

![Image](https://github.com/user-attachments/assets/a42a93b7-9456-412d-839a-3ea24684995c)
