### ISSUE TITLE
🐛[BUG] windows 11下 x64 2.6.2 ASF无法启动

### ISSUE THREAD

**Issue by darkanthem** [BeyondDimension/SteamTools#774]
### 🐛 描述(Description)
启动后会抛出异常

### 📄 [异常/日志]信息([Exception/Log] Information)
2021-12-11 21:35:55|Steam++-13432|ERROR|ASF|OnASFInitModules() System.MissingMethodException: Method not found: 'Int32 ArchiSteamFarm.Core.Utilities.RandomNext(Int32, Int32)'.
   at ArchiSteamFarm.OfficialPlugins.SteamTokenDumper.SteamTokenDumperPlugin.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ArchiSteamFarm.OfficialPlugins.SteamTokenDumper.SteamTokenDumperPlugin.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass12_1.<OnASFInitModules>b__1()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)

**Comment by AigioL** [comment]
你是用了插件吗？

**Comment by darkanthem** [comment]
> 你是用了插件吗？

没用，我试着下了个ASF的官方版本把插件文件夹覆盖了一下之后好了……
