### ISSUE TITLE
🐛[BUG] 修改ASF.json导致Steam++闪退

### ISSUE THREAD

**Issue by cyb233** [BeyondDimension/SteamTools#793]
### 🐛 描述(Description)
修改ASF.json导致Steam++闪退

### 📷 复现步骤(Steps to Reproduce)

1. 打开ASF
2. 在WebUI关闭IPC并保存
3. 此时Steam++正常提示ASF重启
4. 在ASF.json中删除IPC配置行并保存
5. 此时Steam++提示ASF重启并闪退

未测试修改其他配置文本是否会导致相同问题

### 📄 [异常/日志]信息([Exception/Log] Information)
```log
2021-12-13 22:14:24.8822|Error|ViaFactory|Stopped program because of exception, name: AppDomain, isTerminating: True | System.InvalidOperationException: Bots
   at ArchiSteamFarm.Core.ASF.OnCreatedJsonFile(String name, String fullPath)
   at ArchiSteamFarm.Core.ASF.OnCreatedConfigFile(String name, String fullPath)
   at ArchiSteamFarm.Core.ASF.OnCreatedFile(String name, String fullPath)
   at ArchiSteamFarm.Core.ASF.OnRenamed(Object sender, RenamedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2021-12-13 22:14:24.8822|Error|ViaFactory|Stopped program because of exception, name: AppDomain, isTerminating: True | System.InvalidOperationException: Bots
   at ArchiSteamFarm.Core.ASF.OnDeletedJsonConfigFile(String name, String fullPath)
   at ArchiSteamFarm.Core.ASF.OnDeletedConfigFile(String name, String fullPath)
   at ArchiSteamFarm.Core.ASF.OnDeletedFile(String name, String fullPath)
   at ArchiSteamFarm.Core.ASF.OnRenamed(Object sender, RenamedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2021-12-13 22:14:24.9711|Error|HttpProxyServiceImpl|StopProxy | System.InvalidOperationException: InvalidOperation_EnumFailedVersion
   at Titanium.Web.Proxy.ProxyServer.Stop()
   at System.Application.Services.Implementation.HttpProxyServiceImpl.StopProxy()
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.3
- 系统版本号(OS Version):  Windows 10.19044.1348
- 是否为应用商店版本(Whether it is a Store version):  no

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/39186981/145830174-bfd6ce6e-93b9-4df2-ab4b-14ab3f4f8c08.png)

**Comment by AigioL** [comment]
fix https://github.com/BeyondDimension/SteamTools/commit/88755791b1d63a1611f3deaddbc8bafbe8ee8689

ASF Config 目录内有文件监控，发送改变时且 Bots 为 null 则引发异常导致闪退，未启动 ASF 时 Bots 为 null

https://github.com/BeyondDimension/SteamTools/actions/runs/1573415335

等待此 action 执行完后可下载该提交编译的二进制包测试

**Comment by cyb233** [comment]
> fix [8875579](https://github.com/BeyondDimension/SteamTools/commit/88755791b1d63a1611f3deaddbc8bafbe8ee8689)
> 
> ASF Config 目录内有文件监控，发生改变时且 Bots 为 null 则引发异常导致闪退，未启动 ASF 时 Bots 为 null
> 
> https://github.com/BeyondDimension/SteamTools/actions/runs/1573415335
> 
> 等待此 action 执行完后可下载该提交编译的二进制包测试 @rmbadmin

附加: 编辑时ASF处于运行状态, Bot有一个但处于通过配置文件禁用状态

**Comment by AigioL** [comment]
> > fix [8875579](https://github.com/BeyondDimension/SteamTools/commit/88755791b1d63a1611f3deaddbc8bafbe8ee8689)
> > ASF Config 目录内有文件监控，发生改变时且 Bots 为 null 则引发异常导致闪退，未启动 ASF 时 Bots 为 null
> > https://github.com/BeyondDimension/SteamTools/actions/runs/1573415335
> > 等待此 action 执行完后可下载该提交编译的二进制包测试 @rmbadmin
> 
> 附加: 编辑时ASF处于运行状态, Bot有一个但处于通过配置文件禁用状态

重启是调用了停止后再调用启动的，应该是这个监听正好在停止后启动前执行了导致抛出异常
这个提交应该也能避免这种情况发生

**Comment by AigioL** [comment]
因为应用程序的生命周期不一样，控制台程序与目前有UI且嵌入进来的程序不一样

FileSystemWatcher 这个字段
https://github.com/BeyondDimension/ArchiSteamFarm/blob/38e3619c914d169fbeb851ac9fbd3a4adce43621/ArchiSteamFarm/Core/ASF.cs#L84

在控制台程序中，停止时退出了程序，所以这个监听是被释放了的，启动时又重新初始化了
但是在 Steam++ 中停止时并没有释放这个字段，是否应该在 Stop 函数中将 FileSystemWatcher 释放比较符合原版的逻辑 @rmbadmin

**Comment by AigioL** [comment]
fix v2.6.4
