### ISSUE TITLE
使用ASF功能时频繁报错

### ISSUE THREAD

**Issue by duoduo6666** [BeyondDimension/SteamTools#796]
使用ASF功能时频繁报错

2021-12-14 08:20:55|Steam++-21772|INFO|ginde|FarmMultiple() 正在挂卡：616750, 1392060, 566560, 1038740, 844930, 485670, 1007350, 335210, 567980, 1093910, 668630, 1377360, 614460, 1307090, 576480, 541920, 575750, 575580, 386110, 596810, 551930, 453670
2021-12-14 08:20:55|Steam++-21772|INFO|ginde|FarmHours() 仍在挂卡：616750, 1392060, 566560, 1038740, 844930, 485670, 1007350, 335210, 567980, 1093910, 668630, 1377360, 614460, 1307090, 576480, 541920, 575750, 575580, 386110, 596810, 551930, 453670
2021-12-14 08:22:26|Steam++-21772|FATAL|ASF|OnUnobservedTaskException() System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2021-12-14 08:22:26|Steam++-21772|FATAL|ASF|OnUnobservedTaskException() System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2021-12-14 08:22:26|Steam++-21772|FATAL|ASF|OnUnobservedTaskException() System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)

**Comment by wordlesswind** [comment]
### 🐛 描述(Description)


ASF 控制台中输出了错误信息

### 📷 复现步骤(Steps to Reproduce)


N/A

### 📄 [异常/日志]信息([Exception/Log] Information)
```
2022-01-14 14:22:55|Steam++-19528|FATAL|ASF|OnUnobservedTaskException() System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2022-01-14 14:35:38|Steam++-19528|FATAL|ASF|OnUnobservedTaskException() System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.4
- 系统版本号(OS Version): Windows 11 Version 21H2 (Build 22000.434)
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)


N/A

**Comment by cherinyy** [comment]
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SteamKit2.WebAPI.AsyncInterface.CallAsyncInternal(HttpMethod method, String func, Int32 version, Dictionary`2 args, String expectedFormat)
   at SteamKit2.WebAPI.AsyncInterface.CallAsync(HttpMethod method, String func, Int32 version, Dictionary`2 args)
   at ArchiSteamFarm.Steam.Integration.ArchiWebHandler.<>c__DisplayClass67_0.<<Init>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ArchiSteamFarm.Steam.Integration.ArchiWebHandler.WebLimitRequest[T](Uri service, Func`1 function)
   at ArchiSteamFarm.Steam.Integration.ArchiWebHandler.Init(UInt64 steamID, EUniverse universe, String webAPIUserNonce, String parentalCode)
```
