### ISSUE TITLE
🐛[BUG] 移动网 HOST代理 steam连接不上

### ISSUE THREAD

**Issue by mrwjh** [BeyondDimension/SteamTools#949]
### 🐛 描述(Description)

移动网 HOST代理 steam连接不上，但单位的网好像就没问题，服了， log如下

### 📄 [异常/日志]信息([Exception/Log] Information)
2022-01-29 17:21:35.8281|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.4
- 系统版本号(OS Version): Windows 11 22000.469
- 是否为应用商店版本(Whether it is a Store version): yes

**Comment by yzqdev** [comment]
我也用的移动网,一样的问题,时好时坏,估计是移动的锅了

**Comment by WuYou-666** [comment]
我的移动网能连上，但部分网页会出现404
