### ISSUE TITLE
🐛[BUG] 开启Host代理模式后访问Github部分页面404

### ISSUE THREAD

**Issue by muyangplus** [BeyondDimension/SteamTools#952]
### 🐛 描述(Description)

开启Host代理模式后访问Github部分页面404，感觉是所有项目名中带“.”的项目，如
[https://github.com/muyangplus/muyangplus.github.io](https://github.com/muyangplus/muyangplus.github.io)
且关闭后能正常访问（访问[https://muyangplus.github.io](https://muyangplus.github.io)一切正常）

使用git发送项目会报错报错内容如下
Please make sure you have the correct access rights
and the repository exists.
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (D:\Blog\website-hexo\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.cp.emit (D:\Blog\website-hexo\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
    code: 128
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

### 📷 复现步骤(Steps to Reproduce)

开启Host代理模式后访问Github所有项目带“.”的项目

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):Windows v2.6.4
- 系统版本号(OS Version): Windows7旗舰版（内部版本7601：Service Pack 1）
- 是否为应用商店版本(Whether it is a Store version): 否(No)

**Comment by rmbadmin** [comment]
已热更新修复
